import type { Recipe, Ingredient } from "./types";
import { NORTH_RECIPES } from "./recipes/north";
import { WEST_RECIPES } from "./recipes/west";
import { SOUTH_RECIPES } from "./recipes/south";
import { EAST_RECIPES } from "./recipes/east";
import { CENTRAL_RECIPES } from "./recipes/central";
import { NORTHEAST_RECIPES } from "./recipes/northeast";

const CORE_RECIPES: Recipe[] = [
  // BREAKFAST
  {
    id: "poha",
    name: "Poha",
    description: "Light flattened rice with mustard seeds, curry leaves, and peanuts",
    cuisineRegion: ["Maharashtra", "Madhya Pradesh", "Gujarat"],
    dietType: "veg",
    goalTags: ["weight_loss", "maintenance", "recovery"],
    mealType: ["breakfast"],
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 280, proteinG: 7, carbsG: 48, fatG: 7 },
    ingredients: [
      { id: "poha_rice", name: "Flattened rice (poha)", quantity: 200, unit: "g", category: "grain", searchTerms: { zepto: "poha flattened rice", instamart: "poha" } },
      { id: "onion", name: "Onion", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "onion" } },
      { id: "peanuts", name: "Peanuts", quantity: 30, unit: "g", category: "protein", searchTerms: { zepto: "peanuts raw", instamart: "groundnuts" } },
      { id: "mustard", name: "Mustard seeds", quantity: 5, unit: "g", category: "spice", searchTerms: { zepto: "mustard seeds", instamart: "rai" }, optional: true },
      { id: "curry_leaves", name: "Curry leaves", quantity: 10, unit: "leaves", category: "spice", searchTerms: { zepto: "curry leaves", instamart: "curry patta" }, optional: true },
      { id: "turmeric", name: "Turmeric", quantity: 3, unit: "g", category: "spice", searchTerms: { zepto: "turmeric powder", instamart: "haldi" } },
      { id: "lemon", name: "Lemon", quantity: 1, unit: "piece", category: "fruit", searchTerms: { zepto: "lemon", instamart: "nimbu" } },
      { id: "oil", name: "Cooking oil", quantity: 15, unit: "ml", category: "oil", searchTerms: { zepto: "sunflower oil", instamart: "cooking oil" } },
    ],
    steps: [
      "Rinse poha in a colander until soft. Drain well.",
      "Heat oil in a pan; add mustard seeds and curry leaves until they splutter.",
      "Add onion and sauté until translucent, about 3 minutes.",
      "Add turmeric and mix in poha gently; season with salt.",
      "Cover and cook for 2 minutes on low heat.",
      "Garnish with peanuts, coriander, and a squeeze of lemon.",
    ],
    image: "https://images.unsplash.com/photo-1567337710282-00832b415979?w=400",
    tags: ["quick", "light", "indian"],
  },
  {
    id: "upma",
    name: "Rava Upma",
    description: "Semolina porridge cooked with vegetables and tempering",
    cuisineRegion: ["Karnataka", "Tamil Nadu", "Andhra Pradesh", "Maharashtra"],
    dietType: "veg",
    goalTags: ["maintenance", "weight_loss", "recovery"],
    mealType: ["breakfast"],
    prepTime: 5,
    cookTime: 20,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 320, proteinG: 9, carbsG: 55, fatG: 8 },
    ingredients: [
      { id: "rava", name: "Semolina (rava)", quantity: 200, unit: "g", category: "grain", searchTerms: { zepto: "rava semolina", instamart: "suji rava" } },
      { id: "onion2", name: "Onion", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "onion" } },
      { id: "green_chili", name: "Green chilli", quantity: 2, unit: "piece", category: "spice", searchTerms: { zepto: "green chilli", instamart: "hari mirch" } },
      { id: "carrot", name: "Carrot", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "carrot", instamart: "gajar" } },
      { id: "peas_f", name: "Green peas", quantity: 50, unit: "g", category: "vegetable", searchTerms: { zepto: "green peas fresh", instamart: "matar" } },
      { id: "ghee", name: "Ghee", quantity: 20, unit: "ml", category: "oil", searchTerms: { zepto: "ghee", instamart: "desi ghee" } },
    ],
    steps: [
      "Dry roast rava on medium heat until golden. Set aside.",
      "Heat ghee; add mustard seeds, curry leaves, and chopped green chilli.",
      "Add onion and sauté until soft. Add carrot and peas; cook 3 minutes.",
      "Pour 400ml water; bring to boil. Add salt.",
      "Slowly pour rava while stirring continuously to avoid lumps.",
      "Cover and cook on low heat for 5 minutes. Serve hot.",
    ],
    image: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=400",
    tags: ["quick", "light", "south-indian"],
  },
  {
    id: "oats_bowl",
    name: "Masala Oats Bowl",
    description: "High-protein savoury oats with vegetables and spices",
    cuisineRegion: ["Pan-India"],
    dietType: "veg",
    goalTags: ["weight_loss", "diabetic", "heart", "muscle"],
    mealType: ["breakfast"],
    prepTime: 5,
    cookTime: 10,
    servings: 1,
    difficulty: "easy",
    nutrition: { calories: 320, proteinG: 14, carbsG: 45, fatG: 9 },
    ingredients: [
      { id: "oats", name: "Rolled oats", quantity: 80, unit: "g", category: "grain", searchTerms: { zepto: "rolled oats", instamart: "quaker oats" } },
      { id: "tomato", name: "Tomato", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "tomato", instamart: "tamatar" } },
      { id: "spinach", name: "Spinach", quantity: 30, unit: "g", category: "vegetable", searchTerms: { zepto: "spinach", instamart: "palak" } },
      { id: "egg_oats", name: "Egg", quantity: 1, unit: "piece", category: "protein", searchTerms: { zepto: "eggs farm fresh", instamart: "eggs" }, optional: true },
    ],
    steps: [
      "Boil 250ml water; add oats and cook for 3 minutes.",
      "Add chopped tomato, spinach, and spices (cumin, pepper, salt).",
      "Stir and cook until creamy, about 2 more minutes.",
      "Top with a poached or boiled egg for extra protein.",
    ],
    image: "https://images.unsplash.com/photo-1614961907038-c3b9023e6dd2?w=400",
    tags: ["high-protein", "quick", "healthy"],
  },
  {
    id: "idli_sambar",
    name: "Idli with Sambar",
    description: "Steamed rice cakes with lentil and vegetable stew",
    cuisineRegion: ["Tamil Nadu", "Karnataka", "Andhra Pradesh", "Kerala"],
    dietType: "veg",
    goalTags: ["maintenance", "weight_loss", "recovery", "diabetic"],
    mealType: ["breakfast"],
    prepTime: 480,
    cookTime: 20,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 350, proteinG: 12, carbsG: 62, fatG: 5 },
    ingredients: [
      { id: "idli_batter", name: "Idli batter (ready)", quantity: 400, unit: "g", category: "grain", searchTerms: { zepto: "idli batter ready", instamart: "idli batter" } },
      { id: "toor_dal", name: "Toor dal", quantity: 100, unit: "g", category: "protein", searchTerms: { zepto: "toor dal", instamart: "arhar dal" } },
      { id: "tomato2", name: "Tomato", quantity: 2, unit: "medium", category: "vegetable", searchTerms: { zepto: "tomato", instamart: "tamatar" } },
      { id: "drumstick", name: "Drumstick", quantity: 1, unit: "piece", category: "vegetable", searchTerms: { zepto: "drumstick moringa", instamart: "sahjan" }, optional: true },
    ],
    steps: [
      "Grease idli moulds with oil; pour batter and steam for 10–12 minutes.",
      "Cook toor dal until soft. Add tamarind water, tomato, drumstick, and spices.",
      "Prepare tempering with mustard, curry leaves, dried red chilli in oil; add to sambar.",
      "Boil sambar for 5 more minutes. Serve hot idlis with sambar and coconut chutney.",
    ],
    image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=400",
    tags: ["south-indian", "fermented", "classic"],
  },
  {
    id: "egg_bhurji",
    name: "Egg Bhurji",
    description: "Indian-style scrambled eggs with onion, tomato, and spices",
    cuisineRegion: ["Pan-India"],
    dietType: "egg",
    goalTags: ["muscle", "weight_loss", "recovery", "maintenance"],
    mealType: ["breakfast"],
    prepTime: 5,
    cookTime: 10,
    servings: 1,
    difficulty: "easy",
    nutrition: { calories: 290, proteinG: 18, carbsG: 12, fatG: 19 },
    ingredients: [
      { id: "eggs", name: "Eggs", quantity: 3, unit: "piece", category: "protein", searchTerms: { zepto: "eggs farm fresh", instamart: "eggs" } },
      { id: "onion3", name: "Onion", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "onion" } },
      { id: "tomato3", name: "Tomato", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "tomato", instamart: "tamatar" } },
      { id: "butter", name: "Butter", quantity: 10, unit: "g", category: "dairy", searchTerms: { zepto: "amul butter", instamart: "butter" } },
    ],
    steps: [
      "Heat butter in a pan; add chopped onion and cook until golden.",
      "Add finely chopped tomato and green chilli; cook until tomato softens.",
      "Add spices: red chilli powder, turmeric, salt, cumin.",
      "Beat eggs and pour into the pan; scramble on medium heat until just cooked.",
      "Garnish with coriander. Serve with pav or roti.",
    ],
    image: "https://images.unsplash.com/photo-1506084868230-bb9d95c24759?w=400",
    tags: ["high-protein", "quick", "filling"],
  },
  {
    id: "aloo_paratha",
    name: "Aloo Paratha",
    description: "Whole wheat flatbread stuffed with spiced mashed potato",
    cuisineRegion: ["Punjab", "Haryana", "Delhi", "Rajasthan"],
    dietType: "veg",
    goalTags: ["weight_gain", "muscle", "maintenance"],
    mealType: ["breakfast"],
    prepTime: 20,
    cookTime: 20,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 480, proteinG: 12, carbsG: 72, fatG: 16 },
    ingredients: [
      { id: "atta", name: "Whole wheat flour (atta)", quantity: 200, unit: "g", category: "grain", searchTerms: { zepto: "wheat flour atta", instamart: "atta" } },
      { id: "potato", name: "Potato", quantity: 3, unit: "medium", category: "vegetable", searchTerms: { zepto: "potato", instamart: "aloo" } },
      { id: "ghee2", name: "Ghee", quantity: 30, unit: "ml", category: "oil", searchTerms: { zepto: "ghee", instamart: "desi ghee" } },
      { id: "curd", name: "Yoghurt (curd)", quantity: 100, unit: "g", category: "dairy", searchTerms: { zepto: "curd dahi", instamart: "dahi" } },
    ],
    steps: [
      "Knead atta with water and a pinch of salt to a smooth dough. Rest 20 minutes.",
      "Boil, peel, and mash potatoes. Add spices (jeera, amchur, green chilli, coriander).",
      "Roll a dough ball flat; place potato filling in centre; seal and roll again.",
      "Cook on a hot tawa with ghee on both sides until golden.",
      "Serve hot with curd and pickle.",
    ],
    image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400",
    tags: ["north-indian", "filling", "classic"],
  },

  // LUNCH
  {
    id: "dal_chawal",
    name: "Dal Chawal",
    description: "Yellow moong dal with basmati rice — a complete protein meal",
    cuisineRegion: ["Pan-India"],
    dietType: "veg",
    goalTags: ["maintenance", "weight_loss", "recovery", "diabetic"],
    mealType: ["lunch", "dinner"],
    prepTime: 10,
    cookTime: 25,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 420, proteinG: 18, carbsG: 68, fatG: 8 },
    ingredients: [
      { id: "moong_dal", name: "Moong dal (yellow)", quantity: 150, unit: "g", category: "protein", searchTerms: { zepto: "moong dal yellow", instamart: "moong dal" } },
      { id: "rice", name: "Basmati rice", quantity: 150, unit: "g", category: "grain", searchTerms: { zepto: "basmati rice", instamart: "basmati rice" } },
      { id: "tomato4", name: "Tomato", quantity: 2, unit: "medium", category: "vegetable", searchTerms: { zepto: "tomato", instamart: "tamatar" } },
      { id: "onion4", name: "Onion", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "onion" } },
      { id: "ginger_garlic", name: "Ginger-garlic paste", quantity: 15, unit: "g", category: "spice", searchTerms: { zepto: "ginger garlic paste", instamart: "adrak lahsun paste" } },
    ],
    steps: [
      "Cook moong dal in pressure cooker with water (3 cups) for 3 whistles.",
      "Separately cook basmati rice.",
      "Prepare tadka: heat ghee, add jeera, onion, ginger-garlic paste, tomatoes, and spices.",
      "Mix tadka into cooked dal. Adjust consistency and salt.",
      "Serve dal over rice with a dollop of ghee and lemon.",
    ],
    image: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=400",
    tags: ["comfort", "complete-protein", "classic"],
  },
  {
    id: "rajma",
    name: "Rajma Chawal",
    description: "Creamy kidney bean curry with rice — the Punjab classic",
    cuisineRegion: ["Punjab", "Delhi", "Himachal Pradesh"],
    dietType: "veg",
    goalTags: ["muscle", "weight_gain", "maintenance"],
    mealType: ["lunch", "dinner"],
    prepTime: 15,
    cookTime: 40,
    servings: 3,
    difficulty: "medium",
    nutrition: { calories: 530, proteinG: 22, carbsG: 78, fatG: 12 },
    ingredients: [
      { id: "rajma", name: "Kidney beans (rajma)", quantity: 200, unit: "g", category: "protein", searchTerms: { zepto: "rajma kidney beans", instamart: "rajma" } },
      { id: "rice2", name: "Basmati rice", quantity: 150, unit: "g", category: "grain", searchTerms: { zepto: "basmati rice", instamart: "basmati rice" } },
      { id: "tomato5", name: "Tomato", quantity: 3, unit: "medium", category: "vegetable", searchTerms: { zepto: "tomato", instamart: "tamatar" } },
      { id: "onion5", name: "Onion", quantity: 2, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "onion" } },
      { id: "cream", name: "Fresh cream", quantity: 50, unit: "ml", category: "dairy", searchTerms: { zepto: "fresh cream", instamart: "cream" }, optional: true },
    ],
    steps: [
      "Soak rajma overnight; pressure cook for 6 whistles.",
      "Blend tomatoes and onion into a smooth paste; cook with oil and spices.",
      "Add cooked rajma and its water to the masala; simmer 15 minutes.",
      "Finish with cream, kasuri methi, and garam masala.",
      "Serve over fluffy basmati rice.",
    ],
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=400",
    tags: ["north-indian", "high-protein", "vegan-adaptable"],
  },
  {
    id: "palak_paneer",
    name: "Palak Paneer",
    description: "Cottage cheese in rich spinach gravy — iron and protein packed",
    cuisineRegion: ["Punjab", "Delhi", "Pan-North-India"],
    dietType: "veg",
    goalTags: ["muscle", "weight_loss", "heart", "recovery"],
    mealType: ["lunch", "dinner"],
    prepTime: 15,
    cookTime: 25,
    servings: 3,
    difficulty: "medium",
    nutrition: { calories: 380, proteinG: 20, carbsG: 18, fatG: 26 },
    ingredients: [
      { id: "spinach2", name: "Spinach (palak)", quantity: 400, unit: "g", category: "vegetable", searchTerms: { zepto: "spinach", instamart: "palak" } },
      { id: "paneer", name: "Paneer", quantity: 200, unit: "g", category: "dairy", searchTerms: { zepto: "paneer fresh", instamart: "paneer" } },
      { id: "onion6", name: "Onion", quantity: 1, unit: "large", category: "vegetable", searchTerms: { zepto: "onion", instamart: "onion" } },
      { id: "cream2", name: "Fresh cream", quantity: 40, unit: "ml", category: "dairy", searchTerms: { zepto: "fresh cream", instamart: "cream" }, optional: true },
      { id: "ginger2", name: "Ginger", quantity: 20, unit: "g", category: "spice", searchTerms: { zepto: "ginger", instamart: "adrak" } },
    ],
    steps: [
      "Blanch spinach in boiling water for 2 minutes; blend to a smooth purée.",
      "Fry paneer cubes until golden; set aside.",
      "Cook onion, ginger, garlic paste, and tomato masala in oil.",
      "Add spinach purée; simmer for 5 minutes.",
      "Add fried paneer and cream; cook another 3 minutes. Serve with roti.",
    ],
    image: "https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=400",
    tags: ["high-protein", "iron-rich", "north-indian"],
  },
  {
    id: "chicken_curry",
    name: "Chicken Curry",
    description: "Home-style chicken curry with whole spices and tomato base",
    cuisineRegion: ["Pan-India"],
    dietType: "nonveg",
    goalTags: ["muscle", "weight_loss", "recovery", "maintenance"],
    mealType: ["lunch", "dinner"],
    prepTime: 15,
    cookTime: 40,
    servings: 3,
    difficulty: "medium",
    nutrition: { calories: 410, proteinG: 36, carbsG: 14, fatG: 22 },
    ingredients: [
      { id: "chicken", name: "Chicken (curry cut)", quantity: 600, unit: "g", category: "protein", searchTerms: { zepto: "chicken curry cut", instamart: "chicken pieces" } },
      { id: "onion7", name: "Onion", quantity: 2, unit: "large", category: "vegetable", searchTerms: { zepto: "onion", instamart: "onion" } },
      { id: "tomato6", name: "Tomato", quantity: 3, unit: "medium", category: "vegetable", searchTerms: { zepto: "tomato", instamart: "tamatar" } },
      { id: "curd2", name: "Yoghurt", quantity: 100, unit: "g", category: "dairy", searchTerms: { zepto: "curd dahi", instamart: "dahi" } },
      { id: "ginger3", name: "Ginger-garlic paste", quantity: 30, unit: "g", category: "spice", searchTerms: { zepto: "ginger garlic paste", instamart: "adrak lahsun paste" } },
    ],
    steps: [
      "Marinate chicken in yoghurt, ginger-garlic paste, and spices for 30 minutes.",
      "Brown sliced onions in oil until deep golden.",
      "Add tomatoes and cook until oil separates.",
      "Add marinated chicken; cook on high heat for 5 minutes, then low heat 30 minutes.",
      "Finish with garam masala and coriander. Serve with rice or roti.",
    ],
    image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400",
    tags: ["high-protein", "classic", "north-indian"],
  },
  {
    id: "sambhar_rice",
    name: "Sambar Rice",
    description: "One-pot comfort meal with lentils, vegetables, and tamarind",
    cuisineRegion: ["Tamil Nadu", "Karnataka", "Kerala"],
    dietType: "veg",
    goalTags: ["maintenance", "weight_loss", "diabetic", "heart"],
    mealType: ["lunch", "dinner"],
    prepTime: 15,
    cookTime: 30,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 440, proteinG: 15, carbsG: 72, fatG: 9 },
    ingredients: [
      { id: "toor2", name: "Toor dal", quantity: 100, unit: "g", category: "protein", searchTerms: { zepto: "toor dal", instamart: "arhar dal" } },
      { id: "rice3", name: "Rice", quantity: 150, unit: "g", category: "grain", searchTerms: { zepto: "rice", instamart: "rice" } },
      { id: "brinjal", name: "Brinjal (eggplant)", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "brinjal eggplant", instamart: "baingan" } },
      { id: "tamarind", name: "Tamarind paste", quantity: 15, unit: "g", category: "spice", searchTerms: { zepto: "tamarind paste", instamart: "imli paste" } },
      { id: "sambar_pwd", name: "Sambar powder", quantity: 10, unit: "g", category: "spice", searchTerms: { zepto: "sambar powder", instamart: "sambar masala" } },
    ],
    steps: [
      "Cook toor dal and rice together in a pressure cooker with 600ml water (4 whistles).",
      "Prepare sambar: cook vegetables with tamarind water, tomato, and sambar powder.",
      "Mix cooked dal+rice into the sambar; adjust consistency.",
      "Prepare tadka with ghee, mustard, curry leaves, and hing; pour over rice.",
      "Serve hot with papad and pickle.",
    ],
    image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=400",
    tags: ["south-indian", "one-pot", "comfort"],
  },

  // DINNER
  {
    id: "khichdi",
    name: "Moong Dal Khichdi",
    description: "Healing one-pot rice and lentil porridge — gentle and nourishing",
    cuisineRegion: ["Pan-India"],
    dietType: "veg",
    goalTags: ["recovery", "diabetic", "weight_loss", "maintenance"],
    mealType: ["dinner", "lunch"],
    prepTime: 10,
    cookTime: 25,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 380, proteinG: 16, carbsG: 60, fatG: 9 },
    ingredients: [
      { id: "moong2", name: "Moong dal (split)", quantity: 100, unit: "g", category: "protein", searchTerms: { zepto: "moong dal split yellow", instamart: "dhuli moong dal" } },
      { id: "rice4", name: "Rice", quantity: 100, unit: "g", category: "grain", searchTerms: { zepto: "rice", instamart: "rice" } },
      { id: "ghee3", name: "Ghee", quantity: 20, unit: "ml", category: "oil", searchTerms: { zepto: "ghee", instamart: "desi ghee" } },
      { id: "ginger4", name: "Ginger (grated)", quantity: 10, unit: "g", category: "spice", searchTerms: { zepto: "ginger", instamart: "adrak" } },
    ],
    steps: [
      "Wash and soak rice and moong dal together for 20 minutes.",
      "Heat ghee in pressure cooker; add cumin seeds, ginger, and turmeric.",
      "Add dal and rice; pour 4 cups of water. Add salt.",
      "Pressure cook for 4 whistles; mash slightly for a creamy texture.",
      "Serve hot with ghee drizzled on top and pickle on the side.",
    ],
    image: "https://images.unsplash.com/photo-1567337710282-00832b415979?w=400",
    tags: ["healing", "easy-digest", "one-pot"],
  },
  {
    id: "fish_curry",
    name: "Goan Fish Curry",
    description: "Tangy coconut-based fish curry with Kashmiri chilli",
    cuisineRegion: ["Goa", "Kerala", "Coastal Maharashtra"],
    dietType: "nonveg",
    goalTags: ["heart", "weight_loss", "maintenance", "recovery"],
    mealType: ["lunch", "dinner"],
    prepTime: 15,
    cookTime: 25,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 390, proteinG: 32, carbsG: 18, fatG: 22 },
    ingredients: [
      { id: "fish", name: "Surmai / Pomfret (fish)", quantity: 400, unit: "g", category: "protein", searchTerms: { zepto: "surmai fish", instamart: "pomfret fish" } },
      { id: "coconut_milk", name: "Coconut milk", quantity: 200, unit: "ml", category: "other", searchTerms: { zepto: "coconut milk", instamart: "nariyal milk" } },
      { id: "tomato7", name: "Tomato", quantity: 2, unit: "medium", category: "vegetable", searchTerms: { zepto: "tomato", instamart: "tamatar" } },
      { id: "tamarind2", name: "Tamarind", quantity: 15, unit: "g", category: "spice", searchTerms: { zepto: "tamarind", instamart: "imli" } },
    ],
    steps: [
      "Marinate fish with salt, turmeric, and lemon juice for 15 minutes.",
      "Blend coconut milk, Kashmiri red chilli, cumin, coriander into a paste.",
      "Cook onion in oil; add ground masala and tomato; simmer 5 minutes.",
      "Add coconut milk and tamarind; bring to a gentle boil.",
      "Add fish and cook for 10–12 minutes until done. Serve with rice.",
    ],
    image: "https://images.unsplash.com/photo-1559847844-5315695dadae?w=400",
    tags: ["coastal", "omega-3", "goan"],
  },
  // ADDITIONAL BREAKFAST
  {
    id: "moong_chilla",
    name: "Moong Dal Chilla",
    description: "Protein-rich green gram savoury pancakes with ginger and green chilli",
    cuisineRegion: ["Rajasthan", "Gujarat", "Pan-India"],
    dietType: "veg",
    goalTags: ["muscle", "weight_loss", "maintenance", "diabetic"],
    mealType: ["breakfast"],
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 270, proteinG: 18, carbsG: 36, fatG: 6 },
    ingredients: [
      { id: "green_moong", name: "Green moong dal", quantity: 200, unit: "g", category: "protein", searchTerms: { zepto: "green moong dal", instamart: "moong sabut" } },
      { id: "ginger5", name: "Ginger", quantity: 10, unit: "g", category: "spice", searchTerms: { zepto: "ginger", instamart: "adrak" } },
      { id: "green_chili2", name: "Green chilli", quantity: 2, unit: "piece", category: "spice", searchTerms: { zepto: "green chilli", instamart: "hari mirch" } },
      { id: "oil2", name: "Cooking oil", quantity: 15, unit: "ml", category: "oil", searchTerms: { zepto: "sunflower oil", instamart: "cooking oil" } },
      { id: "onion9", name: "Onion (finely chopped)", quantity: 1, unit: "small", category: "vegetable", searchTerms: { zepto: "onion", instamart: "onion" } },
    ],
    steps: [
      "Soak green moong dal for 4 hours or overnight; drain and grind to a coarse batter.",
      "Mix in chopped ginger, green chilli, onion, salt, and cumin.",
      "Heat a non-stick pan; pour a ladleful of batter and spread thin.",
      "Drizzle a little oil around the edges; cook until golden and crisp.",
      "Flip and cook the other side. Serve with green chutney or curd.",
    ],
    tags: ["high-protein", "quick", "healthy"],
  },
  {
    id: "besan_cheela",
    name: "Besan Cheela",
    description: "Crispy chickpea flour savoury crepes with onion and tomato",
    cuisineRegion: ["Rajasthan", "Uttar Pradesh", "Gujarat", "Pan-India"],
    dietType: "veg",
    goalTags: ["weight_loss", "muscle", "maintenance", "diabetic"],
    mealType: ["breakfast"],
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 290, proteinG: 14, carbsG: 38, fatG: 9 },
    ingredients: [
      { id: "besan", name: "Besan (chickpea flour)", quantity: 150, unit: "g", category: "grain", searchTerms: { zepto: "besan gram flour", instamart: "besan" } },
      { id: "onion10", name: "Onion", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "onion" } },
      { id: "tomato9", name: "Tomato", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "tomato", instamart: "tamatar" } },
      { id: "green_chili3", name: "Green chilli", quantity: 1, unit: "piece", category: "spice", searchTerms: { zepto: "green chilli", instamart: "hari mirch" } },
      { id: "oil3", name: "Cooking oil", quantity: 15, unit: "ml", category: "oil", searchTerms: { zepto: "sunflower oil", instamart: "cooking oil" } },
    ],
    steps: [
      "Mix besan with water to make a smooth, thin batter (like dosa batter).",
      "Add finely chopped onion, tomato, green chilli, salt, and ajwain.",
      "Heat a tawa on medium; pour batter and spread into a thin circle.",
      "Drizzle oil; cook until edges turn golden. Flip and cook 1 more minute.",
      "Serve with mint chutney or pickle.",
    ],
    tags: ["quick", "protein-rich", "vegan"],
  },
  {
    id: "dalia_upma",
    name: "Dalia Upma",
    description: "Broken wheat savoury porridge with vegetables — high fibre and filling",
    cuisineRegion: ["Pan-India"],
    dietType: "veg",
    goalTags: ["weight_loss", "diabetic", "heart", "maintenance"],
    mealType: ["breakfast"],
    prepTime: 5,
    cookTime: 20,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 300, proteinG: 10, carbsG: 50, fatG: 7 },
    ingredients: [
      { id: "dalia", name: "Dalia (broken wheat)", quantity: 150, unit: "g", category: "grain", searchTerms: { zepto: "dalia broken wheat", instamart: "daliya" } },
      { id: "onion11", name: "Onion", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "onion" } },
      { id: "carrot2", name: "Carrot", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "carrot", instamart: "gajar" } },
      { id: "peas2", name: "Green peas", quantity: 50, unit: "g", category: "vegetable", searchTerms: { zepto: "green peas", instamart: "matar" } },
      { id: "ghee4", name: "Ghee", quantity: 15, unit: "ml", category: "oil", searchTerms: { zepto: "ghee", instamart: "desi ghee" } },
    ],
    steps: [
      "Dry roast dalia in a pan for 3–4 minutes until lightly golden. Set aside.",
      "Heat ghee; add mustard seeds and curry leaves until they splutter.",
      "Add onion, carrot, and peas; sauté for 3 minutes.",
      "Add roasted dalia, 400ml water, and salt; cover and cook on low heat for 12 minutes.",
      "Stir and serve hot with a squeeze of lemon.",
    ],
    tags: ["high-fibre", "light", "weight-loss"],
  },

  // ADDITIONAL LUNCH / DINNER
  {
    id: "chana_masala",
    name: "Chana Masala",
    description: "Bold chickpea curry with tangy tomato gravy and whole spices",
    cuisineRegion: ["Punjab", "Delhi", "Pan-North-India"],
    dietType: "veg",
    goalTags: ["muscle", "weight_gain", "heart", "maintenance"],
    mealType: ["lunch", "dinner"],
    prepTime: 15,
    cookTime: 35,
    servings: 3,
    difficulty: "medium",
    nutrition: { calories: 420, proteinG: 20, carbsG: 56, fatG: 14 },
    ingredients: [
      { id: "chickpeas", name: "Chickpeas (kabuli chana)", quantity: 250, unit: "g", category: "protein", searchTerms: { zepto: "kabuli chana chickpeas", instamart: "chana" } },
      { id: "onion12", name: "Onion", quantity: 2, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "onion" } },
      { id: "tomato10", name: "Tomato", quantity: 2, unit: "medium", category: "vegetable", searchTerms: { zepto: "tomato", instamart: "tamatar" } },
      { id: "ginger6", name: "Ginger-garlic paste", quantity: 20, unit: "g", category: "spice", searchTerms: { zepto: "ginger garlic paste", instamart: "adrak lahsun paste" } },
      { id: "chana_masala_pwd", name: "Chana masala powder", quantity: 15, unit: "g", category: "spice", searchTerms: { zepto: "chana masala powder", instamart: "chana masala" } },
    ],
    steps: [
      "Soak chickpeas overnight; pressure cook for 5–6 whistles until soft.",
      "Blend onion and tomato; cook the masala in oil until it darkens and oil separates.",
      "Add ginger-garlic paste and chana masala powder; cook 2 minutes.",
      "Add chickpeas with their cooking water; simmer 15 minutes.",
      "Finish with amchur, kasuri methi, and garam masala. Serve with bhature or rice.",
    ],
    tags: ["high-protein", "vegan", "north-indian"],
  },
  {
    id: "veg_pulao",
    name: "Vegetable Pulao",
    description: "Fragrant basmati rice with seasonal vegetables and whole spices",
    cuisineRegion: ["Pan-India"],
    dietType: "veg",
    goalTags: ["maintenance", "weight_loss", "recovery", "heart"],
    mealType: ["lunch", "dinner"],
    prepTime: 15,
    cookTime: 25,
    servings: 3,
    difficulty: "easy",
    nutrition: { calories: 370, proteinG: 9, carbsG: 66, fatG: 8 },
    ingredients: [
      { id: "rice5", name: "Basmati rice", quantity: 200, unit: "g", category: "grain", searchTerms: { zepto: "basmati rice", instamart: "basmati rice" } },
      { id: "mixed_veg", name: "Mixed vegetables (carrot, beans, peas)", quantity: 200, unit: "g", category: "vegetable", searchTerms: { zepto: "mixed vegetables frozen", instamart: "mix veg" } },
      { id: "onion13", name: "Onion", quantity: 1, unit: "large", category: "vegetable", searchTerms: { zepto: "onion", instamart: "onion" } },
      { id: "ghee5", name: "Ghee", quantity: 20, unit: "ml", category: "oil", searchTerms: { zepto: "ghee", instamart: "desi ghee" } },
      { id: "whole_spices", name: "Whole spices (bay leaf, cloves, cardamom)", quantity: 5, unit: "g", category: "spice", searchTerms: { zepto: "whole spices", instamart: "garam masala sabut" } },
    ],
    steps: [
      "Soak rice for 20 minutes; drain.",
      "Heat ghee in a heavy pot; add whole spices and let them splutter.",
      "Add sliced onion and fry until golden.",
      "Add vegetables and sauté for 2 minutes. Add rice and stir gently.",
      "Add 400ml water and salt; cover and cook on low heat for 15 minutes.",
      "Fluff with a fork. Serve with raita.",
    ],
    tags: ["aromatic", "easy", "one-pot"],
  },
  {
    id: "aloo_gobi",
    name: "Aloo Gobi",
    description: "Dry potato and cauliflower stir-fry with cumin and spices",
    cuisineRegion: ["Punjab", "Uttar Pradesh", "Pan-North-India"],
    dietType: "veg",
    goalTags: ["weight_loss", "maintenance", "heart", "diabetic"],
    mealType: ["lunch", "dinner"],
    prepTime: 15,
    cookTime: 25,
    servings: 3,
    difficulty: "easy",
    nutrition: { calories: 280, proteinG: 7, carbsG: 40, fatG: 10 },
    ingredients: [
      { id: "potato2", name: "Potato", quantity: 2, unit: "medium", category: "vegetable", searchTerms: { zepto: "potato", instamart: "aloo" } },
      { id: "gobi", name: "Cauliflower (gobi)", quantity: 400, unit: "g", category: "vegetable", searchTerms: { zepto: "cauliflower", instamart: "gobi" } },
      { id: "onion14", name: "Onion", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "onion" } },
      { id: "tomato11", name: "Tomato", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "tomato", instamart: "tamatar" } },
      { id: "oil4", name: "Cooking oil", quantity: 20, unit: "ml", category: "oil", searchTerms: { zepto: "sunflower oil", instamart: "cooking oil" } },
    ],
    steps: [
      "Cut potato into cubes; break cauliflower into florets.",
      "Heat oil; add cumin seeds, let them splutter.",
      "Add onion and cook until soft. Add chopped tomato and spices.",
      "Add potato and cook for 5 minutes; add cauliflower, mix well.",
      "Cover and cook on low heat for 15 minutes, stirring occasionally.",
      "Garnish with coriander. Serve with roti or dal.",
    ],
    tags: ["dry-sabzi", "north-indian", "light"],
  },
  {
    id: "baingan_bharta",
    name: "Baingan Bharta",
    description: "Smoky flame-roasted eggplant mashed with onion, tomato, and spices",
    cuisineRegion: ["Punjab", "Rajasthan", "Pan-North-India"],
    dietType: "veg",
    goalTags: ["weight_loss", "heart", "maintenance", "diabetic"],
    mealType: ["lunch", "dinner"],
    prepTime: 10,
    cookTime: 30,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 230, proteinG: 6, carbsG: 26, fatG: 12 },
    ingredients: [
      { id: "baingan", name: "Brinjal / Eggplant (large)", quantity: 1, unit: "large", category: "vegetable", searchTerms: { zepto: "large brinjal eggplant", instamart: "baingan" } },
      { id: "onion15", name: "Onion", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "onion" } },
      { id: "tomato12", name: "Tomato", quantity: 2, unit: "medium", category: "vegetable", searchTerms: { zepto: "tomato", instamart: "tamatar" } },
      { id: "ginger7", name: "Ginger", quantity: 15, unit: "g", category: "spice", searchTerms: { zepto: "ginger", instamart: "adrak" } },
      { id: "oil5", name: "Cooking oil", quantity: 20, unit: "ml", category: "oil", searchTerms: { zepto: "sunflower oil", instamart: "cooking oil" } },
    ],
    steps: [
      "Roast eggplant directly on a flame or in the oven until charred and soft.",
      "Peel off the burnt skin; mash the pulp.",
      "Heat oil; sauté onion until golden. Add ginger and cook 1 minute.",
      "Add chopped tomato and spices (cumin, coriander, red chilli); cook until oil separates.",
      "Mix in mashed eggplant; cook together for 5 minutes.",
      "Garnish with coriander and a squeeze of lemon. Serve with roti.",
    ],
    tags: ["smoky", "low-calorie", "north-indian"],
  },

  {
    id: "paneer_bhurji",
    name: "Paneer Bhurji",
    description: "Scrambled cottage cheese with peppers, onion, and spices",
    cuisineRegion: ["Pan-India"],
    dietType: "veg",
    goalTags: ["muscle", "weight_loss", "recovery", "maintenance"],
    mealType: ["breakfast", "dinner"],
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 340, proteinG: 22, carbsG: 14, fatG: 24 },
    ingredients: [
      { id: "paneer2", name: "Paneer", quantity: 250, unit: "g", category: "dairy", searchTerms: { zepto: "paneer fresh", instamart: "paneer" } },
      { id: "capsicum", name: "Capsicum", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "capsicum bell pepper", instamart: "shimla mirch" } },
      { id: "onion8", name: "Onion", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "onion" } },
      { id: "tomato8", name: "Tomato", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "tomato", instamart: "tamatar" } },
    ],
    steps: [
      "Crumble paneer into small pieces by hand.",
      "Sauté onion, capsicum, and green chilli in oil until soft.",
      "Add tomato and cook until mushy. Add spices (cumin, pepper, garam masala).",
      "Add crumbled paneer; mix gently. Cook 3–4 minutes.",
      "Garnish with coriander. Serve with roti or pav.",
    ],
    image: "https://images.unsplash.com/photo-1567337710282-00832b415979?w=400",
    tags: ["high-protein", "quick", "vegetarian"],
  },
];

// Statewide regional library (see recipes.md for the full researched knowledge base
// this was generated from) — one breakfast/lunch/snack/dinner recipe per state/UT
// across six culinary zones, on top of the hand-curated CORE_RECIPES above.
export const RECIPES: Recipe[] = [
  ...CORE_RECIPES,
  ...NORTH_RECIPES,
  ...WEST_RECIPES,
  ...SOUTH_RECIPES,
  ...EAST_RECIPES,
  ...CENTRAL_RECIPES,
  ...NORTHEAST_RECIPES,
];

export function getRecipeById(id: string): Recipe | undefined {
  return RECIPES.find((r) => r.id === id);
}

let ingredientIndex: Map<string, Ingredient> | null = null;

/** Ingredient ids are only unique within a recipe (e.g. "onion", "onion2",
 *  "onion3" across different recipes) — this looks up by that scoped id, not
 *  by ingredient name, so pass the same id ShoppingItem.ingredientId carries. */
export function getIngredientById(id: string): Ingredient | undefined {
  if (!ingredientIndex) {
    ingredientIndex = new Map();
    for (const recipe of RECIPES) {
      for (const ingredient of recipe.ingredients) {
        if (!ingredientIndex.has(ingredient.id)) ingredientIndex.set(ingredient.id, ingredient);
      }
    }
  }
  return ingredientIndex.get(id);
}

export function filterRecipes(params: {
  dietType: string;
  mealType?: string;
  goalTags?: string[];
  state?: string;
  excludeIds?: string[];
}): Recipe[] {
  return RECIPES.filter((r) => {
    if (params.dietType === "veg" && r.dietType !== "veg") return false;
    if (params.dietType === "egg" && r.dietType === "nonveg") return false;
    if (params.mealType && !r.mealType.includes(params.mealType as never)) return false;
    if (params.goalTags?.length && !params.goalTags.some((g) => r.goalTags.includes(g as never))) return false;
    if (params.state && !r.cuisineRegion.includes(params.state) && !r.cuisineRegion.includes("Pan-India")) return false;
    if (params.excludeIds?.includes(r.id)) return false;
    return true;
  });
}
