import type { Recipe } from "../types";

// Auto-generated from regional recipe research (Central zone).
export const CENTRAL_RECIPES: Recipe[] = [
  {
    id: "uttar_pradesh_breakfast_kachori_sabzi",
    name: "Kachori Sabzi",
    description: "Deep-fried spiced urad dal-stuffed kachoris served with a tangy, mildly spiced potato curry, a much-loved Uttar Pradesh breakfast.",
    cuisineRegion: ["Uttar Pradesh"],
    dietType: "veg",
    goalTags: ["maintenance"],
    mealType: ["breakfast"],
    prepTime: 25,
    cookTime: 30,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 480, proteinG: 11, carbsG: 60, fatG: 22 },
    ingredients: [
      { id: "uttar_pradesh_breakfast_kachori_sabzi_wheat_flour_maida", name: "Wheat flour (maida)", quantity: 150, unit: "g", category: "grain", searchTerms: { zepto: "refined flour maida", instamart: "maida" } },
      { id: "uttar_pradesh_breakfast_kachori_sabzi_urad_dal_split", name: "Urad dal (split)", quantity: 50, unit: "g", category: "protein", searchTerms: { zepto: "urad dal split", instamart: "urad dal dhuli" } },
      { id: "uttar_pradesh_breakfast_kachori_sabzi_fennel_seeds", name: "Fennel seeds", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "fennel seeds saunf", instamart: "saunf" }, optional: true },
      { id: "uttar_pradesh_breakfast_kachori_sabzi_potato", name: "Potato", quantity: 300, unit: "g", category: "vegetable", searchTerms: { zepto: "potato", instamart: "aloo" } },
      { id: "uttar_pradesh_breakfast_kachori_sabzi_tomato", name: "Tomato", quantity: 150, unit: "g", category: "vegetable", searchTerms: { zepto: "tomato", instamart: "tamatar" } },
      { id: "uttar_pradesh_breakfast_kachori_sabzi_ginger", name: "Ginger", quantity: 15, unit: "g", category: "vegetable", searchTerms: { zepto: "fresh ginger", instamart: "adrak" }, optional: true },
      { id: "uttar_pradesh_breakfast_kachori_sabzi_green_chili", name: "Green chili", quantity: 2, unit: "piece", category: "vegetable", searchTerms: { zepto: "green chili", instamart: "hari mirch" }, optional: true },
      { id: "uttar_pradesh_breakfast_kachori_sabzi_turmeric_powder", name: "Turmeric powder", quantity: 0.5, unit: "tsp", category: "spice", searchTerms: { zepto: "turmeric powder haldi", instamart: "haldi" } },
      { id: "uttar_pradesh_breakfast_kachori_sabzi_red_chili_powder", name: "Red chili powder", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "red chili powder", instamart: "lal mirch powder" } },
      { id: "uttar_pradesh_breakfast_kachori_sabzi_cooking_oil", name: "Cooking oil", quantity: 400, unit: "ml", category: "oil", searchTerms: { zepto: "refined cooking oil", instamart: "tel" } }
    ],
    steps: [
      "Soak urad dal for 2 hours, then grind coarsely with fennel seeds, ginger and green chili to make the stuffing.",
      "Knead a stiff dough with maida, a little oil and water; rest for 20 minutes.",
      "Stuff small dough balls with the dal mixture, flatten gently into discs, and deep fry on low-medium heat until golden and crisp.",
      "Boil and lightly mash the potatoes; sauté with chopped tomato, ginger, turmeric and red chili powder in a little oil, then add water to form a thin gravy and simmer 10 minutes.",
      "Serve the hot kachoris crushed lightly into the sabzi, garnished with coriander."
    ],
    tags: ["spicy", "deep-fried", "traditional", "street-food"],
  },
  {
    id: "uttar_pradesh_lunch_tehri_vegetable_pulao",
    name: "Tehri (Vegetable Pulao)",
    description: "A one-pot turmeric-spiced vegetable rice pulao made with everyday vegetables, a humble yet iconic UP lunch staple.",
    cuisineRegion: ["Uttar Pradesh"],
    dietType: "veg",
    goalTags: ["maintenance"],
    mealType: ["lunch"],
    prepTime: 15,
    cookTime: 25,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 420, proteinG: 8, carbsG: 70, fatG: 12 },
    ingredients: [
      { id: "uttar_pradesh_lunch_tehri_vegetable_pulao_basmati_rice", name: "Basmati rice", quantity: 200, unit: "g", category: "grain", searchTerms: { zepto: "basmati rice", instamart: "chawal" } },
      { id: "uttar_pradesh_lunch_tehri_vegetable_pulao_potato", name: "Potato", quantity: 100, unit: "g", category: "vegetable", searchTerms: { zepto: "potato", instamart: "aloo" } },
      { id: "uttar_pradesh_lunch_tehri_vegetable_pulao_cauliflower", name: "Cauliflower", quantity: 100, unit: "g", category: "vegetable", searchTerms: { zepto: "cauliflower", instamart: "phool gobi" } },
      { id: "uttar_pradesh_lunch_tehri_vegetable_pulao_carrot", name: "Carrot", quantity: 50, unit: "g", category: "vegetable", searchTerms: { zepto: "carrot", instamart: "gajar" }, optional: true },
      { id: "uttar_pradesh_lunch_tehri_vegetable_pulao_green_peas", name: "Green peas", quantity: 50, unit: "g", category: "vegetable", searchTerms: { zepto: "green peas", instamart: "matar" }, optional: true },
      { id: "uttar_pradesh_lunch_tehri_vegetable_pulao_onion", name: "Onion", quantity: 100, unit: "g", category: "vegetable", searchTerms: { zepto: "onion", instamart: "pyaz" } },
      { id: "uttar_pradesh_lunch_tehri_vegetable_pulao_ginger_garlic_paste", name: "Ginger-garlic paste", quantity: 10, unit: "g", category: "vegetable", searchTerms: { zepto: "ginger garlic paste", instamart: "adrak lehsun paste" } },
      { id: "uttar_pradesh_lunch_tehri_vegetable_pulao_cumin_seeds", name: "Cumin seeds", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "cumin seeds jeera", instamart: "jeera" }, optional: true },
      { id: "uttar_pradesh_lunch_tehri_vegetable_pulao_turmeric_powder", name: "Turmeric powder", quantity: 0.5, unit: "tsp", category: "spice", searchTerms: { zepto: "turmeric powder haldi", instamart: "haldi" } },
      { id: "uttar_pradesh_lunch_tehri_vegetable_pulao_ghee", name: "Ghee", quantity: 2, unit: "tbsp", category: "oil", searchTerms: { zepto: "ghee", instamart: "desi ghee" } }
    ],
    steps: [
      "Wash and soak the rice for 20 minutes, then drain.",
      "Heat ghee, splutter cumin seeds, and sauté onions until golden.",
      "Add ginger-garlic paste, turmeric and all chopped vegetables; sauté for 5 minutes.",
      "Add the drained rice, salt and water (1:2 ratio); bring to a boil.",
      "Cover and cook on low heat for about 15 minutes until the rice is fluffy and fully cooked.",
      "Fluff gently and serve hot with raita or a simple salad."
    ],
    tags: ["one-pot", "comfort", "quick", "homestyle"],
  },
  {
    id: "uttar_pradesh_snack_aloo_tikki_chaat",
    name: "Aloo Tikki Chaat",
    description: "Crisp shallow-fried potato patties topped with tangy tamarind and mint chutneys, yogurt and sev — a classic UP street-food snack.",
    cuisineRegion: ["Uttar Pradesh"],
    dietType: "veg",
    goalTags: ["maintenance"],
    mealType: ["snack"],
    prepTime: 20,
    cookTime: 20,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 380, proteinG: 8, carbsG: 52, fatG: 15 },
    ingredients: [
      { id: "uttar_pradesh_snack_aloo_tikki_chaat_potato", name: "Potato", quantity: 300, unit: "g", category: "vegetable", searchTerms: { zepto: "potato", instamart: "aloo" } },
      { id: "uttar_pradesh_snack_aloo_tikki_chaat_cornflour", name: "Cornflour", quantity: 20, unit: "g", category: "other", searchTerms: { zepto: "cornflour", instamart: "corn flour" } },
      { id: "uttar_pradesh_snack_aloo_tikki_chaat_green_chili", name: "Green chili", quantity: 1, unit: "piece", category: "vegetable", searchTerms: { zepto: "green chili", instamart: "hari mirch" }, optional: true },
      { id: "uttar_pradesh_snack_aloo_tikki_chaat_curd_yogurt", name: "Curd (yogurt)", quantity: 100, unit: "g", category: "dairy", searchTerms: { zepto: "fresh curd", instamart: "dahi" } },
      { id: "uttar_pradesh_snack_aloo_tikki_chaat_tamarind_chutney", name: "Tamarind chutney", quantity: 30, unit: "g", category: "other", searchTerms: { zepto: "tamarind chutney", instamart: "imli chutney" } },
      { id: "uttar_pradesh_snack_aloo_tikki_chaat_mint_coriander_chutney", name: "Mint-coriander chutney", quantity: 30, unit: "g", category: "other", searchTerms: { zepto: "mint coriander chutney", instamart: "hari chutney" } },
      { id: "uttar_pradesh_snack_aloo_tikki_chaat_sev", name: "Sev", quantity: 30, unit: "g", category: "other", searchTerms: { zepto: "sev namkeen", instamart: "sev" } },
      { id: "uttar_pradesh_snack_aloo_tikki_chaat_chaat_masala", name: "Chaat masala", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "chaat masala", instamart: "chaat masala" }, optional: true },
      { id: "uttar_pradesh_snack_aloo_tikki_chaat_cooking_oil", name: "Cooking oil", quantity: 3, unit: "tbsp", category: "oil", searchTerms: { zepto: "refined cooking oil", instamart: "tel" } }
    ],
    steps: [
      "Boil and mash the potatoes; mix with cornflour, chopped green chili and salt, then shape into flat patties.",
      "Shallow fry the patties on a griddle until golden and crisp on both sides.",
      "Whisk the curd smooth; keep the tamarind and mint chutneys ready.",
      "Plate the hot tikkis and top with curd, both chutneys and chaat masala.",
      "Sprinkle sev over the top and serve immediately."
    ],
    tags: ["street-food", "tangy", "quick", "chaat"],
  },
  {
    id: "uttar_pradesh_dinner_murgh_korma_awadhi_chicken_korma",
    name: "Murgh Korma (Awadhi Chicken Korma)",
    description: "A rich, mildly spiced Lucknowi chicken curry braised in a cashew-onion-yogurt gravy, a signature Awadhi dinner dish.",
    cuisineRegion: ["Uttar Pradesh"],
    dietType: "nonveg",
    goalTags: ["maintenance", "muscle", "recovery", "weight_gain"],
    mealType: ["dinner"],
    prepTime: 25,
    cookTime: 35,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 480, proteinG: 32, carbsG: 12, fatG: 32 },
    ingredients: [
      { id: "uttar_pradesh_dinner_murgh_korma_awadhi_chicken_korma_chicken_curry_cut_bone_in", name: "Chicken (curry cut, bone-in)", quantity: 500, unit: "g", category: "protein", searchTerms: { zepto: "chicken curry cut", instamart: "chicken" } },
      { id: "uttar_pradesh_dinner_murgh_korma_awadhi_chicken_korma_curd_yogurt", name: "Curd (yogurt)", quantity: 150, unit: "g", category: "dairy", searchTerms: { zepto: "fresh curd", instamart: "dahi" } },
      { id: "uttar_pradesh_dinner_murgh_korma_awadhi_chicken_korma_cashew_nuts", name: "Cashew nuts", quantity: 30, unit: "g", category: "other", searchTerms: { zepto: "cashew nuts kaju", instamart: "kaju" } },
      { id: "uttar_pradesh_dinner_murgh_korma_awadhi_chicken_korma_onion", name: "Onion", quantity: 150, unit: "g", category: "vegetable", searchTerms: { zepto: "onion", instamart: "pyaz" } },
      { id: "uttar_pradesh_dinner_murgh_korma_awadhi_chicken_korma_ginger_garlic_paste", name: "Ginger-garlic paste", quantity: 15, unit: "g", category: "vegetable", searchTerms: { zepto: "ginger garlic paste", instamart: "adrak lehsun paste" } },
      { id: "uttar_pradesh_dinner_murgh_korma_awadhi_chicken_korma_green_cardamom", name: "Green cardamom", quantity: 3, unit: "piece", category: "spice", searchTerms: { zepto: "green cardamom elaichi", instamart: "elaichi" }, optional: true },
      { id: "uttar_pradesh_dinner_murgh_korma_awadhi_chicken_korma_cinnamon_stick", name: "Cinnamon stick", quantity: 1, unit: "piece", category: "spice", searchTerms: { zepto: "cinnamon stick dalchini", instamart: "dalchini" }, optional: true },
      { id: "uttar_pradesh_dinner_murgh_korma_awadhi_chicken_korma_red_chili_powder", name: "Red chili powder", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "red chili powder", instamart: "lal mirch powder" } },
      { id: "uttar_pradesh_dinner_murgh_korma_awadhi_chicken_korma_ghee", name: "Ghee", quantity: 3, unit: "tbsp", category: "oil", searchTerms: { zepto: "ghee", instamart: "desi ghee" } }
    ],
    steps: [
      "Fry sliced onions until deep golden, then blend to a smooth paste along with soaked cashews.",
      "Marinate the chicken with curd, ginger-garlic paste and a pinch of turmeric for 20 minutes.",
      "Heat ghee, temper the whole spices, add the marinated chicken and sear for 5 minutes.",
      "Stir in the onion-cashew paste and red chili powder; cover and cook on low heat until the chicken is tender, about 20-25 minutes.",
      "Adjust consistency with a little water and season with salt.",
      "Serve hot with sheermal or steamed rice."
    ],
    tags: ["rich", "festive", "awadhi", "creamy"],
  },
  {
    id: "madhya_pradesh_breakfast_indori_poha",
    name: "Indori Poha",
    description: "Flattened rice tempered with mustard seeds and curry leaves, topped with sev, pomegranate and lemon — Indore's most iconic breakfast.",
    cuisineRegion: ["Madhya Pradesh"],
    dietType: "veg",
    goalTags: ["maintenance"],
    mealType: ["breakfast"],
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 320, proteinG: 6, carbsG: 55, fatG: 9 },
    ingredients: [
      { id: "madhya_pradesh_breakfast_indori_poha_thick_poha_flattened_rice", name: "Thick poha (flattened rice)", quantity: 200, unit: "g", category: "grain", searchTerms: { zepto: "thick poha flattened rice", instamart: "poha" } },
      { id: "madhya_pradesh_breakfast_indori_poha_potato", name: "Potato", quantity: 100, unit: "g", category: "vegetable", searchTerms: { zepto: "potato", instamart: "aloo" }, optional: true },
      { id: "madhya_pradesh_breakfast_indori_poha_onion", name: "Onion", quantity: 80, unit: "g", category: "vegetable", searchTerms: { zepto: "onion", instamart: "pyaz" }, optional: true },
      { id: "madhya_pradesh_breakfast_indori_poha_mustard_seeds", name: "Mustard seeds", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "mustard seeds rai", instamart: "rai" }, optional: true },
      { id: "madhya_pradesh_breakfast_indori_poha_curry_leaves", name: "Curry leaves", quantity: 8, unit: "piece", category: "spice", searchTerms: { zepto: "curry leaves", instamart: "kadi patta" }, optional: true },
      { id: "madhya_pradesh_breakfast_indori_poha_green_chili", name: "Green chili", quantity: 1, unit: "piece", category: "vegetable", searchTerms: { zepto: "green chili", instamart: "hari mirch" }, optional: true },
      { id: "madhya_pradesh_breakfast_indori_poha_turmeric_powder", name: "Turmeric powder", quantity: 0.5, unit: "tsp", category: "spice", searchTerms: { zepto: "turmeric powder haldi", instamart: "haldi" } },
      { id: "madhya_pradesh_breakfast_indori_poha_sev", name: "Sev", quantity: 30, unit: "g", category: "other", searchTerms: { zepto: "sev namkeen", instamart: "sev" } },
      { id: "madhya_pradesh_breakfast_indori_poha_lemon", name: "Lemon", quantity: 1, unit: "piece", category: "fruit", searchTerms: { zepto: "lemon", instamart: "nimbu" } },
      { id: "madhya_pradesh_breakfast_indori_poha_cooking_oil", name: "Cooking oil", quantity: 2, unit: "tbsp", category: "oil", searchTerms: { zepto: "refined cooking oil", instamart: "tel" } }
    ],
    steps: [
      "Rinse the poha in a colander under running water until softened; drain and set aside.",
      "Heat oil, splutter mustard seeds and curry leaves, then sauté onion, potato and green chili until soft.",
      "Add turmeric and a pinch of sugar, then fold in the softened poha; toss gently on low heat for 3-4 minutes.",
      "Season with salt, cover and steam for 2 minutes.",
      "Top with sev and a squeeze of lemon before serving hot."
    ],
    tags: ["quick", "tangy", "street-food", "light"],
  },
  {
    id: "madhya_pradesh_lunch_dal_bafla",
    name: "Dal Bafla",
    description: "Whole wheat dough balls boiled then roasted and soaked in ghee, served with spicy mixed-lentil dal — the Malwa region's hearty signature lunch.",
    cuisineRegion: ["Madhya Pradesh"],
    dietType: "veg",
    goalTags: ["maintenance", "weight_gain"],
    mealType: ["lunch"],
    prepTime: 30,
    cookTime: 45,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 620, proteinG: 18, carbsG: 78, fatG: 26 },
    ingredients: [
      { id: "madhya_pradesh_lunch_dal_bafla_whole_wheat_flour_atta", name: "Whole wheat flour (atta)", quantity: 250, unit: "g", category: "grain", searchTerms: { zepto: "whole wheat flour atta", instamart: "atta" } },
      { id: "madhya_pradesh_lunch_dal_bafla_semolina_sooji", name: "Semolina (sooji)", quantity: 30, unit: "g", category: "grain", searchTerms: { zepto: "semolina sooji", instamart: "sooji" }, optional: true },
      { id: "madhya_pradesh_lunch_dal_bafla_mixed_lentils_toor_chana_moong_urad_dal", name: "Mixed lentils (toor, chana, moong, urad dal)", quantity: 150, unit: "g", category: "protein", searchTerms: { zepto: "mixed dal panchmel", instamart: "mix dal" } },
      { id: "madhya_pradesh_lunch_dal_bafla_onion", name: "Onion", quantity: 80, unit: "g", category: "vegetable", searchTerms: { zepto: "onion", instamart: "pyaz" } },
      { id: "madhya_pradesh_lunch_dal_bafla_tomato", name: "Tomato", quantity: 100, unit: "g", category: "vegetable", searchTerms: { zepto: "tomato", instamart: "tamatar" } },
      { id: "madhya_pradesh_lunch_dal_bafla_ginger_garlic_paste", name: "Ginger-garlic paste", quantity: 10, unit: "g", category: "vegetable", searchTerms: { zepto: "ginger garlic paste", instamart: "adrak lehsun paste" } },
      { id: "madhya_pradesh_lunch_dal_bafla_turmeric_powder", name: "Turmeric powder", quantity: 0.5, unit: "tsp", category: "spice", searchTerms: { zepto: "turmeric powder haldi", instamart: "haldi" } },
      { id: "madhya_pradesh_lunch_dal_bafla_red_chili_powder", name: "Red chili powder", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "red chili powder", instamart: "lal mirch powder" } },
      { id: "madhya_pradesh_lunch_dal_bafla_ghee", name: "Ghee", quantity: 60, unit: "g", category: "oil", searchTerms: { zepto: "ghee", instamart: "desi ghee" } }
    ],
    steps: [
      "Knead a stiff dough with atta, sooji and a little ghee and water; shape into round baflas.",
      "Boil the baflas in water for 20 minutes until firm, then roast in an oven or over a tawa until golden and crusted.",
      "Pressure cook the mixed lentils with turmeric until soft, then mash lightly.",
      "Prepare a tempering with onion, tomato, ginger-garlic paste and red chili powder, then simmer the dal in it for 10 minutes.",
      "Crack open the hot baflas and soak generously in melted ghee.",
      "Serve the baflas with the hot dal and extra ghee on the side."
    ],
    tags: ["hearty", "traditional", "festive", "ghee-rich"],
  },
  {
    id: "madhya_pradesh_snack_bhutte_ka_kees",
    name: "Bhutte ka Kees",
    description: "Grated corn slow-cooked with milk, mustard seeds and green chillies into a creamy, savory Indori snack finished with a squeeze of lime.",
    cuisineRegion: ["Madhya Pradesh"],
    dietType: "veg",
    goalTags: ["maintenance", "weight_loss"],
    mealType: ["snack"],
    prepTime: 15,
    cookTime: 20,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 260, proteinG: 6, carbsG: 34, fatG: 11 },
    ingredients: [
      { id: "madhya_pradesh_snack_bhutte_ka_kees_sweet_corn_on_cob", name: "Sweet corn (on cob)", quantity: 3, unit: "medium", category: "vegetable", searchTerms: { zepto: "sweet corn cob", instamart: "bhutta" } },
      { id: "madhya_pradesh_snack_bhutte_ka_kees_milk", name: "Milk", quantity: 100, unit: "ml", category: "dairy", searchTerms: { zepto: "toned milk", instamart: "doodh" } },
      { id: "madhya_pradesh_snack_bhutte_ka_kees_green_chili", name: "Green chili", quantity: 2, unit: "piece", category: "vegetable", searchTerms: { zepto: "green chili", instamart: "hari mirch" }, optional: true },
      { id: "madhya_pradesh_snack_bhutte_ka_kees_ginger", name: "Ginger", quantity: 10, unit: "g", category: "vegetable", searchTerms: { zepto: "fresh ginger", instamart: "adrak" }, optional: true },
      { id: "madhya_pradesh_snack_bhutte_ka_kees_mustard_seeds", name: "Mustard seeds", quantity: 0.5, unit: "tsp", category: "spice", searchTerms: { zepto: "mustard seeds rai", instamart: "rai" }, optional: true },
      { id: "madhya_pradesh_snack_bhutte_ka_kees_cumin_seeds", name: "Cumin seeds", quantity: 0.5, unit: "tsp", category: "spice", searchTerms: { zepto: "cumin seeds jeera", instamart: "jeera" }, optional: true },
      { id: "madhya_pradesh_snack_bhutte_ka_kees_turmeric_powder", name: "Turmeric powder", quantity: 0.25, unit: "tsp", category: "spice", searchTerms: { zepto: "turmeric powder haldi", instamart: "haldi" } },
      { id: "madhya_pradesh_snack_bhutte_ka_kees_butter", name: "Butter", quantity: 2, unit: "tbsp", category: "oil", searchTerms: { zepto: "butter", instamart: "makhan" } },
      { id: "madhya_pradesh_snack_bhutte_ka_kees_lemon", name: "Lemon", quantity: 1, unit: "piece", category: "fruit", searchTerms: { zepto: "lemon", instamart: "nimbu" }, optional: true }
    ],
    steps: [
      "Grate the corn kernels off the cob coarsely using a box grater.",
      "Heat butter, splutter mustard and cumin seeds, then sauté ginger and green chili.",
      "Add the grated corn, turmeric and milk; cook on low heat, stirring frequently, until thick and creamy, about 12-15 minutes.",
      "Season with salt and a pinch of sugar if desired.",
      "Garnish with coriander and a squeeze of lemon, and serve hot."
    ],
    tags: ["corn", "quick", "indori", "snack"],
  },
  {
    id: "madhya_pradesh_dinner_bhopali_gosht_korma",
    name: "Bhopali Gosht Korma",
    description: "A slow-cooked mutton curry simmered in a fragrant onion-yogurt gravy, reflecting Bhopal's Nawabi culinary heritage — a special-occasion dinner dish.",
    cuisineRegion: ["Madhya Pradesh"],
    dietType: "nonveg",
    goalTags: ["maintenance", "muscle", "recovery", "weight_gain"],
    mealType: ["dinner"],
    prepTime: 25,
    cookTime: 50,
    servings: 2,
    difficulty: "hard",
    nutrition: { calories: 520, proteinG: 34, carbsG: 10, fatG: 36 },
    ingredients: [
      { id: "madhya_pradesh_dinner_bhopali_gosht_korma_mutton_curry_cut_bone_in", name: "Mutton (curry cut, bone-in)", quantity: 500, unit: "g", category: "protein", searchTerms: { zepto: "mutton curry cut", instamart: "mutton" } },
      { id: "madhya_pradesh_dinner_bhopali_gosht_korma_curd_yogurt", name: "Curd (yogurt)", quantity: 150, unit: "g", category: "dairy", searchTerms: { zepto: "fresh curd", instamart: "dahi" } },
      { id: "madhya_pradesh_dinner_bhopali_gosht_korma_onion", name: "Onion", quantity: 200, unit: "g", category: "vegetable", searchTerms: { zepto: "onion", instamart: "pyaz" } },
      { id: "madhya_pradesh_dinner_bhopali_gosht_korma_ginger_garlic_paste", name: "Ginger-garlic paste", quantity: 20, unit: "g", category: "vegetable", searchTerms: { zepto: "ginger garlic paste", instamart: "adrak lehsun paste" } },
      { id: "madhya_pradesh_dinner_bhopali_gosht_korma_whole_garam_masala_bay_leaf_cinnamon_cloves_card", name: "Whole garam masala (bay leaf, cinnamon, cloves, cardamom)", quantity: 1, unit: "tbsp", category: "spice", searchTerms: { zepto: "whole garam masala", instamart: "sabut garam masala" }, optional: true },
      { id: "madhya_pradesh_dinner_bhopali_gosht_korma_red_chili_powder", name: "Red chili powder", quantity: 1.5, unit: "tsp", category: "spice", searchTerms: { zepto: "red chili powder", instamart: "lal mirch powder" } },
      { id: "madhya_pradesh_dinner_bhopali_gosht_korma_coriander_powder", name: "Coriander powder", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "coriander powder dhania", instamart: "dhania powder" } },
      { id: "madhya_pradesh_dinner_bhopali_gosht_korma_ghee", name: "Ghee", quantity: 3, unit: "tbsp", category: "oil", searchTerms: { zepto: "ghee", instamart: "desi ghee" } }
    ],
    steps: [
      "Fry sliced onions until deep golden and crisp; reserve some for garnish and grind the rest into a paste.",
      "Marinate the mutton with curd, ginger-garlic paste and turmeric for 30 minutes.",
      "Heat ghee, temper the whole garam masala, add the marinated mutton and sear until the color changes.",
      "Stir in the onion paste, red chili and coriander powder; cover and cook on low flame, adding water as needed, until the mutton is fall-off-the-bone tender, about 35-40 minutes.",
      "Adjust seasoning and garnish with the reserved fried onions.",
      "Serve hot with sheermal, naan or steamed rice."
    ],
    tags: ["rich", "festive", "nawabi", "slow-cooked"],
  },
  {
    id: "chhattisgarh_breakfast_chila",
    name: "Chila",
    description: "A savory pancake made from a fermented rice-urad dal batter, pan-cooked and served with tomato or garlic chutney — a staple Chhattisgarhi breakfast.",
    cuisineRegion: ["Chhattisgarh"],
    dietType: "veg",
    goalTags: ["maintenance"],
    mealType: ["breakfast"],
    prepTime: 20,
    cookTime: 20,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 300, proteinG: 9, carbsG: 48, fatG: 8 },
    ingredients: [
      { id: "chhattisgarh_breakfast_chila_rice", name: "Rice", quantity: 150, unit: "g", category: "grain", searchTerms: { zepto: "rice", instamart: "chawal" } },
      { id: "chhattisgarh_breakfast_chila_urad_dal_split", name: "Urad dal (split)", quantity: 50, unit: "g", category: "protein", searchTerms: { zepto: "urad dal split", instamart: "urad dal dhuli" } },
      { id: "chhattisgarh_breakfast_chila_onion", name: "Onion", quantity: 50, unit: "g", category: "vegetable", searchTerms: { zepto: "onion", instamart: "pyaz" }, optional: true },
      { id: "chhattisgarh_breakfast_chila_green_chili", name: "Green chili", quantity: 1, unit: "piece", category: "vegetable", searchTerms: { zepto: "green chili", instamart: "hari mirch" }, optional: true },
      { id: "chhattisgarh_breakfast_chila_ginger", name: "Ginger", quantity: 10, unit: "g", category: "vegetable", searchTerms: { zepto: "fresh ginger", instamart: "adrak" }, optional: true },
      { id: "chhattisgarh_breakfast_chila_cumin_seeds", name: "Cumin seeds", quantity: 0.5, unit: "tsp", category: "spice", searchTerms: { zepto: "cumin seeds jeera", instamart: "jeera" }, optional: true },
      { id: "chhattisgarh_breakfast_chila_cooking_oil", name: "Cooking oil", quantity: 2, unit: "tbsp", category: "oil", searchTerms: { zepto: "refined cooking oil", instamart: "tel" } }
    ],
    steps: [
      "Soak the rice and urad dal together for 4-5 hours, then grind to a smooth, medium-thick batter; ferment for a few hours if time allows.",
      "Mix in finely chopped onion, green chili, ginger, cumin seeds and salt.",
      "Heat a griddle, pour a ladle of batter and spread into a thin round pancake.",
      "Drizzle a little oil around the edges and cook until golden and crisp on both sides.",
      "Serve hot with tomato or garlic chutney."
    ],
    tags: ["fermented", "quick", "homestyle", "breakfast"],
  },
  {
    id: "chhattisgarh_lunch_bafauri",
    name: "Bafauri",
    description: "Steamed chana dal and cabbage dumplings simmered in a lightly spiced tomato curry, served with rice for a wholesome Chhattisgarhi lunch.",
    cuisineRegion: ["Chhattisgarh"],
    dietType: "veg",
    goalTags: ["maintenance"],
    mealType: ["lunch"],
    prepTime: 25,
    cookTime: 30,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 380, proteinG: 16, carbsG: 52, fatG: 10 },
    ingredients: [
      { id: "chhattisgarh_lunch_bafauri_chana_dal_split", name: "Chana dal (split)", quantity: 200, unit: "g", category: "protein", searchTerms: { zepto: "chana dal split", instamart: "chana dal" } },
      { id: "chhattisgarh_lunch_bafauri_cabbage_shredded", name: "Cabbage (shredded)", quantity: 100, unit: "g", category: "vegetable", searchTerms: { zepto: "cabbage", instamart: "patta gobi" }, optional: true },
      { id: "chhattisgarh_lunch_bafauri_ginger", name: "Ginger", quantity: 10, unit: "g", category: "vegetable", searchTerms: { zepto: "fresh ginger", instamart: "adrak" }, optional: true },
      { id: "chhattisgarh_lunch_bafauri_green_chili", name: "Green chili", quantity: 2, unit: "piece", category: "vegetable", searchTerms: { zepto: "green chili", instamart: "hari mirch" }, optional: true },
      { id: "chhattisgarh_lunch_bafauri_mustard_seeds", name: "Mustard seeds", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "mustard seeds rai", instamart: "rai" }, optional: true },
      { id: "chhattisgarh_lunch_bafauri_turmeric_powder", name: "Turmeric powder", quantity: 0.5, unit: "tsp", category: "spice", searchTerms: { zepto: "turmeric powder haldi", instamart: "haldi" } },
      { id: "chhattisgarh_lunch_bafauri_tomato", name: "Tomato", quantity: 100, unit: "g", category: "vegetable", searchTerms: { zepto: "tomato", instamart: "tamatar" } },
      { id: "chhattisgarh_lunch_bafauri_onion", name: "Onion", quantity: 80, unit: "g", category: "vegetable", searchTerms: { zepto: "onion", instamart: "pyaz" } },
      { id: "chhattisgarh_lunch_bafauri_cooking_oil", name: "Cooking oil", quantity: 2, unit: "tbsp", category: "oil", searchTerms: { zepto: "refined cooking oil", instamart: "tel" } }
    ],
    steps: [
      "Soak the chana dal for 3-4 hours, then grind coarsely along with ginger and green chili.",
      "Mix in the shredded cabbage and salt, shape into small dumplings, and steam for 15-20 minutes until firm.",
      "Heat oil, temper mustard seeds, then sauté onion and tomato with turmeric until softened.",
      "Add water to form a light gravy, bring to a boil, then gently add the steamed bafauri and simmer for 5 minutes.",
      "Garnish with coriander and serve hot with steamed rice."
    ],
    tags: ["steamed", "protein-rich", "traditional", "homestyle"],
  },
  {
    id: "chhattisgarh_snack_faraa",
    name: "Faraa",
    description: "Steamed rice flour dumplings tempered with mustard seeds and curry leaves, a light and popular Chhattisgarhi tea-time snack.",
    cuisineRegion: ["Chhattisgarh"],
    dietType: "veg",
    goalTags: ["maintenance", "weight_loss"],
    mealType: ["snack"],
    prepTime: 15,
    cookTime: 20,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 240, proteinG: 5, carbsG: 46, fatG: 5 },
    ingredients: [
      { id: "chhattisgarh_snack_faraa_rice_flour", name: "Rice flour", quantity: 200, unit: "g", category: "grain", searchTerms: { zepto: "rice flour", instamart: "chawal ka atta" } },
      { id: "chhattisgarh_snack_faraa_green_chili", name: "Green chili", quantity: 1, unit: "piece", category: "vegetable", searchTerms: { zepto: "green chili", instamart: "hari mirch" }, optional: true },
      { id: "chhattisgarh_snack_faraa_ginger", name: "Ginger", quantity: 10, unit: "g", category: "vegetable", searchTerms: { zepto: "fresh ginger", instamart: "adrak" }, optional: true },
      { id: "chhattisgarh_snack_faraa_mustard_seeds", name: "Mustard seeds", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "mustard seeds rai", instamart: "rai" }, optional: true },
      { id: "chhattisgarh_snack_faraa_curry_leaves", name: "Curry leaves", quantity: 8, unit: "piece", category: "spice", searchTerms: { zepto: "curry leaves", instamart: "kadi patta" }, optional: true },
      { id: "chhattisgarh_snack_faraa_asafoetida", name: "Asafoetida", quantity: 1, unit: "piece", category: "spice", searchTerms: { zepto: "asafoetida hing", instamart: "hing" }, optional: true },
      { id: "chhattisgarh_snack_faraa_cooking_oil", name: "Cooking oil", quantity: 2, unit: "tbsp", category: "oil", searchTerms: { zepto: "refined cooking oil", instamart: "tel" } }
    ],
    steps: [
      "Bring water to a boil with salt, chopped ginger and green chili, then stir in the rice flour to form a smooth, lump-free dough.",
      "Shape the dough into small cylindrical rolls and steam for 12-15 minutes.",
      "Once cooled slightly, slice the steamed rolls into bite-sized pieces.",
      "Heat oil, temper mustard seeds, curry leaves and asafoetida.",
      "Toss the sliced faraa in the tempering and garnish with coriander before serving."
    ],
    tags: ["steamed", "light", "tea-time", "quick"],
  },
  {
    id: "chhattisgarh_dinner_bastar_style_vegetable_aamat",
    name: "Bastar-style Vegetable Aamat",
    description: "A tangy, lightly spiced mixed vegetable curry from the Bastar region of Chhattisgarh, traditionally cooked in mustard oil and served with rice for dinner.",
    cuisineRegion: ["Chhattisgarh"],
    dietType: "veg",
    goalTags: ["maintenance", "weight_loss"],
    mealType: ["dinner"],
    prepTime: 15,
    cookTime: 25,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 260, proteinG: 7, carbsG: 38, fatG: 8 },
    ingredients: [
      { id: "chhattisgarh_dinner_bastar_style_vegetable_aamat_mixed_vegetables_pumpkin_drumstick_beans", name: "Mixed vegetables (pumpkin, drumstick, beans)", quantity: 300, unit: "g", category: "vegetable", searchTerms: { zepto: "mixed vegetables", instamart: "mix sabzi" } },
      { id: "chhattisgarh_dinner_bastar_style_vegetable_aamat_tomato", name: "Tomato", quantity: 100, unit: "g", category: "vegetable", searchTerms: { zepto: "tomato", instamart: "tamatar" } },
      { id: "chhattisgarh_dinner_bastar_style_vegetable_aamat_garlic", name: "Garlic", quantity: 10, unit: "g", category: "vegetable", searchTerms: { zepto: "fresh garlic", instamart: "lehsun" }, optional: true },
      { id: "chhattisgarh_dinner_bastar_style_vegetable_aamat_green_chili", name: "Green chili", quantity: 2, unit: "piece", category: "vegetable", searchTerms: { zepto: "green chili", instamart: "hari mirch" }, optional: true },
      { id: "chhattisgarh_dinner_bastar_style_vegetable_aamat_mustard_seeds", name: "Mustard seeds", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "mustard seeds rai", instamart: "rai" }, optional: true },
      { id: "chhattisgarh_dinner_bastar_style_vegetable_aamat_turmeric_powder", name: "Turmeric powder", quantity: 0.5, unit: "tsp", category: "spice", searchTerms: { zepto: "turmeric powder haldi", instamart: "haldi" } },
      { id: "chhattisgarh_dinner_bastar_style_vegetable_aamat_tamarind_pulp", name: "Tamarind pulp", quantity: 20, unit: "g", category: "other", searchTerms: { zepto: "tamarind pulp imli", instamart: "imli" }, optional: true },
      { id: "chhattisgarh_dinner_bastar_style_vegetable_aamat_mustard_oil", name: "Mustard oil", quantity: 2, unit: "tbsp", category: "oil", searchTerms: { zepto: "mustard oil", instamart: "sarson ka tel" } }
    ],
    steps: [
      "Chop the mixed vegetables into bite-sized pieces.",
      "Heat mustard oil, temper mustard seeds, then add crushed garlic and green chili.",
      "Add chopped tomato and turmeric, cook until softened, then add the mixed vegetables along with a little water.",
      "Cover and simmer until the vegetables are tender, then stir in the tamarind pulp for tang.",
      "Adjust salt and consistency, and garnish with coriander.",
      "Serve hot with steamed rice."
    ],
    tags: ["tribal", "light", "tangy", "rice-pairing"],
  },
];
