import type { Recipe } from "../types";

// Auto-generated from regional recipe research (East zone).
export const EAST_RECIPES: Recipe[] = [
  {
    id: "west_bengal_breakfast_luchi_aloor_dom",
    name: "Luchi Aloor Dom",
    description: "Fluffy deep-fried maida bread served with a fragrant, lightly spiced potato curry, a beloved Bengali breakfast and festive-morning staple.",
    cuisineRegion: ["West Bengal"],
    dietType: "veg",
    goalTags: ["maintenance"],
    mealType: ["breakfast"],
    prepTime: 20,
    cookTime: 25,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 420, proteinG: 8, carbsG: 58, fatG: 18 },
    ingredients: [
      { id: "west_bengal_breakfast_luchi_aloor_dom_refined_flour_maida", name: "Refined flour (maida)", quantity: 200, unit: "g", category: "grain", searchTerms: { zepto: "refined flour maida", instamart: "maida" } },
      { id: "west_bengal_breakfast_luchi_aloor_dom_potatoes", name: "Potatoes", quantity: 300, unit: "g", category: "vegetable", searchTerms: { zepto: "potato", instamart: "aloo" } },
      { id: "west_bengal_breakfast_luchi_aloor_dom_ghee", name: "Ghee", quantity: 2, unit: "tbsp", category: "dairy", searchTerms: { zepto: "ghee", instamart: "desi ghee" } },
      { id: "west_bengal_breakfast_luchi_aloor_dom_cumin_seeds", name: "Cumin seeds", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "cumin seeds jeera", instamart: "jeera" }, optional: true },
      { id: "west_bengal_breakfast_luchi_aloor_dom_turmeric_powder", name: "Turmeric powder", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "turmeric powder", instamart: "haldi" } },
      { id: "west_bengal_breakfast_luchi_aloor_dom_ginger_paste", name: "Ginger paste", quantity: 1, unit: "tbsp", category: "spice", searchTerms: { zepto: "ginger paste", instamart: "adrak paste" } },
      { id: "west_bengal_breakfast_luchi_aloor_dom_tomato", name: "Tomato", quantity: 2, unit: "medium", category: "vegetable", searchTerms: { zepto: "tomato", instamart: "tamatar" } },
      { id: "west_bengal_breakfast_luchi_aloor_dom_green_chilli", name: "Green chilli", quantity: 2, unit: "piece", category: "vegetable", searchTerms: { zepto: "green chilli", instamart: "hari mirch" }, optional: true },
      { id: "west_bengal_breakfast_luchi_aloor_dom_sunflower_refined_oil_for_frying", name: "Sunflower/refined oil (for frying)", quantity: 250, unit: "ml", category: "oil", searchTerms: { zepto: "sunflower oil", instamart: "refined tel" } },
      { id: "west_bengal_breakfast_luchi_aloor_dom_garam_masala", name: "Garam masala", quantity: 0.5, unit: "tsp", category: "spice", searchTerms: { zepto: "garam masala powder", instamart: "garam masala" }, optional: true }
    ],
    steps: [
      "Knead maida with a little salt, ghee and water into a stiff dough; rest 20 minutes.",
      "Boil, peel and roughly mash the potatoes; set aside.",
      "Heat oil in a kadai, temper with cumin, add ginger paste, tomatoes and turmeric, and cook till soft.",
      "Add potatoes, salt, green chilli and a splash of water; simmer 8-10 minutes and finish with garam masala.",
      "Roll the dough into small discs and deep fry in hot oil until puffed and golden.",
      "Serve the hot luchi immediately with the aloor dom."
    ],
    tags: ["fried", "festive", "comfort food", "vegetarian"],
  },
  {
    id: "west_bengal_lunch_machher_jhol_bengali_fish_curry_with_rice",
    name: "Machher Jhol (Bengali Fish Curry) with Rice",
    description: "A light, turmeric-forward everyday Bengali fish curry with potatoes, simmered in mustard oil and served over steamed rice.",
    cuisineRegion: ["West Bengal"],
    dietType: "nonveg",
    goalTags: ["maintenance", "muscle", "recovery"],
    mealType: ["lunch"],
    prepTime: 15,
    cookTime: 25,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 480, proteinG: 32, carbsG: 55, fatG: 14 },
    ingredients: [
      { id: "west_bengal_lunch_machher_jhol_bengali_fish_curry_with_rice_rohu_fish_fresh_curry_cut", name: "Rohu fish (fresh, curry cut)", quantity: 4, unit: "piece", category: "protein", searchTerms: { zepto: "rohu fish fresh", instamart: "rohu machli" } },
      { id: "west_bengal_lunch_machher_jhol_bengali_fish_curry_with_rice_rice", name: "Rice", quantity: 300, unit: "g", category: "grain", searchTerms: { zepto: "rice", instamart: "chawal" } },
      { id: "west_bengal_lunch_machher_jhol_bengali_fish_curry_with_rice_potato", name: "Potato", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "potato", instamart: "aloo" } },
      { id: "west_bengal_lunch_machher_jhol_bengali_fish_curry_with_rice_mustard_oil", name: "Mustard oil", quantity: 3, unit: "tbsp", category: "oil", searchTerms: { zepto: "mustard oil", instamart: "sarson ka tel" } },
      { id: "west_bengal_lunch_machher_jhol_bengali_fish_curry_with_rice_turmeric_powder", name: "Turmeric powder", quantity: 1.5, unit: "tsp", category: "spice", searchTerms: { zepto: "turmeric powder", instamart: "haldi" } },
      { id: "west_bengal_lunch_machher_jhol_bengali_fish_curry_with_rice_nigella_seeds_kalonji", name: "Nigella seeds (kalonji)", quantity: 0.5, unit: "tsp", category: "spice", searchTerms: { zepto: "kalonji nigella seeds", instamart: "kalonji" }, optional: true },
      { id: "west_bengal_lunch_machher_jhol_bengali_fish_curry_with_rice_green_chilli", name: "Green chilli", quantity: 3, unit: "piece", category: "vegetable", searchTerms: { zepto: "green chilli", instamart: "hari mirch" }, optional: true },
      { id: "west_bengal_lunch_machher_jhol_bengali_fish_curry_with_rice_cumin_coriander_powder", name: "Cumin-coriander powder", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "cumin coriander powder", instamart: "dhania jeera powder" } },
      { id: "west_bengal_lunch_machher_jhol_bengali_fish_curry_with_rice_tomato", name: "Tomato", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "tomato", instamart: "tamatar" }, optional: true }
    ],
    steps: [
      "Rub the fish pieces with salt and turmeric; shallow fry in mustard oil until lightly golden, then remove.",
      "In the same oil, temper nigella seeds, add potato wedges and fry briefly.",
      "Add turmeric, cumin-coriander powder, tomato and green chilli; cook till the oil separates.",
      "Add water, bring to a boil and simmer the potatoes until half done.",
      "Slide in the fried fish, cover and simmer 8-10 minutes until cooked through.",
      "Serve hot with steamed rice."
    ],
    tags: ["fish", "everyday", "mustard oil", "comfort food"],
  },
  {
    id: "west_bengal_snack_jhal_muri",
    name: "Jhal Muri",
    description: "A spicy, tangy puffed-rice street snack tossed with mustard oil, peanuts, chopped vegetables and chaat masala.",
    cuisineRegion: ["West Bengal"],
    dietType: "veg",
    goalTags: ["maintenance", "weight_loss"],
    mealType: ["snack"],
    prepTime: 10,
    cookTime: 0,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 180, proteinG: 5, carbsG: 28, fatG: 6 },
    ingredients: [
      { id: "west_bengal_snack_jhal_muri_puffed_rice_muri", name: "Puffed rice (muri)", quantity: 150, unit: "g", category: "grain", searchTerms: { zepto: "puffed rice murmura", instamart: "muri" } },
      { id: "west_bengal_snack_jhal_muri_roasted_peanuts", name: "Roasted peanuts", quantity: 40, unit: "g", category: "protein", searchTerms: { zepto: "roasted peanuts", instamart: "moongfali" } },
      { id: "west_bengal_snack_jhal_muri_onion", name: "Onion", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "pyaz" } },
      { id: "west_bengal_snack_jhal_muri_tomato", name: "Tomato", quantity: 1, unit: "small", category: "vegetable", searchTerms: { zepto: "tomato", instamart: "tamatar" } },
      { id: "west_bengal_snack_jhal_muri_cucumber", name: "Cucumber", quantity: 1, unit: "small", category: "vegetable", searchTerms: { zepto: "cucumber", instamart: "kheera" }, optional: true },
      { id: "west_bengal_snack_jhal_muri_green_chilli", name: "Green chilli", quantity: 2, unit: "piece", category: "vegetable", searchTerms: { zepto: "green chilli", instamart: "hari mirch" }, optional: true },
      { id: "west_bengal_snack_jhal_muri_mustard_oil", name: "Mustard oil", quantity: 1, unit: "tbsp", category: "oil", searchTerms: { zepto: "mustard oil", instamart: "sarson ka tel" } },
      { id: "west_bengal_snack_jhal_muri_chaat_masala", name: "Chaat masala", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "chaat masala", instamart: "chaat masala" } },
      { id: "west_bengal_snack_jhal_muri_lemon", name: "Lemon", quantity: 1, unit: "piece", category: "fruit", searchTerms: { zepto: "lemon", instamart: "nimbu" }, optional: true }
    ],
    steps: [
      "Finely chop the onion, tomato, cucumber and green chilli.",
      "In a large bowl, combine puffed rice, peanuts and the chopped vegetables.",
      "Drizzle mustard oil, sprinkle chaat masala and salt, and squeeze in lemon juice.",
      "Toss everything well until evenly coated and serve immediately while crisp."
    ],
    tags: ["quick", "street food", "spicy", "no-cook"],
  },
  {
    id: "west_bengal_dinner_kosha_mangsho_with_rice",
    name: "Kosha Mangsho with Rice",
    description: "A rich, slow-cooked Bengali mutton curry deeply browned with onions and whole spices, traditionally served with rice or luchi.",
    cuisineRegion: ["West Bengal"],
    dietType: "nonveg",
    goalTags: ["maintenance", "muscle", "recovery", "weight_gain"],
    mealType: ["dinner"],
    prepTime: 20,
    cookTime: 50,
    servings: 2,
    difficulty: "hard",
    nutrition: { calories: 520, proteinG: 34, carbsG: 20, fatG: 32 },
    ingredients: [
      { id: "west_bengal_dinner_kosha_mangsho_with_rice_mutton_goat_curry_cut", name: "Mutton (goat, curry cut)", quantity: 500, unit: "g", category: "protein", searchTerms: { zepto: "mutton curry cut", instamart: "mutton" } },
      { id: "west_bengal_dinner_kosha_mangsho_with_rice_onion", name: "Onion", quantity: 4, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "pyaz" } },
      { id: "west_bengal_dinner_kosha_mangsho_with_rice_ginger_garlic_paste", name: "Ginger-garlic paste", quantity: 2, unit: "tbsp", category: "spice", searchTerms: { zepto: "ginger garlic paste", instamart: "adrak lahsun paste" } },
      { id: "west_bengal_dinner_kosha_mangsho_with_rice_curd_yogurt", name: "Curd (yogurt)", quantity: 100, unit: "g", category: "dairy", searchTerms: { zepto: "curd yogurt", instamart: "dahi" } },
      { id: "west_bengal_dinner_kosha_mangsho_with_rice_mustard_oil", name: "Mustard oil", quantity: 4, unit: "tbsp", category: "oil", searchTerms: { zepto: "mustard oil", instamart: "sarson ka tel" } },
      { id: "west_bengal_dinner_kosha_mangsho_with_rice_bay_leaf", name: "Bay leaf", quantity: 2, unit: "piece", category: "spice", searchTerms: { zepto: "bay leaf tej patta", instamart: "tej patta" }, optional: true },
      { id: "west_bengal_dinner_kosha_mangsho_with_rice_whole_garam_masala_cinnamon_cardamom_cloves", name: "Whole garam masala (cinnamon, cardamom, cloves)", quantity: 1, unit: "tbsp", category: "spice", searchTerms: { zepto: "whole garam masala", instamart: "sabut garam masala" }, optional: true },
      { id: "west_bengal_dinner_kosha_mangsho_with_rice_red_chilli_powder", name: "Red chilli powder", quantity: 1.5, unit: "tsp", category: "spice", searchTerms: { zepto: "red chilli powder", instamart: "lal mirch powder" } },
      { id: "west_bengal_dinner_kosha_mangsho_with_rice_sugar", name: "Sugar", quantity: 1, unit: "tsp", category: "other", searchTerms: { zepto: "sugar", instamart: "cheeni" }, optional: true },
      { id: "west_bengal_dinner_kosha_mangsho_with_rice_potato", name: "Potato", quantity: 2, unit: "medium", category: "vegetable", searchTerms: { zepto: "potato", instamart: "aloo" }, optional: true }
    ],
    steps: [
      "Marinate the mutton with curd, ginger-garlic paste, turmeric and salt for at least 1 hour.",
      "Heat mustard oil and caramelize sliced onions with whole garam masala and bay leaf until deep brown.",
      "Add the marinated mutton and sear on high heat, stirring often, until well browned (the \"kosha\" stage).",
      "Add red chilli powder and a little sugar, cover and cook on low heat, adding splashes of water, until the mutton is tender (40-45 minutes).",
      "Add potatoes midway if using, and continue cooking until the gravy is thick and oil separates.",
      "Serve hot with steamed rice or luchi."
    ],
    tags: ["mutton", "slow-cooked", "festive", "rich"],
  },
  {
    id: "odisha_breakfast_chakuli_pitha",
    name: "Chakuli Pitha",
    description: "Soft, savoury fermented rice-and-urad-dal crepes, a staple Odia breakfast usually paired with tomato chutney or dalma.",
    cuisineRegion: ["Odisha"],
    dietType: "veg",
    goalTags: ["maintenance"],
    mealType: ["breakfast"],
    prepTime: 15,
    cookTime: 20,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 300, proteinG: 9, carbsG: 48, fatG: 8 },
    ingredients: [
      { id: "odisha_breakfast_chakuli_pitha_raw_rice", name: "Raw rice", quantity: 200, unit: "g", category: "grain", searchTerms: { zepto: "raw rice", instamart: "chawal" } },
      { id: "odisha_breakfast_chakuli_pitha_urad_dal_split_black_gram", name: "Urad dal (split black gram)", quantity: 60, unit: "g", category: "protein", searchTerms: { zepto: "urad dal", instamart: "urad dal" } },
      { id: "odisha_breakfast_chakuli_pitha_cooked_rice_leftover", name: "Cooked rice (leftover)", quantity: 50, unit: "g", category: "grain", searchTerms: { zepto: "rice", instamart: "chawal" }, optional: true },
      { id: "odisha_breakfast_chakuli_pitha_cumin_seeds", name: "Cumin seeds", quantity: 0.5, unit: "tsp", category: "spice", searchTerms: { zepto: "cumin seeds jeera", instamart: "jeera" }, optional: true },
      { id: "odisha_breakfast_chakuli_pitha_onion", name: "Onion", quantity: 1, unit: "small", category: "vegetable", searchTerms: { zepto: "onion", instamart: "pyaz" }, optional: true },
      { id: "odisha_breakfast_chakuli_pitha_green_chilli", name: "Green chilli", quantity: 1, unit: "piece", category: "vegetable", searchTerms: { zepto: "green chilli", instamart: "hari mirch" }, optional: true },
      { id: "odisha_breakfast_chakuli_pitha_sunflower_refined_oil", name: "Sunflower/refined oil", quantity: 3, unit: "tbsp", category: "oil", searchTerms: { zepto: "sunflower oil", instamart: "refined tel" } },
      { id: "odisha_breakfast_chakuli_pitha_tomato_for_chutney", name: "Tomato (for chutney)", quantity: 2, unit: "medium", category: "vegetable", searchTerms: { zepto: "tomato", instamart: "tamatar" }, optional: true }
    ],
    steps: [
      "Soak rice and urad dal separately for 4-5 hours, then grind together with the cooked rice into a smooth, slightly thin batter; ferment overnight.",
      "Mix in salt, cumin seeds, chopped onion and green chilli.",
      "Heat a griddle, pour a ladle of batter and spread thin like a crepe.",
      "Drizzle a little oil around the edges and cook until crisp and golden on the base; no need to flip.",
      "Serve hot with tomato chutney or a bowl of dalma."
    ],
    tags: ["fermented", "breakfast staple", "gluten-free"],
  },
  {
    id: "odisha_lunch_dalma_with_rice",
    name: "Dalma with Rice",
    description: "A wholesome Odia lentil-and-vegetable stew tempered with panch phutana, served over steamed rice as the quintessential daily lunch.",
    cuisineRegion: ["Odisha"],
    dietType: "veg",
    goalTags: ["maintenance"],
    mealType: ["lunch"],
    prepTime: 15,
    cookTime: 30,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 380, proteinG: 16, carbsG: 60, fatG: 8 },
    ingredients: [
      { id: "odisha_lunch_dalma_with_rice_toor_dal_split_pigeon_pea", name: "Toor dal (split pigeon pea)", quantity: 150, unit: "g", category: "protein", searchTerms: { zepto: "toor dal arhar dal", instamart: "arhar dal" } },
      { id: "odisha_lunch_dalma_with_rice_raw_banana", name: "Raw banana", quantity: 1, unit: "piece", category: "vegetable", searchTerms: { zepto: "raw banana", instamart: "kaccha kela" }, optional: true },
      { id: "odisha_lunch_dalma_with_rice_pumpkin", name: "Pumpkin", quantity: 150, unit: "g", category: "vegetable", searchTerms: { zepto: "pumpkin", instamart: "kaddu" }, optional: true },
      { id: "odisha_lunch_dalma_with_rice_brinjal", name: "Brinjal", quantity: 1, unit: "small", category: "vegetable", searchTerms: { zepto: "brinjal eggplant", instamart: "baingan" }, optional: true },
      { id: "odisha_lunch_dalma_with_rice_panch_phutana_five_spice_mix", name: "Panch phutana (five-spice mix)", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "panch phoron", instamart: "panch phoron" }, optional: true },
      { id: "odisha_lunch_dalma_with_rice_turmeric_powder", name: "Turmeric powder", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "turmeric powder", instamart: "haldi" } },
      { id: "odisha_lunch_dalma_with_rice_ghee", name: "Ghee", quantity: 1, unit: "tbsp", category: "dairy", searchTerms: { zepto: "ghee", instamart: "desi ghee" } },
      { id: "odisha_lunch_dalma_with_rice_dry_red_chilli", name: "Dry red chilli", quantity: 2, unit: "piece", category: "spice", searchTerms: { zepto: "dry red chilli", instamart: "sukhi lal mirch" }, optional: true },
      { id: "odisha_lunch_dalma_with_rice_rice_for_serving", name: "Rice (for serving)", quantity: 300, unit: "g", category: "grain", searchTerms: { zepto: "rice", instamart: "chawal" } }
    ],
    steps: [
      "Pressure cook toor dal with turmeric, chopped raw banana, pumpkin and brinjal until soft.",
      "Mash lightly and adjust the consistency with water; add salt and simmer 5 minutes.",
      "Heat ghee in a small pan and temper panch phutana and dry red chillies until fragrant.",
      "Pour the tempering over the dalma and mix well.",
      "Serve hot with steamed rice."
    ],
    tags: ["everyday", "lentils", "wholesome", "one-pot"],
  },
  {
    id: "odisha_snack_ghuguni",
    name: "Ghuguni",
    description: "A tangy, spiced curry of dried yellow peas simmered and finished with tamarind, onion and sev — a favourite Odia evening street snack.",
    cuisineRegion: ["Odisha"],
    dietType: "veg",
    goalTags: ["maintenance", "weight_loss"],
    mealType: ["snack"],
    prepTime: 15,
    cookTime: 25,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 220, proteinG: 11, carbsG: 34, fatG: 5 },
    ingredients: [
      { id: "odisha_snack_ghuguni_dried_yellow_peas", name: "Dried yellow peas", quantity: 200, unit: "g", category: "protein", searchTerms: { zepto: "dried yellow peas", instamart: "safed matar" } },
      { id: "odisha_snack_ghuguni_onion", name: "Onion", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "pyaz" } },
      { id: "odisha_snack_ghuguni_tomato", name: "Tomato", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "tomato", instamart: "tamatar" }, optional: true },
      { id: "odisha_snack_ghuguni_ginger_garlic_paste", name: "Ginger-garlic paste", quantity: 1, unit: "tbsp", category: "spice", searchTerms: { zepto: "ginger garlic paste", instamart: "adrak lahsun paste" } },
      { id: "odisha_snack_ghuguni_turmeric_powder", name: "Turmeric powder", quantity: 0.5, unit: "tsp", category: "spice", searchTerms: { zepto: "turmeric powder", instamart: "haldi" } },
      { id: "odisha_snack_ghuguni_tamarind_pulp", name: "Tamarind pulp", quantity: 1, unit: "tbsp", category: "other", searchTerms: { zepto: "tamarind pulp imli", instamart: "imli" }, optional: true },
      { id: "odisha_snack_ghuguni_mustard_oil", name: "Mustard oil", quantity: 2, unit: "tbsp", category: "oil", searchTerms: { zepto: "mustard oil", instamart: "sarson ka tel" } },
      { id: "odisha_snack_ghuguni_sev_for_garnish", name: "Sev (for garnish)", quantity: 30, unit: "g", category: "other", searchTerms: { zepto: "sev namkeen", instamart: "sev" }, optional: true }
    ],
    steps: [
      "Soak the dried yellow peas overnight; pressure cook with turmeric and salt until soft.",
      "Heat mustard oil, sauté onion until golden, then add ginger-garlic paste and tomato and cook till soft.",
      "Add the boiled peas along with their water and simmer until the curry thickens slightly.",
      "Stir in tamarind pulp for tang and adjust the seasoning.",
      "Serve warm topped with chopped onion and sev."
    ],
    tags: ["street food", "tangy", "protein-rich", "snack"],
  },
  {
    id: "odisha_dinner_macha_besara_fish_in_mustard_gravy",
    name: "Macha Besara (Fish in Mustard Gravy)",
    description: "A classic Odia fish curry cooked in a pungent mustard-paste gravy, typically enjoyed for dinner with plain rice.",
    cuisineRegion: ["Odisha"],
    dietType: "nonveg",
    goalTags: ["maintenance", "muscle", "recovery"],
    mealType: ["dinner"],
    prepTime: 15,
    cookTime: 20,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 400, proteinG: 30, carbsG: 12, fatG: 22 },
    ingredients: [
      { id: "odisha_dinner_macha_besara_fish_in_mustard_gravy_rohu_or_katla_fish", name: "Rohu or Katla fish", quantity: 4, unit: "piece", category: "protein", searchTerms: { zepto: "rohu fish fresh", instamart: "rohu machli" } },
      { id: "odisha_dinner_macha_besara_fish_in_mustard_gravy_mustard_seeds", name: "Mustard seeds", quantity: 3, unit: "tbsp", category: "spice", searchTerms: { zepto: "mustard seeds", instamart: "rai sarson" } },
      { id: "odisha_dinner_macha_besara_fish_in_mustard_gravy_green_chilli", name: "Green chilli", quantity: 3, unit: "piece", category: "vegetable", searchTerms: { zepto: "green chilli", instamart: "hari mirch" }, optional: true },
      { id: "odisha_dinner_macha_besara_fish_in_mustard_gravy_turmeric_powder", name: "Turmeric powder", quantity: 1.5, unit: "tsp", category: "spice", searchTerms: { zepto: "turmeric powder", instamart: "haldi" } },
      { id: "odisha_dinner_macha_besara_fish_in_mustard_gravy_mustard_oil", name: "Mustard oil", quantity: 3, unit: "tbsp", category: "oil", searchTerms: { zepto: "mustard oil", instamart: "sarson ka tel" } },
      { id: "odisha_dinner_macha_besara_fish_in_mustard_gravy_nigella_seeds_kalonji", name: "Nigella seeds (kalonji)", quantity: 0.5, unit: "tsp", category: "spice", searchTerms: { zepto: "kalonji nigella seeds", instamart: "kalonji" }, optional: true },
      { id: "odisha_dinner_macha_besara_fish_in_mustard_gravy_garlic", name: "Garlic", quantity: 4, unit: "clove", category: "vegetable", searchTerms: { zepto: "garlic", instamart: "lahsun" }, optional: true }
    ],
    steps: [
      "Marinate the fish pieces with salt and turmeric; shallow fry lightly in mustard oil and set aside.",
      "Grind mustard seeds, green chilli and garlic with a little water into a smooth paste.",
      "In the same oil, temper kalonji, add the mustard paste and turmeric, and cook briefly until the raw smell disappears.",
      "Add water to form a thin gravy and bring to a simmer.",
      "Slide in the fried fish, cover and cook 6-8 minutes on low heat without overcooking.",
      "Serve hot with steamed rice."
    ],
    tags: ["fish", "mustard", "tangy", "dinner"],
  },
  {
    id: "bihar_breakfast_sattu_paratha",
    name: "Sattu Paratha",
    description: "Whole-wheat flatbread stuffed with a spiced roasted-gram (sattu) filling, a protein-packed Bihari breakfast served with curd or pickle.",
    cuisineRegion: ["Bihar"],
    dietType: "veg",
    goalTags: ["maintenance"],
    mealType: ["breakfast"],
    prepTime: 20,
    cookTime: 20,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 340, proteinG: 12, carbsG: 45, fatG: 12 },
    ingredients: [
      { id: "bihar_breakfast_sattu_paratha_whole_wheat_flour_atta", name: "Whole wheat flour (atta)", quantity: 250, unit: "g", category: "grain", searchTerms: { zepto: "wheat flour atta", instamart: "atta" } },
      { id: "bihar_breakfast_sattu_paratha_sattu_roasted_gram_flour", name: "Sattu (roasted gram flour)", quantity: 150, unit: "g", category: "protein", searchTerms: { zepto: "sattu roasted gram flour", instamart: "sattu" } },
      { id: "bihar_breakfast_sattu_paratha_onion", name: "Onion", quantity: 1, unit: "small", category: "vegetable", searchTerms: { zepto: "onion", instamart: "pyaz" }, optional: true },
      { id: "bihar_breakfast_sattu_paratha_green_chilli", name: "Green chilli", quantity: 2, unit: "piece", category: "vegetable", searchTerms: { zepto: "green chilli", instamart: "hari mirch" }, optional: true },
      { id: "bihar_breakfast_sattu_paratha_mustard_oil", name: "Mustard oil", quantity: 2, unit: "tbsp", category: "oil", searchTerms: { zepto: "mustard oil", instamart: "sarson ka tel" } },
      { id: "bihar_breakfast_sattu_paratha_lemon", name: "Lemon", quantity: 1, unit: "piece", category: "fruit", searchTerms: { zepto: "lemon", instamart: "nimbu" }, optional: true },
      { id: "bihar_breakfast_sattu_paratha_ajwain_carom_seeds", name: "Ajwain (carom seeds)", quantity: 0.5, unit: "tsp", category: "spice", searchTerms: { zepto: "ajwain carom seeds", instamart: "ajwain" }, optional: true },
      { id: "bihar_breakfast_sattu_paratha_ghee_for_roasting", name: "Ghee (for roasting)", quantity: 2, unit: "tbsp", category: "dairy", searchTerms: { zepto: "ghee", instamart: "desi ghee" } },
      { id: "bihar_breakfast_sattu_paratha_curd_to_serve", name: "Curd (to serve)", quantity: 100, unit: "g", category: "dairy", searchTerms: { zepto: "curd yogurt", instamart: "dahi" }, optional: true }
    ],
    steps: [
      "Knead the wheat flour into a soft dough with water and a little salt; rest 15 minutes.",
      "Mix sattu with chopped onion, green chilli, mustard oil, lemon juice, ajwain and salt, adding a splash of water to bind.",
      "Roll a dough ball into a small disc, place the sattu filling in the centre and seal into a stuffed ball.",
      "Roll out gently into a paratha and roast on a hot griddle with ghee until golden on both sides.",
      "Serve hot with curd or pickle."
    ],
    tags: ["stuffed paratha", "protein-rich", "breakfast staple"],
  },
  {
    id: "bihar_lunch_litti_chokha",
    name: "Litti Chokha",
    description: "Roasted sattu-stuffed wheat balls served with mashed spiced potato-brinjal chokha and a drizzle of ghee — Bihar's signature meal.",
    cuisineRegion: ["Bihar"],
    dietType: "veg",
    goalTags: ["maintenance"],
    mealType: ["lunch"],
    prepTime: 25,
    cookTime: 40,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 450, proteinG: 15, carbsG: 55, fatG: 18 },
    ingredients: [
      { id: "bihar_lunch_litti_chokha_whole_wheat_flour_atta", name: "Whole wheat flour (atta)", quantity: 250, unit: "g", category: "grain", searchTerms: { zepto: "wheat flour atta", instamart: "atta" } },
      { id: "bihar_lunch_litti_chokha_sattu_roasted_gram_flour", name: "Sattu (roasted gram flour)", quantity: 200, unit: "g", category: "protein", searchTerms: { zepto: "sattu roasted gram flour", instamart: "sattu" } },
      { id: "bihar_lunch_litti_chokha_mustard_oil", name: "Mustard oil", quantity: 3, unit: "tbsp", category: "oil", searchTerms: { zepto: "mustard oil", instamart: "sarson ka tel" } },
      { id: "bihar_lunch_litti_chokha_ajwain_carom_seeds", name: "Ajwain (carom seeds)", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "ajwain carom seeds", instamart: "ajwain" }, optional: true },
      { id: "bihar_lunch_litti_chokha_brinjal", name: "Brinjal", quantity: 1, unit: "large", category: "vegetable", searchTerms: { zepto: "brinjal eggplant", instamart: "baingan" } },
      { id: "bihar_lunch_litti_chokha_potato", name: "Potato", quantity: 3, unit: "medium", category: "vegetable", searchTerms: { zepto: "potato", instamart: "aloo" } },
      { id: "bihar_lunch_litti_chokha_tomato", name: "Tomato", quantity: 2, unit: "medium", category: "vegetable", searchTerms: { zepto: "tomato", instamart: "tamatar" }, optional: true },
      { id: "bihar_lunch_litti_chokha_garlic", name: "Garlic", quantity: 4, unit: "clove", category: "vegetable", searchTerms: { zepto: "garlic", instamart: "lahsun" }, optional: true },
      { id: "bihar_lunch_litti_chokha_ghee", name: "Ghee", quantity: 3, unit: "tbsp", category: "dairy", searchTerms: { zepto: "ghee", instamart: "desi ghee" } }
    ],
    steps: [
      "Knead the wheat flour into a stiff dough; make small balls and stuff with a mix of sattu, mustard oil, ajwain, chopped garlic, salt and a little water.",
      "Seal the balls fully and roast on an open flame or in a hot oven, turning until crusty and cooked through.",
      "Roast the brinjal, potatoes and tomatoes directly over flame or in the oven until charred and soft; peel.",
      "Mash them together with garlic, mustard oil, green chilli and salt to make the chokha.",
      "Dip the roasted littis in ghee and serve hot alongside the chokha."
    ],
    tags: ["iconic", "roasted", "wholesome", "festive"],
  },
  {
    id: "bihar_snack_chura_matar",
    name: "Chura Matar",
    description: "A light, home-style snack of flattened rice sautéed with green peas, mild spices and a hint of ghee — a favourite Bihari winter tea-time dish.",
    cuisineRegion: ["Bihar"],
    dietType: "veg",
    goalTags: ["maintenance", "weight_loss"],
    mealType: ["snack"],
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 210, proteinG: 6, carbsG: 32, fatG: 7 },
    ingredients: [
      { id: "bihar_snack_chura_matar_thick_poha_flattened_rice", name: "Thick poha (flattened rice)", quantity: 200, unit: "g", category: "grain", searchTerms: { zepto: "poha flattened rice", instamart: "poha" } },
      { id: "bihar_snack_chura_matar_green_peas", name: "Green peas", quantity: 150, unit: "g", category: "vegetable", searchTerms: { zepto: "green peas", instamart: "matar" } },
      { id: "bihar_snack_chura_matar_onion", name: "Onion", quantity: 1, unit: "small", category: "vegetable", searchTerms: { zepto: "onion", instamart: "pyaz" }, optional: true },
      { id: "bihar_snack_chura_matar_green_chilli", name: "Green chilli", quantity: 2, unit: "piece", category: "vegetable", searchTerms: { zepto: "green chilli", instamart: "hari mirch" }, optional: true },
      { id: "bihar_snack_chura_matar_ghee", name: "Ghee", quantity: 2, unit: "tbsp", category: "dairy", searchTerms: { zepto: "ghee", instamart: "desi ghee" } },
      { id: "bihar_snack_chura_matar_cumin_seeds", name: "Cumin seeds", quantity: 0.5, unit: "tsp", category: "spice", searchTerms: { zepto: "cumin seeds jeera", instamart: "jeera" }, optional: true },
      { id: "bihar_snack_chura_matar_turmeric_powder", name: "Turmeric powder", quantity: 0.25, unit: "tsp", category: "spice", searchTerms: { zepto: "turmeric powder", instamart: "haldi" }, optional: true }
    ],
    steps: [
      "Rinse the thick poha briefly and drain; set aside to soften slightly.",
      "Heat ghee in a pan, temper cumin seeds, add onion and green chilli, and sauté until soft.",
      "Add green peas and a little water, and cook until the peas are tender.",
      "Add turmeric and salt, then fold in the softened poha, mixing gently.",
      "Cook for 2-3 minutes on low heat and serve warm."
    ],
    tags: ["quick", "winter", "light", "tea-time"],
  },
  {
    id: "bihar_dinner_bihari_kadhi_badi_with_rice",
    name: "Bihari Kadhi Badi with Rice",
    description: "A tangy besan-and-curd kadhi studded with fried gram-flour dumplings, a comforting Bihari dinner staple served over rice.",
    cuisineRegion: ["Bihar"],
    dietType: "veg",
    goalTags: ["maintenance"],
    mealType: ["dinner"],
    prepTime: 15,
    cookTime: 30,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 380, proteinG: 13, carbsG: 48, fatG: 14 },
    ingredients: [
      { id: "bihar_dinner_bihari_kadhi_badi_with_rice_besan_gram_flour", name: "Besan (gram flour)", quantity: 150, unit: "g", category: "protein", searchTerms: { zepto: "besan gram flour", instamart: "besan" } },
      { id: "bihar_dinner_bihari_kadhi_badi_with_rice_curd_sour_yogurt", name: "Curd (sour yogurt)", quantity: 250, unit: "g", category: "dairy", searchTerms: { zepto: "curd yogurt", instamart: "dahi" } },
      { id: "bihar_dinner_bihari_kadhi_badi_with_rice_onion", name: "Onion", quantity: 1, unit: "small", category: "vegetable", searchTerms: { zepto: "onion", instamart: "pyaz" }, optional: true },
      { id: "bihar_dinner_bihari_kadhi_badi_with_rice_mustard_seeds", name: "Mustard seeds", quantity: 0.5, unit: "tsp", category: "spice", searchTerms: { zepto: "mustard seeds", instamart: "rai sarson" }, optional: true },
      { id: "bihar_dinner_bihari_kadhi_badi_with_rice_curry_leaves", name: "Curry leaves", quantity: 6, unit: "piece", category: "spice", searchTerms: { zepto: "curry leaves", instamart: "kadi patta" }, optional: true },
      { id: "bihar_dinner_bihari_kadhi_badi_with_rice_turmeric_powder", name: "Turmeric powder", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "turmeric powder", instamart: "haldi" } },
      { id: "bihar_dinner_bihari_kadhi_badi_with_rice_mustard_refined_oil", name: "Mustard/refined oil", quantity: 3, unit: "tbsp", category: "oil", searchTerms: { zepto: "mustard oil", instamart: "sarson ka tel" } },
      { id: "bihar_dinner_bihari_kadhi_badi_with_rice_rice_for_serving", name: "Rice (for serving)", quantity: 300, unit: "g", category: "grain", searchTerms: { zepto: "rice", instamart: "chawal" } }
    ],
    steps: [
      "Make a thick batter with half the besan, chopped onion, a pinch of salt and water; deep fry small dumplings (badi) until golden, then drain.",
      "Whisk the remaining besan into sour curd with turmeric and water to make a smooth, thin mixture.",
      "Heat oil, temper mustard seeds and curry leaves, then pour in the curd-besan mixture, stirring continuously to prevent curdling.",
      "Simmer on low heat for 15-20 minutes until the kadhi thickens, then add the fried badi.",
      "Simmer 5 more minutes and serve hot with steamed rice."
    ],
    tags: ["comfort food", "tangy", "dinner", "curd-based"],
  },
  {
    id: "jharkhand_breakfast_dhuska_with_ghugni",
    name: "Dhuska with Ghugni",
    description: "Deep-fried, lightly spiced rice-and-lentil pancakes, a much-loved Jharkhand breakfast usually paired with spicy ghugni or aloo curry.",
    cuisineRegion: ["Jharkhand"],
    dietType: "veg",
    goalTags: ["maintenance"],
    mealType: ["breakfast"],
    prepTime: 15,
    cookTime: 25,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 350, proteinG: 10, carbsG: 42, fatG: 16 },
    ingredients: [
      { id: "jharkhand_breakfast_dhuska_with_ghugni_raw_rice", name: "Raw rice", quantity: 200, unit: "g", category: "grain", searchTerms: { zepto: "raw rice", instamart: "chawal" } },
      { id: "jharkhand_breakfast_dhuska_with_ghugni_chana_dal_split_gram", name: "Chana dal (split gram)", quantity: 80, unit: "g", category: "protein", searchTerms: { zepto: "chana dal", instamart: "chana dal" } },
      { id: "jharkhand_breakfast_dhuska_with_ghugni_onion", name: "Onion", quantity: 1, unit: "small", category: "vegetable", searchTerms: { zepto: "onion", instamart: "pyaz" }, optional: true },
      { id: "jharkhand_breakfast_dhuska_with_ghugni_cumin_seeds", name: "Cumin seeds", quantity: 0.5, unit: "tsp", category: "spice", searchTerms: { zepto: "cumin seeds jeera", instamart: "jeera" }, optional: true },
      { id: "jharkhand_breakfast_dhuska_with_ghugni_green_chilli", name: "Green chilli", quantity: 2, unit: "piece", category: "vegetable", searchTerms: { zepto: "green chilli", instamart: "hari mirch" }, optional: true },
      { id: "jharkhand_breakfast_dhuska_with_ghugni_sunflower_refined_oil_for_frying", name: "Sunflower/refined oil (for frying)", quantity: 250, unit: "ml", category: "oil", searchTerms: { zepto: "sunflower oil", instamart: "refined tel" } },
      { id: "jharkhand_breakfast_dhuska_with_ghugni_dried_yellow_peas_for_ghugni", name: "Dried yellow peas (for ghugni)", quantity: 150, unit: "g", category: "protein", searchTerms: { zepto: "dried yellow peas", instamart: "safed matar" }, optional: true }
    ],
    steps: [
      "Soak the rice and chana dal together for 4-5 hours, then grind into a thick, slightly coarse batter.",
      "Mix in chopped onion, green chilli, cumin seeds and salt.",
      "Heat oil in a kadai, pour small ladlefuls of batter and deep fry until crisp and golden on both sides.",
      "Meanwhile, prepare a simple ghugni by simmering soaked, boiled yellow peas with onion, turmeric and spices.",
      "Serve the hot dhuska with ghugni or a side of spicy aloo curry."
    ],
    tags: ["fried", "breakfast staple", "tribal cuisine"],
  },
  {
    id: "jharkhand_lunch_rugra_wild_mushroom_curry_with_rice",
    name: "Rugra (Wild Mushroom) Curry with Rice",
    description: "A rustic tribal Jharkhand curry made from rugra, a seasonal wild desert-truffle mushroom, simmered in an onion-tomato gravy and served with rice.",
    cuisineRegion: ["Jharkhand"],
    dietType: "veg",
    goalTags: ["maintenance"],
    mealType: ["lunch"],
    prepTime: 15,
    cookTime: 25,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 320, proteinG: 9, carbsG: 50, fatG: 9 },
    ingredients: [
      { id: "jharkhand_lunch_rugra_wild_mushroom_curry_with_rice_rugra_wild_mushroom_or_button_mushroom", name: "Rugra (wild mushroom, or button mushroom substitute)", quantity: 250, unit: "g", category: "vegetable", searchTerms: { zepto: "mushroom fresh", instamart: "mushroom" } },
      { id: "jharkhand_lunch_rugra_wild_mushroom_curry_with_rice_onion", name: "Onion", quantity: 2, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "pyaz" } },
      { id: "jharkhand_lunch_rugra_wild_mushroom_curry_with_rice_tomato", name: "Tomato", quantity: 2, unit: "medium", category: "vegetable", searchTerms: { zepto: "tomato", instamart: "tamatar" } },
      { id: "jharkhand_lunch_rugra_wild_mushroom_curry_with_rice_ginger_garlic_paste", name: "Ginger-garlic paste", quantity: 1, unit: "tbsp", category: "spice", searchTerms: { zepto: "ginger garlic paste", instamart: "adrak lahsun paste" } },
      { id: "jharkhand_lunch_rugra_wild_mushroom_curry_with_rice_mustard_oil", name: "Mustard oil", quantity: 3, unit: "tbsp", category: "oil", searchTerms: { zepto: "mustard oil", instamart: "sarson ka tel" } },
      { id: "jharkhand_lunch_rugra_wild_mushroom_curry_with_rice_turmeric_powder", name: "Turmeric powder", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "turmeric powder", instamart: "haldi" } },
      { id: "jharkhand_lunch_rugra_wild_mushroom_curry_with_rice_red_chilli_powder", name: "Red chilli powder", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "red chilli powder", instamart: "lal mirch powder" }, optional: true },
      { id: "jharkhand_lunch_rugra_wild_mushroom_curry_with_rice_rice_for_serving", name: "Rice (for serving)", quantity: 300, unit: "g", category: "grain", searchTerms: { zepto: "rice", instamart: "chawal" } }
    ],
    steps: [
      "Clean the rugra or mushrooms thoroughly and chop into bite-sized pieces.",
      "Heat mustard oil, sauté onions until golden, then add ginger-garlic paste and cook till fragrant.",
      "Add tomatoes, turmeric and red chilli powder, and cook until the masala thickens and oil separates.",
      "Add the mushrooms and salt, cover and cook on low heat until tender, adding a little water as needed.",
      "Simmer until the gravy reaches the desired consistency and serve hot with steamed rice."
    ],
    tags: ["tribal cuisine", "mushroom", "seasonal", "rustic"],
  },
  {
    id: "jharkhand_snack_thekua",
    name: "Thekua",
    description: "A dense, sweet, deep-fried wheat-flour and jaggery snack, traditionally made in Jharkhand and enjoyed as a tea-time and festive treat.",
    cuisineRegion: ["Jharkhand"],
    dietType: "veg",
    goalTags: ["maintenance", "weight_loss"],
    mealType: ["snack"],
    prepTime: 15,
    cookTime: 20,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 260, proteinG: 3, carbsG: 38, fatG: 11 },
    ingredients: [
      { id: "jharkhand_snack_thekua_whole_wheat_flour_atta", name: "Whole wheat flour (atta)", quantity: 200, unit: "g", category: "grain", searchTerms: { zepto: "wheat flour atta", instamart: "atta" } },
      { id: "jharkhand_snack_thekua_jaggery", name: "Jaggery", quantity: 100, unit: "g", category: "other", searchTerms: { zepto: "jaggery gur", instamart: "gur" } },
      { id: "jharkhand_snack_thekua_ghee", name: "Ghee", quantity: 2, unit: "tbsp", category: "dairy", searchTerms: { zepto: "ghee", instamart: "desi ghee" } },
      { id: "jharkhand_snack_thekua_grated_coconut_dried", name: "Grated coconut (dried)", quantity: 30, unit: "g", category: "other", searchTerms: { zepto: "desiccated coconut", instamart: "nariyal burada" }, optional: true },
      { id: "jharkhand_snack_thekua_fennel_seeds", name: "Fennel seeds", quantity: 0.5, unit: "tsp", category: "spice", searchTerms: { zepto: "fennel seeds saunf", instamart: "saunf" }, optional: true },
      { id: "jharkhand_snack_thekua_sunflower_refined_oil_for_frying", name: "Sunflower/refined oil (for frying)", quantity: 250, unit: "ml", category: "oil", searchTerms: { zepto: "sunflower oil", instamart: "refined tel" } }
    ],
    steps: [
      "Dissolve jaggery in a little warm water to make a syrup.",
      "Mix wheat flour with ghee, grated coconut and fennel seeds, then knead into a stiff dough using the jaggery syrup.",
      "Divide into small portions and press or shape into flat discs with ridged patterns.",
      "Deep fry on low-medium heat until deep golden brown and crisp, turning occasionally.",
      "Cool completely before storing or serving; keeps well for several days."
    ],
    tags: ["sweet", "fried", "festive", "tea-time"],
  },
  {
    id: "jharkhand_dinner_chilka_roti_with_desi_chicken_curry",
    name: "Chilka Roti with Desi Chicken Curry",
    description: "Rice-flour crepe-like flatbread paired with a rustic mustard-oil country chicken curry, a hearty Jharkhand dinner combination.",
    cuisineRegion: ["Jharkhand"],
    dietType: "nonveg",
    goalTags: ["maintenance", "muscle", "recovery"],
    mealType: ["dinner"],
    prepTime: 20,
    cookTime: 35,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 480, proteinG: 32, carbsG: 38, fatG: 22 },
    ingredients: [
      { id: "jharkhand_dinner_chilka_roti_with_desi_chicken_curry_rice_flour", name: "Rice flour", quantity: 200, unit: "g", category: "grain", searchTerms: { zepto: "rice flour", instamart: "chawal ka atta" } },
      { id: "jharkhand_dinner_chilka_roti_with_desi_chicken_curry_chicken_curry_cut", name: "Chicken, curry cut", quantity: 500, unit: "g", category: "protein", searchTerms: { zepto: "chicken curry cut", instamart: "chicken" } },
      { id: "jharkhand_dinner_chilka_roti_with_desi_chicken_curry_onion", name: "Onion", quantity: 2, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "pyaz" } },
      { id: "jharkhand_dinner_chilka_roti_with_desi_chicken_curry_tomato", name: "Tomato", quantity: 2, unit: "medium", category: "vegetable", searchTerms: { zepto: "tomato", instamart: "tamatar" } },
      { id: "jharkhand_dinner_chilka_roti_with_desi_chicken_curry_ginger_garlic_paste", name: "Ginger-garlic paste", quantity: 1.5, unit: "tbsp", category: "spice", searchTerms: { zepto: "ginger garlic paste", instamart: "adrak lahsun paste" } },
      { id: "jharkhand_dinner_chilka_roti_with_desi_chicken_curry_mustard_oil", name: "Mustard oil", quantity: 3, unit: "tbsp", category: "oil", searchTerms: { zepto: "mustard oil", instamart: "sarson ka tel" } },
      { id: "jharkhand_dinner_chilka_roti_with_desi_chicken_curry_turmeric_powder", name: "Turmeric powder", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "turmeric powder", instamart: "haldi" } },
      { id: "jharkhand_dinner_chilka_roti_with_desi_chicken_curry_red_chilli_powder", name: "Red chilli powder", quantity: 1.5, unit: "tsp", category: "spice", searchTerms: { zepto: "red chilli powder", instamart: "lal mirch powder" }, optional: true }
    ],
    steps: [
      "Mix rice flour with water and a pinch of salt into a thin, lump-free batter; rest 15 minutes.",
      "Heat mustard oil, sauté onions until golden, then add ginger-garlic paste, tomatoes, turmeric and chilli powder, cooking till the oil separates.",
      "Add chicken pieces, sear on high heat for a few minutes, then add salt and a little water.",
      "Cover and simmer until the chicken is fully cooked and the gravy thickens.",
      "Meanwhile, pour ladles of rice batter onto a hot griddle and cook into thin crepes (chilka roti) on both sides.",
      "Serve the hot chilka roti alongside the chicken curry."
    ],
    tags: ["rustic", "chicken", "dinner", "mustard oil"],
  },
];
