import type { Recipe } from "../types";

// Auto-generated from regional recipe research (Northeast zone).
export const NORTHEAST_RECIPES: Recipe[] = [
  {
    id: "assam_breakfast_chira_doi_flattened_rice_with_curd_and_jaggery",
    name: "Chira Doi (Flattened Rice with Curd and Jaggery)",
    description: "A quick Bihu-morning classic of soaked flattened rice mixed with fresh curd and jaggery.",
    cuisineRegion: ["Assam"],
    dietType: "veg",
    goalTags: ["maintenance"],
    mealType: ["breakfast"],
    prepTime: 10,
    cookTime: 0,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 320, proteinG: 9, carbsG: 58, fatG: 6 },
    ingredients: [
      { id: "assam_breakfast_chira_doi_flattened_rice_with_curd_and_jaggery_flattened_rice_thick_chira_", name: "Flattened rice (thick chira/poha)", quantity: 150, unit: "g", category: "grain", searchTerms: { zepto: "thick poha flattened rice", instamart: "chira poha thick" } },
      { id: "assam_breakfast_chira_doi_flattened_rice_with_curd_and_jaggery_curd_dahi", name: "Curd (dahi)", quantity: 300, unit: "g", category: "dairy", searchTerms: { zepto: "fresh curd", instamart: "curd" } },
      { id: "assam_breakfast_chira_doi_flattened_rice_with_curd_and_jaggery_jaggery_gur", name: "Jaggery (gur)", quantity: 80, unit: "g", category: "other", searchTerms: { zepto: "jaggery gur", instamart: "jaggery" } },
      { id: "assam_breakfast_chira_doi_flattened_rice_with_curd_and_jaggery_banana", name: "Banana", quantity: 2, unit: "medium", category: "fruit", searchTerms: { zepto: "banana", instamart: "banana" }, optional: true },
      { id: "assam_breakfast_chira_doi_flattened_rice_with_curd_and_jaggery_milk", name: "Milk", quantity: 100, unit: "ml", category: "dairy", searchTerms: { zepto: "toned milk", instamart: "milk" }, optional: true }
    ],
    steps: [
      "Rinse the thick flattened rice briefly and let it soften for 5 minutes.",
      "Whisk the curd until smooth, loosening with a little milk if needed.",
      "Divide the soaked chira into two bowls and top with curd and jaggery.",
      "Add sliced banana and serve immediately."
    ],
    tags: ["quick", "no-cook", "festive", "sweet"],
  },
  {
    id: "assam_lunch_masor_tenga_sour_fish_curry",
    name: "Masor Tenga (Sour Fish Curry)",
    description: "A light, tangy Assamese fish curry soured with tomato and lemon, the everyday centerpiece of an Assamese lunch.",
    cuisineRegion: ["Assam"],
    dietType: "nonveg",
    goalTags: ["maintenance", "muscle", "recovery"],
    mealType: ["lunch"],
    prepTime: 15,
    cookTime: 25,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 420, proteinG: 32, carbsG: 12, fatG: 22 },
    ingredients: [
      { id: "assam_lunch_masor_tenga_sour_fish_curry_rohu_fish_curry_cut", name: "Rohu fish (curry cut)", quantity: 400, unit: "g", category: "protein", searchTerms: { zepto: "rohu fish curry cut", instamart: "rohu fish" } },
      { id: "assam_lunch_masor_tenga_sour_fish_curry_tomato", name: "Tomato", quantity: 3, unit: "medium", category: "vegetable", searchTerms: { zepto: "tomato", instamart: "tomato" } },
      { id: "assam_lunch_masor_tenga_sour_fish_curry_lemon", name: "Lemon", quantity: 1, unit: "piece", category: "fruit", searchTerms: { zepto: "lemon", instamart: "lemon" } },
      { id: "assam_lunch_masor_tenga_sour_fish_curry_mustard_oil", name: "Mustard oil", quantity: 3, unit: "tbsp", category: "oil", searchTerms: { zepto: "mustard oil", instamart: "mustard oil" } },
      { id: "assam_lunch_masor_tenga_sour_fish_curry_fenugreek_seeds", name: "Fenugreek seeds", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "methi dana fenugreek seeds", instamart: "fenugreek seeds" } },
      { id: "assam_lunch_masor_tenga_sour_fish_curry_turmeric_powder", name: "Turmeric powder", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "turmeric powder", instamart: "haldi powder" } },
      { id: "assam_lunch_masor_tenga_sour_fish_curry_green_chilli", name: "Green chilli", quantity: 3, unit: "piece", category: "vegetable", searchTerms: { zepto: "green chilli", instamart: "green chilli" } },
      { id: "assam_lunch_masor_tenga_sour_fish_curry_elephant_apple_outenga_or_raw_mango_as_substitute", name: "Elephant apple (outenga), or raw mango as substitute", quantity: 1, unit: "piece", category: "fruit", searchTerms: { zepto: "raw mango", instamart: "raw mango" }, optional: true }
    ],
    steps: [
      "Marinate fish pieces with turmeric and salt, shallow fry lightly in mustard oil, and set aside.",
      "In the same oil, temper fenugreek seeds until fragrant.",
      "Add chopped tomatoes (and elephant apple or raw mango, if using) and cook until pulpy and sour.",
      "Add water, turmeric and salt, and bring to a boil.",
      "Slide in the fried fish and green chillies, and simmer for 8-10 minutes.",
      "Finish with a squeeze of lemon juice and serve hot with steamed rice."
    ],
    tags: ["sour", "light", "everyday", "fish"],
  },
  {
    id: "assam_snack_til_pitha_sesame_rice_rolls",
    name: "Til Pitha (Sesame Rice Rolls)",
    description: "Thin rice flour crepes rolled around a sweet roasted sesame-jaggery filling, a beloved Assamese tea-time snack.",
    cuisineRegion: ["Assam"],
    dietType: "veg",
    goalTags: ["maintenance", "weight_loss"],
    mealType: ["snack"],
    prepTime: 20,
    cookTime: 20,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 280, proteinG: 5, carbsG: 45, fatG: 9 },
    ingredients: [
      { id: "assam_snack_til_pitha_sesame_rice_rolls_rice_flour", name: "Rice flour", quantity: 200, unit: "g", category: "grain", searchTerms: { zepto: "rice flour", instamart: "rice flour" } },
      { id: "assam_snack_til_pitha_sesame_rice_rolls_black_sesame_seeds", name: "Black sesame seeds", quantity: 150, unit: "g", category: "other", searchTerms: { zepto: "black til sesame seeds", instamart: "sesame seeds" } },
      { id: "assam_snack_til_pitha_sesame_rice_rolls_jaggery", name: "Jaggery", quantity: 100, unit: "g", category: "other", searchTerms: { zepto: "jaggery gur", instamart: "jaggery" } },
      { id: "assam_snack_til_pitha_sesame_rice_rolls_water", name: "Water", quantity: 300, unit: "ml", category: "other", searchTerms: { zepto: "packaged drinking water", instamart: "drinking water" } },
      { id: "assam_snack_til_pitha_sesame_rice_rolls_salt", name: "Salt", quantity: 1, unit: "pinch", category: "spice", searchTerms: { zepto: "salt", instamart: "salt" } }
    ],
    steps: [
      "Dry roast sesame seeds until fragrant, cool, and coarsely pound with jaggery to make the filling.",
      "Make a thin batter with rice flour, a pinch of salt and water.",
      "Pour a ladleful onto a hot greased griddle to form a thin crepe (pitha).",
      "While still warm and pliable, spoon the sesame-jaggery filling along one edge and roll it up tightly.",
      "Repeat with the remaining batter and serve warm."
    ],
    tags: ["sweet", "festive", "tea-time", "rice-flour"],
  },
  {
    id: "assam_dinner_khar_raw_papaya_and_lentil_alkaline_curry",
    name: "Khar (Raw Papaya and Lentil Alkaline Curry)",
    description: "Assam's signature alkaline dish of raw papaya and lentils simmered with a traditional filtered ash-water base, always the opening course of an Assamese meal.",
    cuisineRegion: ["Assam"],
    dietType: "veg",
    goalTags: ["maintenance", "weight_loss"],
    mealType: ["dinner"],
    prepTime: 15,
    cookTime: 25,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 260, proteinG: 10, carbsG: 30, fatG: 11 },
    ingredients: [
      { id: "assam_dinner_khar_raw_papaya_and_lentil_alkaline_curry_raw_papaya", name: "Raw papaya", quantity: 300, unit: "g", category: "vegetable", searchTerms: { zepto: "raw papaya", instamart: "raw papaya" } },
      { id: "assam_dinner_khar_raw_papaya_and_lentil_alkaline_curry_split_black_gram_kolai_dal", name: "Split black gram (kolai dal)", quantity: 100, unit: "g", category: "protein", searchTerms: { zepto: "urad dal split", instamart: "urad dal" } },
      { id: "assam_dinner_khar_raw_papaya_and_lentil_alkaline_curry_khar_traditional_culinary_alkali", name: "Khar (traditional culinary alkali)", quantity: 2, unit: "tbsp", category: "other", searchTerms: { zepto: "baking soda", instamart: "baking soda" }, optional: true },
      { id: "assam_dinner_khar_raw_papaya_and_lentil_alkaline_curry_mustard_oil", name: "Mustard oil", quantity: 2, unit: "tbsp", category: "oil", searchTerms: { zepto: "mustard oil", instamart: "mustard oil" } },
      { id: "assam_dinner_khar_raw_papaya_and_lentil_alkaline_curry_green_chilli", name: "Green chilli", quantity: 2, unit: "piece", category: "vegetable", searchTerms: { zepto: "green chilli", instamart: "green chilli" } },
      { id: "assam_dinner_khar_raw_papaya_and_lentil_alkaline_curry_garlic", name: "Garlic", quantity: 4, unit: "clove", category: "vegetable", searchTerms: { zepto: "garlic", instamart: "garlic" } },
      { id: "assam_dinner_khar_raw_papaya_and_lentil_alkaline_curry_dried_red_chilli", name: "Dried red chilli", quantity: 2, unit: "piece", category: "spice", searchTerms: { zepto: "dry red chilli", instamart: "dried red chilli" }, optional: true }
    ],
    steps: [
      "Heat mustard oil and temper with dried red chilli and crushed garlic.",
      "Add cubed raw papaya and lightly roasted lentils, and sauté for 2 minutes.",
      "Pour in water and the khar (or a pinch of baking soda as a home substitute), and season with salt.",
      "Simmer until the papaya turns soft and slightly mushy.",
      "Finish with slit green chillies and serve as the first course with steamed rice."
    ],
    tags: ["alkaline", "traditional", "comfort", "healthy"],
  },
  {
    id: "meghalaya_breakfast_pumaloi_steamed_rice_cake",
    name: "Pumaloi (Steamed Rice Cake)",
    description: "A soft, fluffy steamed rice cake, the everyday Khasi breakfast eaten with tea or a side of pork.",
    cuisineRegion: ["Meghalaya"],
    dietType: "veg",
    goalTags: ["maintenance", "weight_loss"],
    mealType: ["breakfast"],
    prepTime: 15,
    cookTime: 20,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 260, proteinG: 5, carbsG: 55, fatG: 2 },
    ingredients: [
      { id: "meghalaya_breakfast_pumaloi_steamed_rice_cake_rice_short_grain", name: "Rice (short-grain)", quantity: 250, unit: "g", category: "grain", searchTerms: { zepto: "rice", instamart: "rice" } },
      { id: "meghalaya_breakfast_pumaloi_steamed_rice_cake_salt", name: "Salt", quantity: 1, unit: "pinch", category: "spice", searchTerms: { zepto: "salt", instamart: "salt" } },
      { id: "meghalaya_breakfast_pumaloi_steamed_rice_cake_water", name: "Water", quantity: 100, unit: "ml", category: "other", searchTerms: { zepto: "packaged drinking water", instamart: "drinking water" } }
    ],
    steps: [
      "Soak rice for a few hours, then drain and grind coarsely to a semolina-like texture (or use store-bought coarse rice flour).",
      "Sprinkle the coarse rice flour with a little water and salt until it turns crumbly, not wet.",
      "Steam the mixture in a muslin-lined or idli-style steamer for 15-20 minutes until fluffy.",
      "Fluff up with a fork and serve warm with tea."
    ],
    tags: ["steamed", "simple", "staple", "gluten-free"],
  },
  {
    id: "meghalaya_lunch_jadoh_khasi_rice_with_pork",
    name: "Jadoh (Khasi Rice with Pork)",
    description: "Meghalaya's most iconic one-pot dish - rice cooked in a rich pork stock - traditionally eaten for a hearty midday meal.",
    cuisineRegion: ["Meghalaya"],
    dietType: "nonveg",
    goalTags: ["maintenance", "muscle", "recovery", "weight_gain"],
    mealType: ["lunch"],
    prepTime: 20,
    cookTime: 40,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 520, proteinG: 30, carbsG: 55, fatG: 18 },
    ingredients: [
      { id: "meghalaya_lunch_jadoh_khasi_rice_with_pork_rice", name: "Rice", quantity: 250, unit: "g", category: "grain", searchTerms: { zepto: "rice", instamart: "rice" } },
      { id: "meghalaya_lunch_jadoh_khasi_rice_with_pork_pork_with_some_fat", name: "Pork (with some fat)", quantity: 350, unit: "g", category: "protein", searchTerms: { zepto: "pork curry cut", instamart: "pork curry cut" } },
      { id: "meghalaya_lunch_jadoh_khasi_rice_with_pork_pork_blood_for_traditional_colour", name: "Pork blood (for traditional colour)", quantity: 50, unit: "ml", category: "protein", searchTerms: { zepto: "pork", instamart: "pork" }, optional: true },
      { id: "meghalaya_lunch_jadoh_khasi_rice_with_pork_onion", name: "Onion", quantity: 2, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "onion" } },
      { id: "meghalaya_lunch_jadoh_khasi_rice_with_pork_ginger", name: "Ginger", quantity: 1, unit: "inch", category: "vegetable", searchTerms: { zepto: "ginger", instamart: "ginger" } },
      { id: "meghalaya_lunch_jadoh_khasi_rice_with_pork_garlic", name: "Garlic", quantity: 5, unit: "clove", category: "vegetable", searchTerms: { zepto: "garlic", instamart: "garlic" } },
      { id: "meghalaya_lunch_jadoh_khasi_rice_with_pork_turmeric_powder", name: "Turmeric powder", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "turmeric powder", instamart: "haldi powder" } },
      { id: "meghalaya_lunch_jadoh_khasi_rice_with_pork_bay_leaf", name: "Bay leaf", quantity: 2, unit: "piece", category: "spice", searchTerms: { zepto: "tej patta bay leaf", instamart: "bay leaf" }, optional: true },
      { id: "meghalaya_lunch_jadoh_khasi_rice_with_pork_mustard_oil", name: "Mustard oil", quantity: 2, unit: "tbsp", category: "oil", searchTerms: { zepto: "mustard oil", instamart: "mustard oil" } }
    ],
    steps: [
      "Boil the pork in water with turmeric and salt until tender, and reserve the stock.",
      "In a heavy pot, heat mustard oil and sauté onion, ginger, garlic and bay leaf until golden.",
      "Add the cooked pork and fry briefly, then stir in pork blood if using, for the traditional deep colour.",
      "Add washed rice and the reserved pork stock, topped up with water as needed.",
      "Cook covered on low heat until the rice is done and has absorbed all the flavour, stirring gently once or twice.",
      "Serve hot, traditionally with a side onion salad or pickle."
    ],
    tags: ["one-pot", "festive", "hearty", "tribal"],
  },
  {
    id: "meghalaya_snack_pukhlein_sweet_rice_fritters",
    name: "Pukhlein (Sweet Rice Fritters)",
    description: "Deep-fried, jaggery-sweetened rice flour fritters, a favourite Khasi tea-time and market-stall snack.",
    cuisineRegion: ["Meghalaya"],
    dietType: "veg",
    goalTags: ["maintenance", "weight_loss"],
    mealType: ["snack"],
    prepTime: 15,
    cookTime: 15,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 220, proteinG: 3, carbsG: 32, fatG: 9 },
    ingredients: [
      { id: "meghalaya_snack_pukhlein_sweet_rice_fritters_rice_flour", name: "Rice flour", quantity: 200, unit: "g", category: "grain", searchTerms: { zepto: "rice flour", instamart: "rice flour" } },
      { id: "meghalaya_snack_pukhlein_sweet_rice_fritters_jaggery", name: "Jaggery", quantity: 100, unit: "g", category: "other", searchTerms: { zepto: "jaggery gur", instamart: "jaggery" } },
      { id: "meghalaya_snack_pukhlein_sweet_rice_fritters_ripe_banana", name: "Ripe banana", quantity: 1, unit: "medium", category: "fruit", searchTerms: { zepto: "banana", instamart: "banana" }, optional: true },
      { id: "meghalaya_snack_pukhlein_sweet_rice_fritters_water", name: "Water", quantity: 100, unit: "ml", category: "other", searchTerms: { zepto: "packaged drinking water", instamart: "drinking water" } },
      { id: "meghalaya_snack_pukhlein_sweet_rice_fritters_cooking_oil_for_deep_frying", name: "Cooking oil for deep frying", quantity: 300, unit: "ml", category: "oil", searchTerms: { zepto: "cooking oil", instamart: "refined oil" } }
    ],
    steps: [
      "Dissolve jaggery in a little warm water and mash in the ripe banana if using.",
      "Mix in rice flour to form a thick, dropping-consistency batter.",
      "Heat oil in a kadai and drop spoonfuls of the batter in.",
      "Fry on medium heat until golden brown and cooked through, turning occasionally.",
      "Drain on paper and serve warm."
    ],
    tags: ["fried", "sweet", "street-food", "festive"],
  },
  {
    id: "meghalaya_dinner_dohneiiong_pork_with_black_sesame",
    name: "Dohneiiong (Pork with Black Sesame)",
    description: "A rich Khasi pork curry thickened with roasted black sesame paste, a signature dinner dish across Meghalaya.",
    cuisineRegion: ["Meghalaya"],
    dietType: "nonveg",
    goalTags: ["maintenance", "muscle", "recovery", "weight_gain"],
    mealType: ["dinner"],
    prepTime: 15,
    cookTime: 35,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 480, proteinG: 28, carbsG: 10, fatG: 32 },
    ingredients: [
      { id: "meghalaya_dinner_dohneiiong_pork_with_black_sesame_pork_with_fat", name: "Pork (with fat)", quantity: 400, unit: "g", category: "protein", searchTerms: { zepto: "pork curry cut", instamart: "pork curry cut" } },
      { id: "meghalaya_dinner_dohneiiong_pork_with_black_sesame_black_sesame_seeds", name: "Black sesame seeds", quantity: 100, unit: "g", category: "other", searchTerms: { zepto: "black til sesame seeds", instamart: "sesame seeds" } },
      { id: "meghalaya_dinner_dohneiiong_pork_with_black_sesame_onion", name: "Onion", quantity: 2, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "onion" } },
      { id: "meghalaya_dinner_dohneiiong_pork_with_black_sesame_ginger_garlic_paste", name: "Ginger-garlic paste", quantity: 1, unit: "tbsp", category: "vegetable", searchTerms: { zepto: "ginger garlic paste", instamart: "ginger garlic paste" } },
      { id: "meghalaya_dinner_dohneiiong_pork_with_black_sesame_turmeric_powder", name: "Turmeric powder", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "turmeric powder", instamart: "haldi powder" } },
      { id: "meghalaya_dinner_dohneiiong_pork_with_black_sesame_dried_red_chilli", name: "Dried red chilli", quantity: 3, unit: "piece", category: "spice", searchTerms: { zepto: "dry red chilli", instamart: "dried red chilli" }, optional: true },
      { id: "meghalaya_dinner_dohneiiong_pork_with_black_sesame_mustard_oil", name: "Mustard oil", quantity: 2, unit: "tbsp", category: "oil", searchTerms: { zepto: "mustard oil", instamart: "mustard oil" } }
    ],
    steps: [
      "Dry roast the black sesame seeds and grind to a coarse paste with a little water.",
      "Heat mustard oil, sauté onions until soft, then add ginger-garlic paste and dried red chillies.",
      "Add pork pieces, turmeric and salt, and sear for 5-6 minutes.",
      "Pour in water, cover, and simmer until the pork is nearly tender.",
      "Stir in the sesame paste and simmer uncovered until the gravy thickens and turns glossy.",
      "Serve hot with steamed rice."
    ],
    tags: ["nutty", "rich", "tribal", "festive"],
  },
  {
    id: "manipur_breakfast_chak_hao_kheer_black_rice_pudding",
    name: "Chak-hao Kheer (Black Rice Pudding)",
    description: "Manipur's prized black rice slow-cooked into a fragrant, naturally purple sweet pudding, often enjoyed on special mornings.",
    cuisineRegion: ["Manipur"],
    dietType: "veg",
    goalTags: ["maintenance"],
    mealType: ["breakfast"],
    prepTime: 10,
    cookTime: 40,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 310, proteinG: 6, carbsG: 55, fatG: 7 },
    ingredients: [
      { id: "manipur_breakfast_chak_hao_kheer_black_rice_pudding_black_rice_chak_hao", name: "Black rice (chak-hao)", quantity: 150, unit: "g", category: "grain", searchTerms: { zepto: "black rice", instamart: "black rice" } },
      { id: "manipur_breakfast_chak_hao_kheer_black_rice_pudding_milk", name: "Milk", quantity: 500, unit: "ml", category: "dairy", searchTerms: { zepto: "toned milk", instamart: "milk" } },
      { id: "manipur_breakfast_chak_hao_kheer_black_rice_pudding_sugar", name: "Sugar", quantity: 80, unit: "g", category: "other", searchTerms: { zepto: "sugar", instamart: "sugar" } },
      { id: "manipur_breakfast_chak_hao_kheer_black_rice_pudding_cardamom_powder", name: "Cardamom powder", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "elaichi cardamom powder", instamart: "cardamom powder" }, optional: true },
      { id: "manipur_breakfast_chak_hao_kheer_black_rice_pudding_cashew_nuts", name: "Cashew nuts", quantity: 20, unit: "g", category: "other", searchTerms: { zepto: "cashew nuts", instamart: "cashew" }, optional: true }
    ],
    steps: [
      "Soak the black rice overnight, then drain.",
      "Simmer the rice in milk on low heat, stirring often, until the grains soften and the milk thickens into a pudding, about 35-40 minutes.",
      "Stir in sugar and cardamom powder and cook for a further 5 minutes.",
      "Garnish with cashew nuts and serve warm or chilled."
    ],
    tags: ["sweet", "festive", "antioxidant", "slow-cooked"],
  },
  {
    id: "manipur_lunch_eromba_mashed_vegetable_and_fermented_fish_chutney",
    name: "Eromba (Mashed Vegetable and Fermented Fish Chutney)",
    description: "A rustic Meitei staple of boiled vegetables mashed together with fiery fermented fish (ngari) and chillies, eaten with rice at almost every Manipuri lunch.",
    cuisineRegion: ["Manipur"],
    dietType: "nonveg",
    goalTags: ["maintenance", "weight_loss"],
    mealType: ["lunch"],
    prepTime: 15,
    cookTime: 20,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 260, proteinG: 14, carbsG: 28, fatG: 8 },
    ingredients: [
      { id: "manipur_lunch_eromba_mashed_vegetable_and_fermented_fish_chutney_potato", name: "Potato", quantity: 2, unit: "medium", category: "vegetable", searchTerms: { zepto: "potato", instamart: "potato" } },
      { id: "manipur_lunch_eromba_mashed_vegetable_and_fermented_fish_chutney_pumpkin_or_squash", name: "Pumpkin or squash", quantity: 200, unit: "g", category: "vegetable", searchTerms: { zepto: "pumpkin", instamart: "pumpkin" } },
      { id: "manipur_lunch_eromba_mashed_vegetable_and_fermented_fish_chutney_ngari_fermented_fish", name: "Ngari (fermented fish)", quantity: 30, unit: "g", category: "protein", searchTerms: { zepto: "dried fish", instamart: "dried fish" }, optional: true },
      { id: "manipur_lunch_eromba_mashed_vegetable_and_fermented_fish_chutney_green_chilli", name: "Green chilli", quantity: 4, unit: "piece", category: "vegetable", searchTerms: { zepto: "green chilli", instamart: "green chilli" } },
      { id: "manipur_lunch_eromba_mashed_vegetable_and_fermented_fish_chutney_onion", name: "Onion", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "onion" } },
      { id: "manipur_lunch_eromba_mashed_vegetable_and_fermented_fish_chutney_fermented_bamboo_shoot_so", name: "Fermented bamboo shoot (soibum)", quantity: 30, unit: "g", category: "vegetable", searchTerms: { zepto: "bamboo shoot", instamart: "bamboo shoot" }, optional: true }
    ],
    steps: [
      "Boil the potato and pumpkin (and any other vegetables of choice) until soft.",
      "Roast the ngari lightly wrapped in foil until fragrant, or pan toast a dried fish substitute.",
      "Mash the boiled vegetables coarsely in a bowl.",
      "Mix in the roasted fermented fish, chopped raw onion, chillies and fermented bamboo shoot if using.",
      "Mash everything together by hand until well combined and slightly chunky.",
      "Serve at room temperature with steamed rice."
    ],
    tags: ["fermented", "spicy", "staple", "comfort"],
  },
  {
    id: "manipur_snack_singju_raw_vegetable_salad",
    name: "Singju (Raw Vegetable Salad)",
    description: "A zesty raw salad of shredded vegetables tossed with roasted gram powder, chilli and perilla seeds, Manipur's favourite light snack.",
    cuisineRegion: ["Manipur"],
    dietType: "veg",
    goalTags: ["maintenance", "weight_loss"],
    mealType: ["snack"],
    prepTime: 15,
    cookTime: 5,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 180, proteinG: 6, carbsG: 20, fatG: 8 },
    ingredients: [
      { id: "manipur_snack_singju_raw_vegetable_salad_cabbage", name: "Cabbage", quantity: 200, unit: "g", category: "vegetable", searchTerms: { zepto: "cabbage", instamart: "cabbage" } },
      { id: "manipur_snack_singju_raw_vegetable_salad_raw_papaya_or_banana_flower", name: "Raw papaya or banana flower", quantity: 150, unit: "g", category: "vegetable", searchTerms: { zepto: "raw papaya", instamart: "raw papaya" }, optional: true },
      { id: "manipur_snack_singju_raw_vegetable_salad_roasted_gram_powder_bhuna_besan", name: "Roasted gram powder (bhuna besan)", quantity: 3, unit: "tbsp", category: "protein", searchTerms: { zepto: "roasted chana besan", instamart: "roasted gram powder" } },
      { id: "manipur_snack_singju_raw_vegetable_salad_perilla_seeds", name: "Perilla seeds", quantity: 1, unit: "tbsp", category: "spice", searchTerms: { zepto: "til sesame seeds", instamart: "sesame seeds" }, optional: true },
      { id: "manipur_snack_singju_raw_vegetable_salad_green_chilli", name: "Green chilli", quantity: 2, unit: "piece", category: "vegetable", searchTerms: { zepto: "green chilli", instamart: "green chilli" } },
      { id: "manipur_snack_singju_raw_vegetable_salad_mustard_oil", name: "Mustard oil", quantity: 1, unit: "tbsp", category: "oil", searchTerms: { zepto: "mustard oil", instamart: "mustard oil" } },
      { id: "manipur_snack_singju_raw_vegetable_salad_ngari_fermented_fish", name: "Ngari (fermented fish)", quantity: 15, unit: "g", category: "protein", searchTerms: { zepto: "dried fish", instamart: "dried fish" }, optional: true }
    ],
    steps: [
      "Finely shred the cabbage and raw papaya or banana flower.",
      "Dry roast the perilla seeds and coarsely crush them.",
      "Toss the shredded vegetables with roasted gram powder, crushed perilla seeds, chopped chillies and mustard oil.",
      "Mix in flaked roasted ngari if using, for the authentic fermented note.",
      "Serve immediately as a light, tangy snack."
    ],
    tags: ["raw", "tangy", "healthy", "quick"],
  },
  {
    id: "manipur_dinner_kangshoi_vegetable_stew",
    name: "Kangshoi (Vegetable Stew)",
    description: "A comforting, lightly seasoned Manipuri vegetable broth that typically rounds off the everyday evening meal.",
    cuisineRegion: ["Manipur"],
    dietType: "veg",
    goalTags: ["maintenance", "weight_loss"],
    mealType: ["dinner"],
    prepTime: 10,
    cookTime: 20,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 150, proteinG: 5, carbsG: 20, fatG: 4 },
    ingredients: [
      { id: "manipur_dinner_kangshoi_vegetable_stew_mixed_seasonal_vegetables_pumpkin_beans_squash", name: "Mixed seasonal vegetables (pumpkin, beans, squash)", quantity: 300, unit: "g", category: "vegetable", searchTerms: { zepto: "mixed vegetables", instamart: "mixed vegetables" } },
      { id: "manipur_dinner_kangshoi_vegetable_stew_onion", name: "Onion", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "onion" } },
      { id: "manipur_dinner_kangshoi_vegetable_stew_green_chilli", name: "Green chilli", quantity: 2, unit: "piece", category: "vegetable", searchTerms: { zepto: "green chilli", instamart: "green chilli" } },
      { id: "manipur_dinner_kangshoi_vegetable_stew_ngari_fermented_fish_for_stock", name: "Ngari (fermented fish, for stock)", quantity: 15, unit: "g", category: "protein", searchTerms: { zepto: "dried fish", instamart: "dried fish" }, optional: true },
      { id: "manipur_dinner_kangshoi_vegetable_stew_turmeric_powder", name: "Turmeric powder", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "turmeric powder", instamart: "haldi powder" } }
    ],
    steps: [
      "Bring water to a boil and add turmeric, salt and the ngari if using, for depth of flavour.",
      "Add the chopped mixed vegetables and onion.",
      "Simmer until the vegetables are just tender, keeping the stew light and brothy.",
      "Toss in slit green chillies at the end and simmer for 2 more minutes.",
      "Serve hot alongside steamed rice as the final course of the meal."
    ],
    tags: ["light", "broth", "everyday", "healthy"],
  },
  {
    id: "mizoram_breakfast_sawhchiar_rice_and_meat_porridge",
    name: "Sawhchiar (Rice and Meat Porridge)",
    description: "A warming rice porridge cooked with minced pork or chicken, a classic Mizo breakfast especially on cool mornings and festivals.",
    cuisineRegion: ["Mizoram"],
    dietType: "nonveg",
    goalTags: ["maintenance", "muscle", "recovery"],
    mealType: ["breakfast"],
    prepTime: 15,
    cookTime: 35,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 350, proteinG: 20, carbsG: 45, fatG: 9 },
    ingredients: [
      { id: "mizoram_breakfast_sawhchiar_rice_and_meat_porridge_rice", name: "Rice", quantity: 150, unit: "g", category: "grain", searchTerms: { zepto: "rice", instamart: "rice" } },
      { id: "mizoram_breakfast_sawhchiar_rice_and_meat_porridge_minced_pork_or_chicken", name: "Minced pork or chicken", quantity: 200, unit: "g", category: "protein", searchTerms: { zepto: "chicken keema minced chicken", instamart: "chicken keema" } },
      { id: "mizoram_breakfast_sawhchiar_rice_and_meat_porridge_ginger", name: "Ginger", quantity: 1, unit: "inch", category: "vegetable", searchTerms: { zepto: "ginger", instamart: "ginger" } },
      { id: "mizoram_breakfast_sawhchiar_rice_and_meat_porridge_garlic", name: "Garlic", quantity: 3, unit: "clove", category: "vegetable", searchTerms: { zepto: "garlic", instamart: "garlic" } },
      { id: "mizoram_breakfast_sawhchiar_rice_and_meat_porridge_onion", name: "Onion", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "onion" } },
      { id: "mizoram_breakfast_sawhchiar_rice_and_meat_porridge_spring_onion", name: "Spring onion", quantity: 2, unit: "stalk", category: "vegetable", searchTerms: { zepto: "spring onion", instamart: "spring onion" }, optional: true },
      { id: "mizoram_breakfast_sawhchiar_rice_and_meat_porridge_black_pepper_powder", name: "Black pepper powder", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "black pepper powder", instamart: "black pepper powder" } }
    ],
    steps: [
      "In a pot, sauté chopped onion, ginger and garlic until soft.",
      "Add the minced meat and cook until it changes colour.",
      "Add washed rice and plenty of water, then bring to a boil.",
      "Simmer on low heat, stirring occasionally, until the rice breaks down into a thick porridge, about 30 minutes.",
      "Season with salt and black pepper, top with spring onion, and serve hot in bowls."
    ],
    tags: ["porridge", "comfort", "one-pot", "warming"],
  },
  {
    id: "mizoram_lunch_bai_mizo_vegetable_and_pork_stew",
    name: "Bai (Mizo Vegetable and Pork Stew)",
    description: "Mizoram's everyday one-pot lunch of boiled greens and vegetables simmered with pork fat, deliberately kept low on oil and spice.",
    cuisineRegion: ["Mizoram"],
    dietType: "nonveg",
    goalTags: ["maintenance", "muscle", "recovery"],
    mealType: ["lunch"],
    prepTime: 15,
    cookTime: 25,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 380, proteinG: 22, carbsG: 20, fatG: 22 },
    ingredients: [
      { id: "mizoram_lunch_bai_mizo_vegetable_and_pork_stew_mustard_greens_or_spinach", name: "Mustard greens or spinach", quantity: 250, unit: "g", category: "vegetable", searchTerms: { zepto: "mustard greens sarson saag", instamart: "spinach" } },
      { id: "mizoram_lunch_bai_mizo_vegetable_and_pork_stew_pork_belly_with_fat", name: "Pork belly (with fat)", quantity: 250, unit: "g", category: "protein", searchTerms: { zepto: "pork belly", instamart: "pork" } },
      { id: "mizoram_lunch_bai_mizo_vegetable_and_pork_stew_fermented_bamboo_shoot", name: "Fermented bamboo shoot", quantity: 50, unit: "g", category: "vegetable", searchTerms: { zepto: "bamboo shoot", instamart: "bamboo shoot" }, optional: true },
      { id: "mizoram_lunch_bai_mizo_vegetable_and_pork_stew_bekang_fermented_soybean", name: "Bekang (fermented soybean)", quantity: 20, unit: "g", category: "protein", searchTerms: { zepto: "soybean", instamart: "soybean" }, optional: true },
      { id: "mizoram_lunch_bai_mizo_vegetable_and_pork_stew_green_chilli", name: "Green chilli", quantity: 2, unit: "piece", category: "vegetable", searchTerms: { zepto: "green chilli", instamart: "green chilli" } },
      { id: "mizoram_lunch_bai_mizo_vegetable_and_pork_stew_onion", name: "Onion", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "onion" } }
    ],
    steps: [
      "Boil the pork pieces in a little water until half-cooked.",
      "Add the chopped greens, onion and bamboo shoot if using.",
      "Simmer everything together until the vegetables and pork are fully tender, adding water as needed to keep it stew-like.",
      "Stir in the fermented soybean (bekang) if using, and slit green chillies, in the last few minutes.",
      "Lightly mash some of the vegetables against the side of the pot to thicken, season with salt, and serve with rice."
    ],
    tags: ["boiled", "low-spice", "everyday", "healthy"],
  },
  {
    id: "mizoram_snack_vawksa_rep_smoked_pork_strips",
    name: "Vawksa Rep (Smoked Pork Strips)",
    description: "Strips of pork smoked over a wood fire until dry and intensely flavoured, a favourite Mizo snack eaten plain or pan-seared.",
    cuisineRegion: ["Mizoram"],
    dietType: "nonveg",
    goalTags: ["maintenance", "weight_loss", "muscle", "recovery"],
    mealType: ["snack"],
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 260, proteinG: 24, carbsG: 2, fatG: 17 },
    ingredients: [
      { id: "mizoram_snack_vawksa_rep_smoked_pork_strips_pork_belly_strips", name: "Pork belly strips", quantity: 300, unit: "g", category: "protein", searchTerms: { zepto: "pork belly", instamart: "pork" } },
      { id: "mizoram_snack_vawksa_rep_smoked_pork_strips_salt", name: "Salt", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "salt", instamart: "salt" } },
      { id: "mizoram_snack_vawksa_rep_smoked_pork_strips_black_pepper_powder", name: "Black pepper powder", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "black pepper powder", instamart: "black pepper powder" }, optional: true },
      { id: "mizoram_snack_vawksa_rep_smoked_pork_strips_bird_s_eye_chilli", name: "Bird's eye chilli", quantity: 2, unit: "piece", category: "vegetable", searchTerms: { zepto: "green chilli", instamart: "green chilli" }, optional: true }
    ],
    steps: [
      "Rub the pork strips generously with salt and let them cure for a couple of hours.",
      "Traditionally, hang and smoke the strips over a wood fire for several hours until dry and deep brown; at home, approximate by slow-roasting at low heat until dry and lightly charred.",
      "To serve, pan-sear the smoked strips briefly until hot and slightly crisp at the edges.",
      "Serve as is, or with a side of crushed bird's eye chilli, a popular tea-time bite."
    ],
    tags: ["smoked", "protein-rich", "tribal", "preserved"],
  },
  {
    id: "mizoram_dinner_bekang_um_fermented_soybean_pork_stew",
    name: "Bekang Um (Fermented Soybean Pork Stew)",
    description: "A pungent, deeply savoury Mizo stew built on fermented soybean (bekang) and pork, a favourite dinner comfort dish.",
    cuisineRegion: ["Mizoram"],
    dietType: "nonveg",
    goalTags: ["maintenance", "muscle", "recovery"],
    mealType: ["dinner"],
    prepTime: 10,
    cookTime: 25,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 340, proteinG: 20, carbsG: 12, fatG: 22 },
    ingredients: [
      { id: "mizoram_dinner_bekang_um_fermented_soybean_pork_stew_bekang_fermented_soybean", name: "Bekang (fermented soybean)", quantity: 100, unit: "g", category: "protein", searchTerms: { zepto: "soybean", instamart: "soybean" }, optional: true },
      { id: "mizoram_dinner_bekang_um_fermented_soybean_pork_stew_pork_with_fat", name: "Pork (with fat)", quantity: 250, unit: "g", category: "protein", searchTerms: { zepto: "pork curry cut", instamart: "pork" } },
      { id: "mizoram_dinner_bekang_um_fermented_soybean_pork_stew_onion", name: "Onion", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "onion" } },
      { id: "mizoram_dinner_bekang_um_fermented_soybean_pork_stew_green_chilli", name: "Green chilli", quantity: 2, unit: "piece", category: "vegetable", searchTerms: { zepto: "green chilli", instamart: "green chilli" } },
      { id: "mizoram_dinner_bekang_um_fermented_soybean_pork_stew_ginger", name: "Ginger", quantity: 1, unit: "inch", category: "vegetable", searchTerms: { zepto: "ginger", instamart: "ginger" } },
      { id: "mizoram_dinner_bekang_um_fermented_soybean_pork_stew_tomato", name: "Tomato", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "tomato", instamart: "tomato" }, optional: true }
    ],
    steps: [
      "Boil the pork with ginger and salt until nearly tender.",
      "Add chopped onion and tomato and simmer until softened.",
      "Mash in the fermented soybean (bekang), stirring well to distribute its flavour through the stew.",
      "Simmer for another 8-10 minutes until the stew thickens slightly.",
      "Add slit green chillies, adjust salt, and serve hot with rice."
    ],
    tags: ["fermented", "pungent", "comfort", "tribal"],
  },
  {
    id: "nagaland_breakfast_galho_rice_vegetable_and_smoked_meat_porridge",
    name: "Galho (Rice, Vegetable and Smoked Meat Porridge)",
    description: "A hearty one-pot rice porridge cooked with greens and smoked meat, Nagaland's favourite comforting breakfast or brunch dish.",
    cuisineRegion: ["Nagaland"],
    dietType: "nonveg",
    goalTags: ["maintenance", "muscle", "recovery"],
    mealType: ["breakfast"],
    prepTime: 15,
    cookTime: 30,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 360, proteinG: 20, carbsG: 45, fatG: 10 },
    ingredients: [
      { id: "nagaland_breakfast_galho_rice_vegetable_and_smoked_meat_porridge_rice", name: "Rice", quantity: 150, unit: "g", category: "grain", searchTerms: { zepto: "rice", instamart: "rice" } },
      { id: "nagaland_breakfast_galho_rice_vegetable_and_smoked_meat_porridge_smoked_pork", name: "Smoked pork", quantity: 150, unit: "g", category: "protein", searchTerms: { zepto: "pork", instamart: "pork" } },
      { id: "nagaland_breakfast_galho_rice_vegetable_and_smoked_meat_porridge_mustard_greens_or_spinach", name: "Mustard greens or spinach", quantity: 150, unit: "g", category: "vegetable", searchTerms: { zepto: "mustard greens sarson saag", instamart: "spinach" } },
      { id: "nagaland_breakfast_galho_rice_vegetable_and_smoked_meat_porridge_onion", name: "Onion", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "onion" } },
      { id: "nagaland_breakfast_galho_rice_vegetable_and_smoked_meat_porridge_ginger", name: "Ginger", quantity: 1, unit: "inch", category: "vegetable", searchTerms: { zepto: "ginger", instamart: "ginger" } },
      { id: "nagaland_breakfast_galho_rice_vegetable_and_smoked_meat_porridge_garlic", name: "Garlic", quantity: 3, unit: "clove", category: "vegetable", searchTerms: { zepto: "garlic", instamart: "garlic" } },
      { id: "nagaland_breakfast_galho_rice_vegetable_and_smoked_meat_porridge_bird_s_eye_chilli", name: "Bird's eye chilli", quantity: 2, unit: "piece", category: "vegetable", searchTerms: { zepto: "green chilli", instamart: "green chilli" }, optional: true }
    ],
    steps: [
      "Boil the smoked pork with ginger and garlic until tender, reserving the stock.",
      "Add washed rice to the pork and stock, along with extra water, and bring to a boil.",
      "Simmer, stirring occasionally, until the rice starts breaking down into a thick porridge.",
      "Stir in the chopped greens and onion, and cook until wilted and the porridge is creamy.",
      "Season with salt, top with crushed bird's eye chilli, and serve hot."
    ],
    tags: ["one-pot", "comfort", "porridge", "smoked"],
  },
  {
    id: "nagaland_lunch_smoked_pork_with_bamboo_shoot",
    name: "Smoked Pork with Bamboo Shoot",
    description: "Nagaland's best-known dish - smoky pork slow-cooked with fermented bamboo shoot and dried chillies - the heart of a Naga lunch thali.",
    cuisineRegion: ["Nagaland"],
    dietType: "nonveg",
    goalTags: ["maintenance", "muscle", "recovery", "weight_gain"],
    mealType: ["lunch"],
    prepTime: 15,
    cookTime: 40,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 430, proteinG: 30, carbsG: 10, fatG: 28 },
    ingredients: [
      { id: "nagaland_lunch_smoked_pork_with_bamboo_shoot_smoked_pork", name: "Smoked pork", quantity: 400, unit: "g", category: "protein", searchTerms: { zepto: "pork", instamart: "pork" } },
      { id: "nagaland_lunch_smoked_pork_with_bamboo_shoot_fermented_bamboo_shoot", name: "Fermented bamboo shoot", quantity: 80, unit: "g", category: "vegetable", searchTerms: { zepto: "bamboo shoot", instamart: "bamboo shoot" }, optional: true },
      { id: "nagaland_lunch_smoked_pork_with_bamboo_shoot_dried_red_chilli_or_naga_king_chilli", name: "Dried red chilli (or Naga king chilli)", quantity: 2, unit: "piece", category: "spice", searchTerms: { zepto: "dry red chilli", instamart: "dried red chilli" }, optional: true },
      { id: "nagaland_lunch_smoked_pork_with_bamboo_shoot_ginger", name: "Ginger", quantity: 1, unit: "inch", category: "vegetable", searchTerms: { zepto: "ginger", instamart: "ginger" } },
      { id: "nagaland_lunch_smoked_pork_with_bamboo_shoot_garlic", name: "Garlic", quantity: 4, unit: "clove", category: "vegetable", searchTerms: { zepto: "garlic", instamart: "garlic" } },
      { id: "nagaland_lunch_smoked_pork_with_bamboo_shoot_onion", name: "Onion", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "onion" } },
      { id: "nagaland_lunch_smoked_pork_with_bamboo_shoot_turmeric_powder", name: "Turmeric powder", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "turmeric powder", instamart: "haldi powder" } }
    ],
    steps: [
      "Boil the smoked pork with ginger, garlic and turmeric until nearly tender.",
      "Add sliced onion and the fermented bamboo shoot to the pot.",
      "Simmer everything together on low heat until the pork is fully tender and the flavours meld, about 25 minutes.",
      "Add dried chillies (whole or crushed, to taste) in the last 10 minutes for heat.",
      "Adjust salt and serve hot with steamed rice, traditionally with very little oil."
    ],
    tags: ["smoked", "fermented", "spicy", "tribal", "iconic"],
  },
  {
    id: "nagaland_snack_axone_chutney_fermented_soybean_chutney",
    name: "Axone Chutney (Fermented Soybean Chutney)",
    description: "A pungent, powerful chutney of fermented soybean pounded with chillies and garlic, eaten in small amounts as a side or snack with rice.",
    cuisineRegion: ["Nagaland"],
    dietType: "veg",
    goalTags: ["maintenance", "weight_loss"],
    mealType: ["snack"],
    prepTime: 10,
    cookTime: 10,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 90, proteinG: 6, carbsG: 8, fatG: 4 },
    ingredients: [
      { id: "nagaland_snack_axone_chutney_fermented_soybean_chutney_axone_fermented_soybean_akhuni", name: "Axone (fermented soybean, akhuni)", quantity: 60, unit: "g", category: "protein", searchTerms: { zepto: "soybean", instamart: "soybean" }, optional: true },
      { id: "nagaland_snack_axone_chutney_fermented_soybean_chutney_dried_red_chilli", name: "Dried red chilli", quantity: 3, unit: "piece", category: "spice", searchTerms: { zepto: "dry red chilli", instamart: "dried red chilli" }, optional: true },
      { id: "nagaland_snack_axone_chutney_fermented_soybean_chutney_garlic", name: "Garlic", quantity: 4, unit: "clove", category: "vegetable", searchTerms: { zepto: "garlic", instamart: "garlic" } },
      { id: "nagaland_snack_axone_chutney_fermented_soybean_chutney_ginger", name: "Ginger", quantity: 1, unit: "inch", category: "vegetable", searchTerms: { zepto: "ginger", instamart: "ginger" }, optional: true },
      { id: "nagaland_snack_axone_chutney_fermented_soybean_chutney_mustard_oil", name: "Mustard oil", quantity: 1, unit: "tbsp", category: "oil", searchTerms: { zepto: "mustard oil", instamart: "mustard oil" } }
    ],
    steps: [
      "Lightly roast the axone wrapped in a leaf or foil over low heat until fragrant.",
      "Dry roast the red chillies briefly.",
      "Pound the roasted axone, chillies, garlic and ginger together into a coarse chutney using a mortar and pestle.",
      "Stir in a little mustard oil and salt to bind.",
      "Serve in small portions alongside rice or boiled vegetables as a pungent snack-side."
    ],
    tags: ["fermented", "pungent", "condiment", "tribal"],
  },
  {
    id: "nagaland_dinner_naga_king_chilli_pork",
    name: "Naga King Chilli Pork",
    description: "A fiery pork curry cooked with the world-famous Naga king chilli (bhut jolokia), the showstopper dinner dish of Nagaland.",
    cuisineRegion: ["Nagaland"],
    dietType: "nonveg",
    goalTags: ["maintenance", "muscle", "recovery", "weight_gain"],
    mealType: ["dinner"],
    prepTime: 15,
    cookTime: 35,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 440, proteinG: 28, carbsG: 8, fatG: 30 },
    ingredients: [
      { id: "nagaland_dinner_naga_king_chilli_pork_pork_with_some_fat", name: "Pork (with some fat)", quantity: 400, unit: "g", category: "protein", searchTerms: { zepto: "pork curry cut", instamart: "pork" } },
      { id: "nagaland_dinner_naga_king_chilli_pork_naga_king_chilli_bhut_jolokia", name: "Naga king chilli (bhut jolokia)", quantity: 2, unit: "piece", category: "spice", searchTerms: { zepto: "dry red chilli", instamart: "dried red chilli" }, optional: true },
      { id: "nagaland_dinner_naga_king_chilli_pork_onion", name: "Onion", quantity: 2, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "onion" } },
      { id: "nagaland_dinner_naga_king_chilli_pork_ginger", name: "Ginger", quantity: 1, unit: "inch", category: "vegetable", searchTerms: { zepto: "ginger", instamart: "ginger" } },
      { id: "nagaland_dinner_naga_king_chilli_pork_garlic", name: "Garlic", quantity: 5, unit: "clove", category: "vegetable", searchTerms: { zepto: "garlic", instamart: "garlic" } },
      { id: "nagaland_dinner_naga_king_chilli_pork_tomato", name: "Tomato", quantity: 2, unit: "medium", category: "vegetable", searchTerms: { zepto: "tomato", instamart: "tomato" } },
      { id: "nagaland_dinner_naga_king_chilli_pork_mustard_oil", name: "Mustard oil", quantity: 2, unit: "tbsp", category: "oil", searchTerms: { zepto: "mustard oil", instamart: "mustard oil" } }
    ],
    steps: [
      "Heat mustard oil and sauté onion, ginger and garlic until golden.",
      "Add pork pieces and sear until lightly browned on all sides.",
      "Add chopped tomato and salt, cover, and simmer until the pork is nearly tender.",
      "Crush the Naga king chilli (handle with gloves) and stir into the curry, adjusting the amount to taste for heat.",
      "Simmer uncovered for another 10 minutes until the gravy thickens.",
      "Serve hot with steamed rice, with extra chilli on the side for the brave."
    ],
    tags: ["spicy", "fiery", "iconic", "tribal"],
  },
  {
    id: "tripura_breakfast_mosdeng_mashed_fish_and_vegetable_chutney",
    name: "Mosdeng (Mashed Fish and Vegetable Chutney)",
    description: "A simple raw-mashed chutney of dried fish, chillies and herbs eaten with warm rice, a staple light Tripuri morning meal.",
    cuisineRegion: ["Tripura"],
    dietType: "nonveg",
    goalTags: ["maintenance", "weight_loss"],
    mealType: ["breakfast"],
    prepTime: 15,
    cookTime: 5,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 180, proteinG: 12, carbsG: 10, fatG: 10 },
    ingredients: [
      { id: "tripura_breakfast_mosdeng_mashed_fish_and_vegetable_chutney_dried_fish", name: "Dried fish", quantity: 50, unit: "g", category: "protein", searchTerms: { zepto: "dried fish", instamart: "dried fish" } },
      { id: "tripura_breakfast_mosdeng_mashed_fish_and_vegetable_chutney_onion", name: "Onion", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "onion" } },
      { id: "tripura_breakfast_mosdeng_mashed_fish_and_vegetable_chutney_green_chilli", name: "Green chilli", quantity: 3, unit: "piece", category: "vegetable", searchTerms: { zepto: "green chilli", instamart: "green chilli" } },
      { id: "tripura_breakfast_mosdeng_mashed_fish_and_vegetable_chutney_coriander_leaves", name: "Coriander leaves", quantity: 10, unit: "g", category: "vegetable", searchTerms: { zepto: "coriander leaves", instamart: "coriander" }, optional: true },
      { id: "tripura_breakfast_mosdeng_mashed_fish_and_vegetable_chutney_mustard_oil", name: "Mustard oil", quantity: 1, unit: "tbsp", category: "oil", searchTerms: { zepto: "mustard oil", instamart: "mustard oil" } },
      { id: "tripura_breakfast_mosdeng_mashed_fish_and_vegetable_chutney_lemon", name: "Lemon", quantity: 0.5, unit: "piece", category: "fruit", searchTerms: { zepto: "lemon", instamart: "lemon" }, optional: true }
    ],
    steps: [
      "Roast the dried fish lightly over a flame or in a dry pan until crisp, then flake it.",
      "Finely chop the onion, green chillies and coriander leaves.",
      "Mix everything together with mustard oil, a squeeze of lemon and salt, mashing lightly by hand.",
      "Serve at room temperature with warm steamed rice."
    ],
    tags: ["raw", "spicy", "quick", "staple"],
  },
  {
    id: "tripura_lunch_chakhwi_bamboo_shoot_and_pork_curry",
    name: "Chakhwi (Bamboo Shoot and Pork Curry)",
    description: "A tangy, fragrant Tripuri curry of bamboo shoot simmered with pork and mustard, a beloved everyday lunch dish of the Mui Borok kitchen.",
    cuisineRegion: ["Tripura"],
    dietType: "nonveg",
    goalTags: ["maintenance", "muscle", "recovery", "weight_gain"],
    mealType: ["lunch"],
    prepTime: 15,
    cookTime: 30,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 400, proteinG: 24, carbsG: 14, fatG: 26 },
    ingredients: [
      { id: "tripura_lunch_chakhwi_bamboo_shoot_and_pork_curry_pork", name: "Pork", quantity: 300, unit: "g", category: "protein", searchTerms: { zepto: "pork curry cut", instamart: "pork" } },
      { id: "tripura_lunch_chakhwi_bamboo_shoot_and_pork_curry_bamboo_shoot_fresh_or_fermented", name: "Bamboo shoot (fresh or fermented)", quantity: 150, unit: "g", category: "vegetable", searchTerms: { zepto: "bamboo shoot", instamart: "bamboo shoot" }, optional: true },
      { id: "tripura_lunch_chakhwi_bamboo_shoot_and_pork_curry_mustard_seeds", name: "Mustard seeds", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "rai mustard seeds", instamart: "mustard seeds" } },
      { id: "tripura_lunch_chakhwi_bamboo_shoot_and_pork_curry_turmeric_powder", name: "Turmeric powder", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "turmeric powder", instamart: "haldi powder" } },
      { id: "tripura_lunch_chakhwi_bamboo_shoot_and_pork_curry_garlic", name: "Garlic", quantity: 4, unit: "clove", category: "vegetable", searchTerms: { zepto: "garlic", instamart: "garlic" } },
      { id: "tripura_lunch_chakhwi_bamboo_shoot_and_pork_curry_green_chilli", name: "Green chilli", quantity: 2, unit: "piece", category: "vegetable", searchTerms: { zepto: "green chilli", instamart: "green chilli" } },
      { id: "tripura_lunch_chakhwi_bamboo_shoot_and_pork_curry_mustard_oil", name: "Mustard oil", quantity: 2, unit: "tbsp", category: "oil", searchTerms: { zepto: "mustard oil", instamart: "mustard oil" } }
    ],
    steps: [
      "Heat mustard oil and splutter mustard seeds, then add crushed garlic.",
      "Add pork pieces with turmeric and salt, and sear for a few minutes.",
      "Add the bamboo shoot and enough water to just cover, then cover and simmer until the pork is tender.",
      "Add slit green chillies in the last 5 minutes.",
      "Simmer uncovered briefly to thicken slightly, and serve hot with rice."
    ],
    tags: ["tangy", "fermented", "tribal", "everyday"],
  },
  {
    id: "tripura_snack_muya_bwtwi_bamboo_shoot_fritters",
    name: "Muya Bwtwi (Bamboo Shoot Fritters)",
    description: "Crisp fritters made from tender bamboo shoot and gram flour, a home-style Tripuri tea-time snack approximated from regional bamboo-shoot cooking traditions.",
    cuisineRegion: ["Tripura"],
    dietType: "veg",
    goalTags: ["maintenance", "weight_loss"],
    mealType: ["snack"],
    prepTime: 15,
    cookTime: 15,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 210, proteinG: 6, carbsG: 22, fatG: 11 },
    ingredients: [
      { id: "tripura_snack_muya_bwtwi_bamboo_shoot_fritters_bamboo_shoot_boiled_sliced", name: "Bamboo shoot (boiled, sliced)", quantity: 150, unit: "g", category: "vegetable", searchTerms: { zepto: "bamboo shoot", instamart: "bamboo shoot" }, optional: true },
      { id: "tripura_snack_muya_bwtwi_bamboo_shoot_fritters_gram_flour_besan", name: "Gram flour (besan)", quantity: 100, unit: "g", category: "grain", searchTerms: { zepto: "besan gram flour", instamart: "besan" } },
      { id: "tripura_snack_muya_bwtwi_bamboo_shoot_fritters_rice_flour", name: "Rice flour", quantity: 2, unit: "tbsp", category: "grain", searchTerms: { zepto: "rice flour", instamart: "rice flour" }, optional: true },
      { id: "tripura_snack_muya_bwtwi_bamboo_shoot_fritters_green_chilli", name: "Green chilli", quantity: 2, unit: "piece", category: "vegetable", searchTerms: { zepto: "green chilli", instamart: "green chilli" } },
      { id: "tripura_snack_muya_bwtwi_bamboo_shoot_fritters_turmeric_powder", name: "Turmeric powder", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "turmeric powder", instamart: "haldi powder" } },
      { id: "tripura_snack_muya_bwtwi_bamboo_shoot_fritters_cooking_oil_for_frying", name: "Cooking oil for frying", quantity: 250, unit: "ml", category: "oil", searchTerms: { zepto: "cooking oil", instamart: "refined oil" } }
    ],
    steps: [
      "Boil the bamboo shoot slices until tender, then drain well and pat dry.",
      "Make a thick batter with gram flour, rice flour, turmeric, chopped chilli, salt and a little water.",
      "Dip the bamboo shoot slices in the batter to coat evenly.",
      "Deep fry in hot oil until golden and crisp on both sides.",
      "Drain and serve hot as a crunchy snack."
    ],
    tags: ["fried", "tea-time", "approximated", "crunchy"],
  },
  {
    id: "tripura_dinner_gudok_fermented_fish_and_taro_stew",
    name: "Gudok (Fermented Fish and Taro Stew)",
    description: "A pungent, hearty stew of taro root cooked with fermented fish (berma), a classic warming Tripuri dinner dish.",
    cuisineRegion: ["Tripura"],
    dietType: "nonveg",
    goalTags: ["maintenance"],
    mealType: ["dinner"],
    prepTime: 15,
    cookTime: 30,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 320, proteinG: 18, carbsG: 30, fatG: 12 },
    ingredients: [
      { id: "tripura_dinner_gudok_fermented_fish_and_taro_stew_taro_root_kachu_arbi", name: "Taro root (kachu/arbi)", quantity: 300, unit: "g", category: "vegetable", searchTerms: { zepto: "arbi taro root", instamart: "arbi" } },
      { id: "tripura_dinner_gudok_fermented_fish_and_taro_stew_fermented_fish_berma_shidol", name: "Fermented fish (berma/shidol)", quantity: 40, unit: "g", category: "protein", searchTerms: { zepto: "dried fish", instamart: "dried fish" }, optional: true },
      { id: "tripura_dinner_gudok_fermented_fish_and_taro_stew_onion", name: "Onion", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "onion" } },
      { id: "tripura_dinner_gudok_fermented_fish_and_taro_stew_green_chilli", name: "Green chilli", quantity: 3, unit: "piece", category: "vegetable", searchTerms: { zepto: "green chilli", instamart: "green chilli" } },
      { id: "tripura_dinner_gudok_fermented_fish_and_taro_stew_garlic", name: "Garlic", quantity: 3, unit: "clove", category: "vegetable", searchTerms: { zepto: "garlic", instamart: "garlic" } },
      { id: "tripura_dinner_gudok_fermented_fish_and_taro_stew_mustard_oil", name: "Mustard oil", quantity: 1, unit: "tbsp", category: "oil", searchTerms: { zepto: "mustard oil", instamart: "mustard oil" } }
    ],
    steps: [
      "Peel and cube the taro root, then boil until just tender.",
      "Roast the fermented fish lightly wrapped in foil until fragrant, then flake it.",
      "Heat mustard oil, sauté onion and garlic, then add the flaked fermented fish.",
      "Add the boiled taro along with a little of its cooking water and simmer for 10 minutes until the flavours combine.",
      "Add slit green chillies, adjust salt, and serve hot with rice."
    ],
    tags: ["fermented", "pungent", "hearty", "tribal"],
  },
  {
    id: "arunachal_pradesh_breakfast_thukpa_noodle_soup",
    name: "Thukpa (Noodle Soup)",
    description: "A warming Tibetan-influenced noodle soup with vegetables and meat, a favourite breakfast in the Monpa highlands of Arunachal Pradesh.",
    cuisineRegion: ["Arunachal Pradesh"],
    dietType: "nonveg",
    goalTags: ["maintenance", "muscle", "recovery"],
    mealType: ["breakfast"],
    prepTime: 15,
    cookTime: 20,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 380, proteinG: 20, carbsG: 48, fatG: 11 },
    ingredients: [
      { id: "arunachal_pradesh_breakfast_thukpa_noodle_soup_wheat_noodles", name: "Wheat noodles", quantity: 200, unit: "g", category: "grain", searchTerms: { zepto: "noodles", instamart: "noodles" } },
      { id: "arunachal_pradesh_breakfast_thukpa_noodle_soup_chicken_or_pork_sliced", name: "Chicken or pork, sliced", quantity: 150, unit: "g", category: "protein", searchTerms: { zepto: "chicken", instamart: "chicken" } },
      { id: "arunachal_pradesh_breakfast_thukpa_noodle_soup_carrot", name: "Carrot", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "carrot", instamart: "carrot" } },
      { id: "arunachal_pradesh_breakfast_thukpa_noodle_soup_cabbage", name: "Cabbage", quantity: 100, unit: "g", category: "vegetable", searchTerms: { zepto: "cabbage", instamart: "cabbage" } },
      { id: "arunachal_pradesh_breakfast_thukpa_noodle_soup_garlic", name: "Garlic", quantity: 3, unit: "clove", category: "vegetable", searchTerms: { zepto: "garlic", instamart: "garlic" } },
      { id: "arunachal_pradesh_breakfast_thukpa_noodle_soup_ginger", name: "Ginger", quantity: 1, unit: "inch", category: "vegetable", searchTerms: { zepto: "ginger", instamart: "ginger" } },
      { id: "arunachal_pradesh_breakfast_thukpa_noodle_soup_spring_onion", name: "Spring onion", quantity: 2, unit: "stalk", category: "vegetable", searchTerms: { zepto: "spring onion", instamart: "spring onion" }, optional: true }
    ],
    steps: [
      "Simmer the chicken or pork with ginger and garlic in water to make a light broth.",
      "Add sliced carrot and cabbage and cook until just tender.",
      "Separately, boil the noodles until al dente, then drain.",
      "Add the noodles to the broth and season with salt and pepper.",
      "Ladle into bowls, top with spring onion, and serve piping hot."
    ],
    tags: ["soup", "warming", "himalayan", "comfort"],
  },
  {
    id: "arunachal_pradesh_lunch_zan_fermented_millet_porridge_with_greens",
    name: "Zan (Fermented Millet Porridge with Greens)",
    description: "A traditional Nyishi/Apatani one-pot porridge of millet or maize flour served alongside a fiery fish chutney, a genuine everyday Arunachali lunch (recipe approximated from tribal cooking traditions).",
    cuisineRegion: ["Arunachal Pradesh"],
    dietType: "nonveg",
    goalTags: ["maintenance"],
    mealType: ["lunch"],
    prepTime: 15,
    cookTime: 25,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 340, proteinG: 14, carbsG: 50, fatG: 9 },
    ingredients: [
      { id: "arunachal_pradesh_lunch_zan_fermented_millet_porridge_with_greens_millet_flour_or_maize_fl", name: "Millet flour or maize flour", quantity: 200, unit: "g", category: "grain", searchTerms: { zepto: "millet flour bajra atta", instamart: "bajra atta" } },
      { id: "arunachal_pradesh_lunch_zan_fermented_millet_porridge_with_greens_mustard_greens_or_spinac", name: "Mustard greens or spinach", quantity: 150, unit: "g", category: "vegetable", searchTerms: { zepto: "mustard greens sarson saag", instamart: "spinach" } },
      { id: "arunachal_pradesh_lunch_zan_fermented_millet_porridge_with_greens_dried_or_fermented_fish", name: "Dried or fermented fish", quantity: 30, unit: "g", category: "protein", searchTerms: { zepto: "dried fish", instamart: "dried fish" }, optional: true },
      { id: "arunachal_pradesh_lunch_zan_fermented_millet_porridge_with_greens_green_chilli", name: "Green chilli", quantity: 3, unit: "piece", category: "vegetable", searchTerms: { zepto: "green chilli", instamart: "green chilli" } },
      { id: "arunachal_pradesh_lunch_zan_fermented_millet_porridge_with_greens_garlic", name: "Garlic", quantity: 3, unit: "clove", category: "vegetable", searchTerms: { zepto: "garlic", instamart: "garlic" } },
      { id: "arunachal_pradesh_lunch_zan_fermented_millet_porridge_with_greens_mustard_oil", name: "Mustard oil", quantity: 1, unit: "tbsp", category: "oil", searchTerms: { zepto: "mustard oil", instamart: "mustard oil" } }
    ],
    steps: [
      "Bring water to a boil and gradually whisk in the millet flour to avoid lumps, cooking into a thick porridge.",
      "Stir in the chopped greens and cook until wilted into the porridge.",
      "Separately, pound roasted dried fish with garlic, green chillies and a little mustard oil into a rough chutney.",
      "Season the porridge with salt.",
      "Serve the warm porridge with a spoonful of the fish chutney on the side, mixing to taste as you eat."
    ],
    tags: ["tribal", "staple", "one-pot", "approximated"],
  },
  {
    id: "arunachal_pradesh_snack_momos_steamed_dumplings",
    name: "Momos (Steamed Dumplings)",
    description: "Soft steamed dumplings filled with spiced minced meat, the most popular snack across the Himalayan belt of Arunachal Pradesh.",
    cuisineRegion: ["Arunachal Pradesh"],
    dietType: "nonveg",
    goalTags: ["maintenance", "weight_loss"],
    mealType: ["snack"],
    prepTime: 30,
    cookTime: 20,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 260, proteinG: 14, carbsG: 32, fatG: 8 },
    ingredients: [
      { id: "arunachal_pradesh_snack_momos_steamed_dumplings_all_purpose_flour_maida", name: "All-purpose flour (maida)", quantity: 200, unit: "g", category: "grain", searchTerms: { zepto: "maida all purpose flour", instamart: "all purpose flour" } },
      { id: "arunachal_pradesh_snack_momos_steamed_dumplings_minced_chicken_or_pork", name: "Minced chicken or pork", quantity: 200, unit: "g", category: "protein", searchTerms: { zepto: "chicken keema minced chicken", instamart: "chicken keema" } },
      { id: "arunachal_pradesh_snack_momos_steamed_dumplings_cabbage_finely_chopped", name: "Cabbage, finely chopped", quantity: 100, unit: "g", category: "vegetable", searchTerms: { zepto: "cabbage", instamart: "cabbage" } },
      { id: "arunachal_pradesh_snack_momos_steamed_dumplings_onion", name: "Onion", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "onion" } },
      { id: "arunachal_pradesh_snack_momos_steamed_dumplings_ginger_garlic_paste", name: "Ginger-garlic paste", quantity: 1, unit: "tbsp", category: "vegetable", searchTerms: { zepto: "ginger garlic paste", instamart: "ginger garlic paste" } },
      { id: "arunachal_pradesh_snack_momos_steamed_dumplings_soy_sauce", name: "Soy sauce", quantity: 1, unit: "tbsp", category: "other", searchTerms: { zepto: "soy sauce", instamart: "soy sauce" }, optional: true }
    ],
    steps: [
      "Knead the flour with water into a smooth, firm dough and rest for 20 minutes.",
      "Mix the minced meat with chopped cabbage, onion, ginger-garlic paste, soy sauce and salt.",
      "Roll the dough into small thin circles and place a spoonful of filling in the centre of each.",
      "Pleat and seal the edges to form dumplings.",
      "Steam for 12-15 minutes until the wrappers turn translucent.",
      "Serve hot with a chilli dipping sauce."
    ],
    tags: ["steamed", "himalayan", "popular", "dumplings"],
  },
  {
    id: "arunachal_pradesh_dinner_pika_pila_pork_with_fermented_bamboo_shoot_and_mustard_",
    name: "Pika Pila (Pork with Fermented Bamboo Shoot and Mustard Oil)",
    description: "An Adi-tribe specialty of pork cooked in generous mustard oil with pungent fermented bamboo shoot, a distinctive Arunachali dinner dish.",
    cuisineRegion: ["Arunachal Pradesh"],
    dietType: "nonveg",
    goalTags: ["maintenance", "muscle", "recovery", "weight_gain"],
    mealType: ["dinner"],
    prepTime: 15,
    cookTime: 35,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 450, proteinG: 26, carbsG: 8, fatG: 32 },
    ingredients: [
      { id: "arunachal_pradesh_dinner_pika_pila_pork_with_fermented_bamboo_shoot_and_mustard__pork_with", name: "Pork (with fat)", quantity: 400, unit: "g", category: "protein", searchTerms: { zepto: "pork curry cut", instamart: "pork" } },
      { id: "arunachal_pradesh_dinner_pika_pila_pork_with_fermented_bamboo_shoot_and_mustard__fermented", name: "Fermented bamboo shoot", quantity: 100, unit: "g", category: "vegetable", searchTerms: { zepto: "bamboo shoot", instamart: "bamboo shoot" }, optional: true },
      { id: "arunachal_pradesh_dinner_pika_pila_pork_with_fermented_bamboo_shoot_and_mustard__mustard_o", name: "Mustard oil", quantity: 4, unit: "tbsp", category: "oil", searchTerms: { zepto: "mustard oil", instamart: "mustard oil" } },
      { id: "arunachal_pradesh_dinner_pika_pila_pork_with_fermented_bamboo_shoot_and_mustard__green_chi", name: "Green chilli", quantity: 3, unit: "piece", category: "vegetable", searchTerms: { zepto: "green chilli", instamart: "green chilli" } },
      { id: "arunachal_pradesh_dinner_pika_pila_pork_with_fermented_bamboo_shoot_and_mustard__garlic", name: "Garlic", quantity: 4, unit: "clove", category: "vegetable", searchTerms: { zepto: "garlic", instamart: "garlic" } },
      { id: "arunachal_pradesh_dinner_pika_pila_pork_with_fermented_bamboo_shoot_and_mustard__ginger", name: "Ginger", quantity: 1, unit: "inch", category: "vegetable", searchTerms: { zepto: "ginger", instamart: "ginger" } }
    ],
    steps: [
      "Heat a generous amount of mustard oil until it just smokes, then let it cool slightly, a traditional Adi technique for flavour.",
      "Sauté garlic and ginger, then add the pork pieces and sear well.",
      "Add the fermented bamboo shoot and a splash of water, cover, and simmer until the pork is tender.",
      "Add slit green chillies and cook uncovered for a final 5 minutes so the oil separates slightly.",
      "Serve hot with rice, letting the mustard oil flavour come through strongly."
    ],
    tags: ["tribal", "pungent", "fermented", "iconic"],
  },
  {
    id: "sikkim_breakfast_sel_roti_sweet_rice_ring_bread",
    name: "Sel Roti (Sweet Rice Ring Bread)",
    description: "A crisp, golden ring-shaped fried bread made from fermented rice batter, a festive and everyday Sikkimese breakfast favourite.",
    cuisineRegion: ["Sikkim"],
    dietType: "veg",
    goalTags: ["maintenance", "weight_loss"],
    mealType: ["breakfast"],
    prepTime: 20,
    cookTime: 20,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 290, proteinG: 4, carbsG: 45, fatG: 11 },
    ingredients: [
      { id: "sikkim_breakfast_sel_roti_sweet_rice_ring_bread_rice_soaked_and_ground", name: "Rice (soaked and ground)", quantity: 250, unit: "g", category: "grain", searchTerms: { zepto: "rice", instamart: "rice" } },
      { id: "sikkim_breakfast_sel_roti_sweet_rice_ring_bread_sugar", name: "Sugar", quantity: 60, unit: "g", category: "other", searchTerms: { zepto: "sugar", instamart: "sugar" } },
      { id: "sikkim_breakfast_sel_roti_sweet_rice_ring_bread_milk", name: "Milk", quantity: 100, unit: "ml", category: "dairy", searchTerms: { zepto: "toned milk", instamart: "milk" }, optional: true },
      { id: "sikkim_breakfast_sel_roti_sweet_rice_ring_bread_ghee", name: "Ghee", quantity: 1, unit: "tbsp", category: "dairy", searchTerms: { zepto: "ghee", instamart: "ghee" }, optional: true },
      { id: "sikkim_breakfast_sel_roti_sweet_rice_ring_bread_cardamom_powder", name: "Cardamom powder", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "elaichi cardamom powder", instamart: "cardamom powder" }, optional: true },
      { id: "sikkim_breakfast_sel_roti_sweet_rice_ring_bread_cooking_oil_for_deep_frying", name: "Cooking oil for deep frying", quantity: 300, unit: "ml", category: "oil", searchTerms: { zepto: "cooking oil", instamart: "refined oil" } }
    ],
    steps: [
      "Soak rice for several hours, then grind to a smooth, slightly thick batter, allowing it to ferment lightly for a few hours if time permits.",
      "Mix in sugar, milk, ghee and cardamom powder until well combined.",
      "Heat oil in a kadai and pour the batter in a circular ring motion directly into the hot oil to form a ring shape.",
      "Fry until golden brown and crisp on both sides, then drain.",
      "Serve warm, on their own or with tea."
    ],
    tags: ["fried", "sweet", "festive", "rice-based"],
  },
  {
    id: "sikkim_lunch_gundruk_ko_jhol_fermented_leafy_greens_soup",
    name: "Gundruk ko Jhol (Fermented Leafy Greens Soup)",
    description: "A sour, tangy soup made from sun-dried fermented leafy greens, a distinctly Sikkimese-Nepali lunch dish valued for its tang and shelf-stable base.",
    cuisineRegion: ["Sikkim"],
    dietType: "veg",
    goalTags: ["maintenance", "weight_loss"],
    mealType: ["lunch"],
    prepTime: 10,
    cookTime: 20,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 150, proteinG: 6, carbsG: 16, fatG: 6 },
    ingredients: [
      { id: "sikkim_lunch_gundruk_ko_jhol_fermented_leafy_greens_soup_gundruk_fermented_dried_leafy_gre", name: "Gundruk (fermented dried leafy greens)", quantity: 50, unit: "g", category: "vegetable", searchTerms: { zepto: "dried spinach", instamart: "spinach" }, optional: true },
      { id: "sikkim_lunch_gundruk_ko_jhol_fermented_leafy_greens_soup_potato", name: "Potato", quantity: 2, unit: "medium", category: "vegetable", searchTerms: { zepto: "potato", instamart: "potato" } },
      { id: "sikkim_lunch_gundruk_ko_jhol_fermented_leafy_greens_soup_tomato", name: "Tomato", quantity: 2, unit: "medium", category: "vegetable", searchTerms: { zepto: "tomato", instamart: "tomato" } },
      { id: "sikkim_lunch_gundruk_ko_jhol_fermented_leafy_greens_soup_garlic", name: "Garlic", quantity: 3, unit: "clove", category: "vegetable", searchTerms: { zepto: "garlic", instamart: "garlic" } },
      { id: "sikkim_lunch_gundruk_ko_jhol_fermented_leafy_greens_soup_cumin_seeds", name: "Cumin seeds", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "jeera cumin seeds", instamart: "cumin seeds" } },
      { id: "sikkim_lunch_gundruk_ko_jhol_fermented_leafy_greens_soup_mustard_oil", name: "Mustard oil", quantity: 1, unit: "tbsp", category: "oil", searchTerms: { zepto: "mustard oil", instamart: "mustard oil" } }
    ],
    steps: [
      "Soak the gundruk briefly in warm water to soften, then roughly chop it.",
      "Heat mustard oil and temper cumin seeds and garlic until fragrant.",
      "Add chopped tomato and cook until pulpy.",
      "Add cubed potato, the softened gundruk, and enough water to make a soupy consistency.",
      "Simmer until the potatoes are cooked through and the soup turns pleasantly sour.",
      "Season with salt and serve hot with rice."
    ],
    tags: ["fermented", "tangy", "healthy", "everyday"],
  },
  {
    id: "sikkim_snack_momos_steamed_dumplings_sikkimese_style",
    name: "Momos (Steamed Dumplings, Sikkimese-style)",
    description: "Delicate steamed dumplings, arguably Sikkim's most beloved snack, served with a fiery tomato-sesame chutney.",
    cuisineRegion: ["Sikkim"],
    dietType: "veg",
    goalTags: ["maintenance", "weight_loss"],
    mealType: ["snack"],
    prepTime: 30,
    cookTime: 20,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 240, proteinG: 9, carbsG: 34, fatG: 7 },
    ingredients: [
      { id: "sikkim_snack_momos_steamed_dumplings_sikkimese_style_all_purpose_flour_maida", name: "All-purpose flour (maida)", quantity: 200, unit: "g", category: "grain", searchTerms: { zepto: "maida all purpose flour", instamart: "all purpose flour" } },
      { id: "sikkim_snack_momos_steamed_dumplings_sikkimese_style_mixed_vegetables_cabbage_carrot_or_pa", name: "Mixed vegetables (cabbage, carrot) or paneer", quantity: 250, unit: "g", category: "vegetable", searchTerms: { zepto: "cabbage carrot mixed vegetables", instamart: "mixed vegetables" } },
      { id: "sikkim_snack_momos_steamed_dumplings_sikkimese_style_onion", name: "Onion", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "onion" } },
      { id: "sikkim_snack_momos_steamed_dumplings_sikkimese_style_ginger_garlic_paste", name: "Ginger-garlic paste", quantity: 1, unit: "tbsp", category: "vegetable", searchTerms: { zepto: "ginger garlic paste", instamart: "ginger garlic paste" } },
      { id: "sikkim_snack_momos_steamed_dumplings_sikkimese_style_tomato_for_chutney", name: "Tomato (for chutney)", quantity: 2, unit: "medium", category: "vegetable", searchTerms: { zepto: "tomato", instamart: "tomato" } },
      { id: "sikkim_snack_momos_steamed_dumplings_sikkimese_style_sesame_seeds_for_chutney", name: "Sesame seeds (for chutney)", quantity: 1, unit: "tbsp", category: "other", searchTerms: { zepto: "til sesame seeds", instamart: "sesame seeds" }, optional: true }
    ],
    steps: [
      "Knead the flour with water into a smooth dough and rest for 20 minutes.",
      "Finely chop or grate the vegetables (or crumble paneer) and mix with onion, ginger-garlic paste and salt.",
      "Roll small dough circles, fill with the vegetable mixture, and pleat closed.",
      "Steam for 12-15 minutes until translucent.",
      "For the chutney, roast tomatoes and sesame seeds, then blend with chilli and salt.",
      "Serve the hot momos with the tomato-sesame chutney."
    ],
    tags: ["steamed", "popular", "himalayan", "dumplings"],
  },
  {
    id: "sikkim_dinner_thukpa_hearty_noodle_soup",
    name: "Thukpa (Hearty Noodle Soup)",
    description: "A filling brothy noodle soup loaded with vegetables and meat, the classic cold-weather Sikkimese dinner.",
    cuisineRegion: ["Sikkim"],
    dietType: "nonveg",
    goalTags: ["maintenance", "muscle", "recovery"],
    mealType: ["dinner"],
    prepTime: 15,
    cookTime: 25,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 420, proteinG: 24, carbsG: 50, fatG: 12 },
    ingredients: [
      { id: "sikkim_dinner_thukpa_hearty_noodle_soup_wheat_noodles", name: "Wheat noodles", quantity: 200, unit: "g", category: "grain", searchTerms: { zepto: "noodles", instamart: "noodles" } },
      { id: "sikkim_dinner_thukpa_hearty_noodle_soup_chicken_sliced", name: "Chicken, sliced", quantity: 200, unit: "g", category: "protein", searchTerms: { zepto: "chicken", instamart: "chicken" } },
      { id: "sikkim_dinner_thukpa_hearty_noodle_soup_cabbage", name: "Cabbage", quantity: 100, unit: "g", category: "vegetable", searchTerms: { zepto: "cabbage", instamart: "cabbage" } },
      { id: "sikkim_dinner_thukpa_hearty_noodle_soup_carrot", name: "Carrot", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "carrot", instamart: "carrot" } },
      { id: "sikkim_dinner_thukpa_hearty_noodle_soup_tomato", name: "Tomato", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "tomato", instamart: "tomato" } },
      { id: "sikkim_dinner_thukpa_hearty_noodle_soup_garlic", name: "Garlic", quantity: 3, unit: "clove", category: "vegetable", searchTerms: { zepto: "garlic", instamart: "garlic" } },
      { id: "sikkim_dinner_thukpa_hearty_noodle_soup_spring_onion", name: "Spring onion", quantity: 2, unit: "stalk", category: "vegetable", searchTerms: { zepto: "spring onion", instamart: "spring onion" }, optional: true }
    ],
    steps: [
      "Make a broth by simmering chicken pieces with garlic in water for 15 minutes.",
      "Add chopped tomato, carrot and cabbage, and cook until tender.",
      "Boil the noodles separately until al dente and drain.",
      "Combine the noodles with the broth and vegetables, and season with salt and pepper.",
      "Simmer for 2-3 minutes to let the flavours meld.",
      "Garnish with spring onion and serve hot in deep bowls."
    ],
    tags: ["soup", "warming", "himalayan", "hearty"],
  },
];
