import type { Recipe } from "../types";

// Auto-generated from regional recipe research (North zone).
export const NORTH_RECIPES: Recipe[] = [
  {
    id: "punjab_breakfast_aloo_paratha",
    name: "Aloo Paratha",
    description: "Whole wheat flatbread stuffed with spiced mashed potatoes, pan-fried in ghee and served with curd and pickle.",
    cuisineRegion: ["Punjab"],
    dietType: "veg",
    goalTags: ["maintenance", "weight_gain"],
    mealType: ["breakfast"],
    prepTime: 20,
    cookTime: 20,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 520, proteinG: 12, carbsG: 78, fatG: 18 },
    ingredients: [
      { id: "punjab_breakfast_aloo_paratha_whole_wheat_flour", name: "Whole wheat flour", quantity: 300, unit: "g", category: "grain", searchTerms: { zepto: "wheat flour atta", instamart: "atta" } },
      { id: "punjab_breakfast_aloo_paratha_potato", name: "Potato", quantity: 3, unit: "medium", category: "vegetable", searchTerms: { zepto: "potato", instamart: "aloo" } },
      { id: "punjab_breakfast_aloo_paratha_onion", name: "Onion", quantity: 1, unit: "small", category: "vegetable", searchTerms: { zepto: "onion", instamart: "pyaz" }, optional: true },
      { id: "punjab_breakfast_aloo_paratha_green_chili", name: "Green chili", quantity: 2, unit: "piece", category: "spice", searchTerms: { zepto: "green chilli", instamart: "hari mirch" }, optional: true },
      { id: "punjab_breakfast_aloo_paratha_coriander_leaves", name: "Coriander leaves", quantity: 20, unit: "g", category: "vegetable", searchTerms: { zepto: "coriander leaves", instamart: "dhania patta" }, optional: true },
      { id: "punjab_breakfast_aloo_paratha_ajwain_carom_seeds", name: "Ajwain (carom seeds)", quantity: 0.5, unit: "tsp", category: "spice", searchTerms: { zepto: "carom seeds ajwain", instamart: "ajwain" }, optional: true },
      { id: "punjab_breakfast_aloo_paratha_red_chili_powder", name: "Red chili powder", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "red chilli powder", instamart: "lal mirch powder" } },
      { id: "punjab_breakfast_aloo_paratha_ghee", name: "Ghee", quantity: 3, unit: "tbsp", category: "oil", searchTerms: { zepto: "ghee", instamart: "desi ghee" } },
      { id: "punjab_breakfast_aloo_paratha_curd", name: "Curd", quantity: 200, unit: "g", category: "dairy", searchTerms: { zepto: "curd fresh", instamart: "dahi" } },
      { id: "punjab_breakfast_aloo_paratha_salt", name: "Salt", quantity: 1, unit: "tsp", category: "other", searchTerms: { zepto: "iodised salt", instamart: "namak" } }
    ],
    steps: [
      "Boil potatoes, peel and mash them well; mix in chopped onion, green chili, coriander, ajwain, chili powder and salt.",
      "Knead the wheat flour with water into a soft dough and rest for 10 minutes.",
      "Divide dough into balls, stuff each with the potato filling, seal and roll gently into a paratha.",
      "Cook on a hot tawa, applying ghee on both sides until golden brown spots appear.",
      "Serve hot with curd and pickle."
    ],
    tags: ["breakfast staple", "comfort food", "stuffed bread"],
  },
  {
    id: "punjab_lunch_rajma_chawal",
    name: "Rajma Chawal",
    description: "Slow-cooked kidney beans in a spiced onion-tomato gravy served over steamed basmati rice.",
    cuisineRegion: ["Punjab"],
    dietType: "veg",
    goalTags: ["maintenance"],
    mealType: ["lunch"],
    prepTime: 15,
    cookTime: 40,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 480, proteinG: 18, carbsG: 75, fatG: 10 },
    ingredients: [
      { id: "punjab_lunch_rajma_chawal_rajma_kidney_beans", name: "Rajma (kidney beans)", quantity: 200, unit: "g", category: "protein", searchTerms: { zepto: "kidney beans rajma", instamart: "rajma" } },
      { id: "punjab_lunch_rajma_chawal_basmati_rice", name: "Basmati rice", quantity: 200, unit: "g", category: "grain", searchTerms: { zepto: "basmati rice", instamart: "chawal" } },
      { id: "punjab_lunch_rajma_chawal_onion", name: "Onion", quantity: 2, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "pyaz" } },
      { id: "punjab_lunch_rajma_chawal_tomato", name: "Tomato", quantity: 3, unit: "medium", category: "vegetable", searchTerms: { zepto: "tomato", instamart: "tamatar" } },
      { id: "punjab_lunch_rajma_chawal_ginger_garlic_paste", name: "Ginger-garlic paste", quantity: 1, unit: "tbsp", category: "spice", searchTerms: { zepto: "ginger garlic paste", instamart: "adrak lehsun paste" } },
      { id: "punjab_lunch_rajma_chawal_cumin_seeds", name: "Cumin seeds", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "cumin seeds jeera", instamart: "jeera" }, optional: true },
      { id: "punjab_lunch_rajma_chawal_bay_leaf", name: "Bay leaf", quantity: 1, unit: "piece", category: "spice", searchTerms: { zepto: "bay leaf tej patta", instamart: "tej patta" }, optional: true },
      { id: "punjab_lunch_rajma_chawal_garam_masala", name: "Garam masala", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "garam masala", instamart: "garam masala" } },
      { id: "punjab_lunch_rajma_chawal_red_chili_powder", name: "Red chili powder", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "red chilli powder", instamart: "lal mirch powder" } },
      { id: "punjab_lunch_rajma_chawal_oil", name: "Oil", quantity: 2, unit: "tbsp", category: "oil", searchTerms: { zepto: "refined sunflower oil", instamart: "khana pakane ka tel" } }
    ],
    steps: [
      "Soak rajma overnight, then pressure cook with salt until soft.",
      "Heat oil, splutter cumin and bay leaf, add onions and sauté until golden.",
      "Add ginger-garlic paste, tomatoes, and spices; cook until the masala releases oil.",
      "Add the boiled rajma along with its stock, simmer for 15-20 minutes until thick and creamy.",
      "Serve hot with steamed basmati rice."
    ],
    tags: ["comfort food", "protein-rich", "one-pot"],
  },
  {
    id: "punjab_snack_amritsari_chole_kulcha",
    name: "Amritsari Chole Kulcha",
    description: "Spicy chickpea curry served with soft leavened flatbread, a beloved Punjabi street-food snack.",
    cuisineRegion: ["Punjab"],
    dietType: "veg",
    goalTags: ["maintenance"],
    mealType: ["snack"],
    prepTime: 20,
    cookTime: 30,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 450, proteinG: 14, carbsG: 68, fatG: 12 },
    ingredients: [
      { id: "punjab_snack_amritsari_chole_kulcha_chickpeas_kabuli_chana", name: "Chickpeas (kabuli chana)", quantity: 200, unit: "g", category: "protein", searchTerms: { zepto: "kabuli chana chickpeas", instamart: "kabuli chana" } },
      { id: "punjab_snack_amritsari_chole_kulcha_refined_flour_maida", name: "Refined flour (maida)", quantity: 250, unit: "g", category: "grain", searchTerms: { zepto: "refined flour maida", instamart: "maida" } },
      { id: "punjab_snack_amritsari_chole_kulcha_yogurt", name: "Yogurt", quantity: 2, unit: "tbsp", category: "dairy", searchTerms: { zepto: "curd fresh", instamart: "dahi" } },
      { id: "punjab_snack_amritsari_chole_kulcha_baking_powder", name: "Baking powder", quantity: 0.5, unit: "tsp", category: "other", searchTerms: { zepto: "baking powder", instamart: "baking powder" }, optional: true },
      { id: "punjab_snack_amritsari_chole_kulcha_onion", name: "Onion", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "pyaz" } },
      { id: "punjab_snack_amritsari_chole_kulcha_tomato", name: "Tomato", quantity: 2, unit: "medium", category: "vegetable", searchTerms: { zepto: "tomato", instamart: "tamatar" } },
      { id: "punjab_snack_amritsari_chole_kulcha_tea_leaves", name: "Tea leaves", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "loose tea leaves", instamart: "chai patti" }, optional: true },
      { id: "punjab_snack_amritsari_chole_kulcha_chole_masala", name: "Chole masala", quantity: 1.5, unit: "tbsp", category: "spice", searchTerms: { zepto: "chole masala", instamart: "chole masala" } },
      { id: "punjab_snack_amritsari_chole_kulcha_ginger", name: "Ginger", quantity: 1, unit: "inch", category: "spice", searchTerms: { zepto: "ginger", instamart: "adrak" }, optional: true },
      { id: "punjab_snack_amritsari_chole_kulcha_butter", name: "Butter", quantity: 1, unit: "tbsp", category: "dairy", searchTerms: { zepto: "butter", instamart: "makhan" }, optional: true }
    ],
    steps: [
      "Soak chickpeas overnight and pressure cook with a tea bag (for dark colour) until soft.",
      "Knead maida with yogurt, baking powder and water into a soft dough; rest for 2 hours.",
      "Sauté onion, ginger and tomato with chole masala, then add the boiled chickpeas and simmer until thick.",
      "Roll out dough into ovals and cook kulchas on a hot tawa or in a tandoor until puffed and charred.",
      "Brush kulchas with butter and serve hot alongside the chole."
    ],
    tags: ["street food", "spicy", "popular"],
  },
  {
    id: "punjab_dinner_sarson_da_saag_with_makki_di_roti",
    name: "Sarson da Saag with Makki di Roti",
    description: "Slow-cooked mustard and spinach greens mashed together, served with hand-rolled maize flatbread and a dollop of white butter.",
    cuisineRegion: ["Punjab"],
    dietType: "veg",
    goalTags: ["maintenance"],
    mealType: ["dinner"],
    prepTime: 20,
    cookTime: 45,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 420, proteinG: 11, carbsG: 52, fatG: 18 },
    ingredients: [
      { id: "punjab_dinner_sarson_da_saag_with_makki_di_roti_mustard_greens_sarson", name: "Mustard greens (sarson)", quantity: 400, unit: "g", category: "vegetable", searchTerms: { zepto: "mustard greens sarson saag", instamart: "sarson saag" } },
      { id: "punjab_dinner_sarson_da_saag_with_makki_di_roti_spinach", name: "Spinach", quantity: 150, unit: "g", category: "vegetable", searchTerms: { zepto: "spinach palak", instamart: "palak" }, optional: true },
      { id: "punjab_dinner_sarson_da_saag_with_makki_di_roti_bathua_leaves", name: "Bathua leaves", quantity: 100, unit: "g", category: "vegetable", searchTerms: { zepto: "bathua leaves", instamart: "bathua" }, optional: true },
      { id: "punjab_dinner_sarson_da_saag_with_makki_di_roti_maize_flour_makki_atta", name: "Maize flour (makki atta)", quantity: 250, unit: "g", category: "grain", searchTerms: { zepto: "maize flour makki atta", instamart: "makki atta" } },
      { id: "punjab_dinner_sarson_da_saag_with_makki_di_roti_green_chili", name: "Green chili", quantity: 2, unit: "piece", category: "spice", searchTerms: { zepto: "green chilli", instamart: "hari mirch" }, optional: true },
      { id: "punjab_dinner_sarson_da_saag_with_makki_di_roti_ginger_garlic_paste", name: "Ginger-garlic paste", quantity: 1, unit: "tbsp", category: "spice", searchTerms: { zepto: "ginger garlic paste", instamart: "adrak lehsun paste" } },
      { id: "punjab_dinner_sarson_da_saag_with_makki_di_roti_maize_flour_for_binding_saag", name: "Maize flour (for binding saag)", quantity: 2, unit: "tbsp", category: "grain", searchTerms: { zepto: "maize flour makki atta", instamart: "makki atta" }, optional: true },
      { id: "punjab_dinner_sarson_da_saag_with_makki_di_roti_white_butter_makhan", name: "White butter (makhan)", quantity: 2, unit: "tbsp", category: "dairy", searchTerms: { zepto: "white butter makhan", instamart: "makhan" } },
      { id: "punjab_dinner_sarson_da_saag_with_makki_di_roti_onion", name: "Onion", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "pyaz" } }
    ],
    steps: [
      "Boil mustard greens, spinach and bathua together until soft, then blend coarsely.",
      "Heat butter, sauté onion, ginger-garlic paste and green chili, then add the greens back in.",
      "Stir in a little makki flour to thicken, simmer for 20 minutes, mashing occasionally.",
      "Knead makki atta with warm water and pat into rotis; cook on a hot tawa with ghee until crisp.",
      "Serve the saag hot topped with white butter alongside makki di roti."
    ],
    tags: ["winter special", "greens", "traditional"],
  },
  {
    id: "haryana_breakfast_bajra_khichdi",
    name: "Bajra Khichdi",
    description: "A comforting one-pot pearl millet and moong dal khichdi tempered with cumin and ghee, a winter breakfast staple in Haryana.",
    cuisineRegion: ["Haryana"],
    dietType: "veg",
    goalTags: ["maintenance"],
    mealType: ["breakfast"],
    prepTime: 10,
    cookTime: 30,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 380, proteinG: 12, carbsG: 60, fatG: 10 },
    ingredients: [
      { id: "haryana_breakfast_bajra_khichdi_bajra_pearl_millet", name: "Bajra (pearl millet)", quantity: 150, unit: "g", category: "grain", searchTerms: { zepto: "pearl millet bajra", instamart: "bajra" } },
      { id: "haryana_breakfast_bajra_khichdi_moong_dal", name: "Moong dal", quantity: 80, unit: "g", category: "protein", searchTerms: { zepto: "yellow moong dal", instamart: "moong dal" } },
      { id: "haryana_breakfast_bajra_khichdi_ghee", name: "Ghee", quantity: 2, unit: "tbsp", category: "oil", searchTerms: { zepto: "ghee", instamart: "desi ghee" } },
      { id: "haryana_breakfast_bajra_khichdi_cumin_seeds", name: "Cumin seeds", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "cumin seeds jeera", instamart: "jeera" }, optional: true },
      { id: "haryana_breakfast_bajra_khichdi_turmeric_powder", name: "Turmeric powder", quantity: 0.5, unit: "tsp", category: "spice", searchTerms: { zepto: "turmeric powder haldi", instamart: "haldi" } },
      { id: "haryana_breakfast_bajra_khichdi_buttermilk_chaas", name: "Buttermilk (chaas)", quantity: 300, unit: "ml", category: "dairy", searchTerms: { zepto: "buttermilk chaas", instamart: "chaas" } },
      { id: "haryana_breakfast_bajra_khichdi_salt", name: "Salt", quantity: 1, unit: "tsp", category: "other", searchTerms: { zepto: "iodised salt", instamart: "namak" } },
      { id: "haryana_breakfast_bajra_khichdi_green_chili", name: "Green chili", quantity: 1, unit: "piece", category: "spice", searchTerms: { zepto: "green chilli", instamart: "hari mirch" }, optional: true }
    ],
    steps: [
      "Wash and soak bajra and moong dal together for 30 minutes.",
      "Pressure cook bajra, dal, turmeric and salt with water until soft and mushy.",
      "Heat ghee in a small pan, splutter cumin seeds and green chili, and pour over the khichdi.",
      "Serve hot with a glass of chilled buttermilk."
    ],
    tags: ["winter", "one-pot", "wholesome"],
  },
  {
    id: "haryana_lunch_kadhi_pakora_with_rice",
    name: "Kadhi Pakora with Rice",
    description: "Tangy yogurt-gram flour curry studded with crisp onion fritters, served over steamed rice.",
    cuisineRegion: ["Haryana"],
    dietType: "veg",
    goalTags: ["maintenance"],
    mealType: ["lunch"],
    prepTime: 20,
    cookTime: 35,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 460, proteinG: 14, carbsG: 62, fatG: 16 },
    ingredients: [
      { id: "haryana_lunch_kadhi_pakora_with_rice_yogurt", name: "Yogurt", quantity: 400, unit: "g", category: "dairy", searchTerms: { zepto: "curd fresh", instamart: "dahi" } },
      { id: "haryana_lunch_kadhi_pakora_with_rice_gram_flour_besan", name: "Gram flour (besan)", quantity: 100, unit: "g", category: "grain", searchTerms: { zepto: "gram flour besan", instamart: "besan" } },
      { id: "haryana_lunch_kadhi_pakora_with_rice_onion", name: "Onion", quantity: 2, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "pyaz" } },
      { id: "haryana_lunch_kadhi_pakora_with_rice_rice", name: "Rice", quantity: 200, unit: "g", category: "grain", searchTerms: { zepto: "basmati rice", instamart: "chawal" } },
      { id: "haryana_lunch_kadhi_pakora_with_rice_turmeric_powder", name: "Turmeric powder", quantity: 0.5, unit: "tsp", category: "spice", searchTerms: { zepto: "turmeric powder haldi", instamart: "haldi" } },
      { id: "haryana_lunch_kadhi_pakora_with_rice_mustard_seeds", name: "Mustard seeds", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "mustard seeds rai", instamart: "rai" }, optional: true },
      { id: "haryana_lunch_kadhi_pakora_with_rice_curry_leaves", name: "Curry leaves", quantity: 8, unit: "piece", category: "spice", searchTerms: { zepto: "curry leaves", instamart: "kadi patta" }, optional: true },
      { id: "haryana_lunch_kadhi_pakora_with_rice_red_chili_powder", name: "Red chili powder", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "red chilli powder", instamart: "lal mirch powder" } },
      { id: "haryana_lunch_kadhi_pakora_with_rice_oil", name: "Oil", quantity: 3, unit: "tbsp", category: "oil", searchTerms: { zepto: "refined sunflower oil", instamart: "khana pakane ka tel" } }
    ],
    steps: [
      "Whisk yogurt with half the besan and water to make the kadhi base; set aside.",
      "Make a thick batter with remaining besan, chopped onion and spices, and deep-fry small pakoras.",
      "Heat oil, temper mustard seeds and curry leaves, add the kadhi base and simmer for 20 minutes, stirring often.",
      "Drop the pakoras into the simmering kadhi 5 minutes before serving.",
      "Serve hot over steamed rice."
    ],
    tags: ["comfort food", "tangy", "curry"],
  },
  {
    id: "haryana_snack_churma_ladoo",
    name: "Churma Ladoo",
    description: "Sweet crumbled wheat-flour and jaggery ladoos rich with ghee, a festive Haryanvi treat.",
    cuisineRegion: ["Haryana"],
    dietType: "veg",
    goalTags: ["maintenance"],
    mealType: ["snack"],
    prepTime: 15,
    cookTime: 25,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 320, proteinG: 5, carbsG: 40, fatG: 15 },
    ingredients: [
      { id: "haryana_snack_churma_ladoo_whole_wheat_flour", name: "Whole wheat flour", quantity: 200, unit: "g", category: "grain", searchTerms: { zepto: "wheat flour atta", instamart: "atta" } },
      { id: "haryana_snack_churma_ladoo_ghee", name: "Ghee", quantity: 100, unit: "g", category: "oil", searchTerms: { zepto: "ghee", instamart: "desi ghee" } },
      { id: "haryana_snack_churma_ladoo_jaggery_gur", name: "Jaggery (gur)", quantity: 100, unit: "g", category: "other", searchTerms: { zepto: "jaggery gur", instamart: "gur" } },
      { id: "haryana_snack_churma_ladoo_cardamom_powder", name: "Cardamom powder", quantity: 0.5, unit: "tsp", category: "spice", searchTerms: { zepto: "cardamom powder elaichi", instamart: "elaichi powder" }, optional: true },
      { id: "haryana_snack_churma_ladoo_chopped_almonds", name: "Chopped almonds", quantity: 20, unit: "g", category: "protein", searchTerms: { zepto: "almonds badam", instamart: "badam" }, optional: true },
      { id: "haryana_snack_churma_ladoo_semolina_sooji", name: "Semolina (sooji)", quantity: 2, unit: "tbsp", category: "grain", searchTerms: { zepto: "semolina sooji", instamart: "sooji" }, optional: true }
    ],
    steps: [
      "Knead wheat flour with a little ghee and water into a stiff dough, shape into small discs and deep-fry or bake until deep golden.",
      "Once cooled, crumble/grind the discs coarsely.",
      "Melt jaggery with a little ghee to a syrup, then mix into the crumbled flour along with cardamom and almonds.",
      "Shape the warm mixture into small round ladoos while still pliable."
    ],
    tags: ["sweet", "festive", "energy-rich"],
  },
  {
    id: "haryana_dinner_hara_dhania_cholia_with_bajra_roti",
    name: "Hara Dhania Cholia with Bajra Roti",
    description: "Fresh green chickpeas simmered in a light coriander-spiced curry, paired with hand-pressed pearl millet flatbread.",
    cuisineRegion: ["Haryana"],
    dietType: "veg",
    goalTags: ["maintenance"],
    mealType: ["dinner"],
    prepTime: 15,
    cookTime: 25,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 400, proteinG: 14, carbsG: 55, fatG: 12 },
    ingredients: [
      { id: "haryana_dinner_hara_dhania_cholia_with_bajra_roti_green_chickpeas_hara_cholia", name: "Green chickpeas (hara cholia)", quantity: 250, unit: "g", category: "vegetable", searchTerms: { zepto: "green chickpeas hara chana", instamart: "hara cholia" } },
      { id: "haryana_dinner_hara_dhania_cholia_with_bajra_roti_bajra_flour", name: "Bajra flour", quantity: 200, unit: "g", category: "grain", searchTerms: { zepto: "bajra flour", instamart: "bajra atta" } },
      { id: "haryana_dinner_hara_dhania_cholia_with_bajra_roti_onion", name: "Onion", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "pyaz" } },
      { id: "haryana_dinner_hara_dhania_cholia_with_bajra_roti_tomato", name: "Tomato", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "tomato", instamart: "tamatar" } },
      { id: "haryana_dinner_hara_dhania_cholia_with_bajra_roti_coriander_leaves", name: "Coriander leaves", quantity: 30, unit: "g", category: "vegetable", searchTerms: { zepto: "coriander leaves", instamart: "dhania patta" } },
      { id: "haryana_dinner_hara_dhania_cholia_with_bajra_roti_cumin_seeds", name: "Cumin seeds", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "cumin seeds jeera", instamart: "jeera" }, optional: true },
      { id: "haryana_dinner_hara_dhania_cholia_with_bajra_roti_ghee", name: "Ghee", quantity: 2, unit: "tbsp", category: "oil", searchTerms: { zepto: "ghee", instamart: "desi ghee" } },
      { id: "haryana_dinner_hara_dhania_cholia_with_bajra_roti_green_chili", name: "Green chili", quantity: 2, unit: "piece", category: "spice", searchTerms: { zepto: "green chilli", instamart: "hari mirch" }, optional: true }
    ],
    steps: [
      "Heat ghee, splutter cumin, then sauté onion and green chili until soft.",
      "Add tomato and cook until mushy, then add the shelled green chickpeas with a splash of water.",
      "Cover and simmer for 12-15 minutes until the chickpeas are tender; finish with chopped coriander.",
      "Knead bajra flour with warm water, pat into rotis by hand and cook on a hot tawa until charred spots appear.",
      "Serve the cholia curry hot with bajra roti and a dollop of ghee."
    ],
    tags: ["winter special", "wholesome", "rustic"],
  },
  {
    id: "himachal_pradesh_breakfast_siddu",
    name: "Siddu",
    description: "Steamed wheat bread stuffed with a walnut-poppy seed filling, served hot with melted ghee, a Himachali mountain breakfast.",
    cuisineRegion: ["Himachal Pradesh"],
    dietType: "veg",
    goalTags: ["maintenance"],
    mealType: ["breakfast"],
    prepTime: 30,
    cookTime: 30,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 350, proteinG: 9, carbsG: 50, fatG: 13 },
    ingredients: [
      { id: "himachal_pradesh_breakfast_siddu_whole_wheat_flour", name: "Whole wheat flour", quantity: 250, unit: "g", category: "grain", searchTerms: { zepto: "wheat flour atta", instamart: "atta" } },
      { id: "himachal_pradesh_breakfast_siddu_instant_yeast", name: "Instant yeast", quantity: 1, unit: "tsp", category: "other", searchTerms: { zepto: "instant yeast", instamart: "yeast" }, optional: true },
      { id: "himachal_pradesh_breakfast_siddu_walnuts", name: "Walnuts", quantity: 50, unit: "g", category: "protein", searchTerms: { zepto: "walnuts akhrot", instamart: "akhrot" } },
      { id: "himachal_pradesh_breakfast_siddu_poppy_seeds_khuskhus", name: "Poppy seeds (khuskhus)", quantity: 2, unit: "tbsp", category: "spice", searchTerms: { zepto: "poppy seeds khuskhus", instamart: "khuskhus" }, optional: true },
      { id: "himachal_pradesh_breakfast_siddu_ghee", name: "Ghee", quantity: 3, unit: "tbsp", category: "oil", searchTerms: { zepto: "ghee", instamart: "desi ghee" } },
      { id: "himachal_pradesh_breakfast_siddu_sugar", name: "Sugar", quantity: 1, unit: "tsp", category: "other", searchTerms: { zepto: "sugar", instamart: "cheeni" }, optional: true },
      { id: "himachal_pradesh_breakfast_siddu_salt", name: "Salt", quantity: 0.5, unit: "tsp", category: "other", searchTerms: { zepto: "iodised salt", instamart: "namak" } }
    ],
    steps: [
      "Knead wheat flour with yeast, sugar, salt and warm water into a soft dough; let it proof for an hour.",
      "Grind walnuts and poppy seeds coarsely with a little sugar to make the filling.",
      "Flatten dough balls, stuff with the walnut filling, and seal into round buns.",
      "Steam the stuffed buns for 20-25 minutes until cooked through.",
      "Serve hot, generously drizzled with melted ghee."
    ],
    tags: ["steamed", "mountain food", "hearty"],
  },
  {
    id: "himachal_pradesh_lunch_chana_madra",
    name: "Chana Madra",
    description: "Chickpeas simmered in a rich yogurt-based curry flavored with whole spices, a signature dish from Himachali Dham feasts.",
    cuisineRegion: ["Himachal Pradesh"],
    dietType: "veg",
    goalTags: ["maintenance"],
    mealType: ["lunch"],
    prepTime: 15,
    cookTime: 35,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 430, proteinG: 16, carbsG: 48, fatG: 18 },
    ingredients: [
      { id: "himachal_pradesh_lunch_chana_madra_chickpeas", name: "Chickpeas", quantity: 200, unit: "g", category: "protein", searchTerms: { zepto: "kabuli chana chickpeas", instamart: "kabuli chana" } },
      { id: "himachal_pradesh_lunch_chana_madra_yogurt", name: "Yogurt", quantity: 300, unit: "g", category: "dairy", searchTerms: { zepto: "curd fresh", instamart: "dahi" } },
      { id: "himachal_pradesh_lunch_chana_madra_ghee", name: "Ghee", quantity: 3, unit: "tbsp", category: "oil", searchTerms: { zepto: "ghee", instamart: "desi ghee" } },
      { id: "himachal_pradesh_lunch_chana_madra_cloves", name: "Cloves", quantity: 4, unit: "piece", category: "spice", searchTerms: { zepto: "cloves laung", instamart: "laung" }, optional: true },
      { id: "himachal_pradesh_lunch_chana_madra_cinnamon_stick", name: "Cinnamon stick", quantity: 1, unit: "piece", category: "spice", searchTerms: { zepto: "cinnamon stick dalchini", instamart: "dalchini" }, optional: true },
      { id: "himachal_pradesh_lunch_chana_madra_bay_leaf", name: "Bay leaf", quantity: 1, unit: "piece", category: "spice", searchTerms: { zepto: "bay leaf tej patta", instamart: "tej patta" }, optional: true },
      { id: "himachal_pradesh_lunch_chana_madra_gram_flour", name: "Gram flour", quantity: 1, unit: "tbsp", category: "grain", searchTerms: { zepto: "gram flour besan", instamart: "besan" }, optional: true },
      { id: "himachal_pradesh_lunch_chana_madra_red_chili_powder", name: "Red chili powder", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "red chilli powder", instamart: "lal mirch powder" } },
      { id: "himachal_pradesh_lunch_chana_madra_rice", name: "Rice", quantity: 200, unit: "g", category: "grain", searchTerms: { zepto: "basmati rice", instamart: "chawal" } }
    ],
    steps: [
      "Soak chickpeas overnight and pressure cook until soft; retain the boiled liquid.",
      "Whisk yogurt with gram flour to prevent curdling.",
      "Heat ghee, temper cloves, cinnamon and bay leaf, then add the yogurt mixture, stirring continuously on low heat.",
      "Add the boiled chickpeas and chili powder, simmer for 20 minutes until the gravy thickens and turns glossy.",
      "Serve hot with steamed rice."
    ],
    tags: ["festive", "curry", "yogurt-based"],
  },
  {
    id: "himachal_pradesh_snack_babru",
    name: "Babru",
    description: "Himachali stuffed poori filled with spiced black gram paste, deep-fried and enjoyed with tamarind chutney.",
    cuisineRegion: ["Himachal Pradesh"],
    dietType: "veg",
    goalTags: ["maintenance"],
    mealType: ["snack"],
    prepTime: 20,
    cookTime: 25,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 300, proteinG: 8, carbsG: 38, fatG: 13 },
    ingredients: [
      { id: "himachal_pradesh_snack_babru_urad_dal_black_gram", name: "Urad dal (black gram)", quantity: 100, unit: "g", category: "protein", searchTerms: { zepto: "urad dal split", instamart: "urad dal" } },
      { id: "himachal_pradesh_snack_babru_whole_wheat_flour", name: "Whole wheat flour", quantity: 200, unit: "g", category: "grain", searchTerms: { zepto: "wheat flour atta", instamart: "atta" } },
      { id: "himachal_pradesh_snack_babru_fennel_seeds", name: "Fennel seeds", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "fennel seeds saunf", instamart: "saunf" }, optional: true },
      { id: "himachal_pradesh_snack_babru_asafoetida_hing", name: "Asafoetida (hing)", quantity: 1, unit: "piece", category: "spice", searchTerms: { zepto: "asafoetida hing", instamart: "hing" }, optional: true },
      { id: "himachal_pradesh_snack_babru_oil_for_frying", name: "Oil for frying", quantity: 300, unit: "ml", category: "oil", searchTerms: { zepto: "refined sunflower oil", instamart: "khana pakane ka tel" } },
      { id: "himachal_pradesh_snack_babru_tamarind_chutney", name: "Tamarind chutney", quantity: 2, unit: "tbsp", category: "other", searchTerms: { zepto: "tamarind chutney", instamart: "imli chutney" }, optional: true }
    ],
    steps: [
      "Soak urad dal for 3-4 hours, then grind coarsely with fennel seeds and hing to make the filling.",
      "Knead wheat flour with water into a soft dough.",
      "Flatten small dough balls, stuff with the dal filling, seal and roll gently into discs.",
      "Deep-fry until golden and puffed on both sides.",
      "Serve hot with tamarind chutney."
    ],
    tags: ["fried", "snack", "tea-time"],
  },
  {
    id: "himachal_pradesh_dinner_sepu_vadi",
    name: "Sepu Vadi",
    description: "Sun-dried lentil dumplings simmered in a spiced yogurt-tomato gravy, a hearty Himachali dinner curry served with rice.",
    cuisineRegion: ["Himachal Pradesh"],
    dietType: "veg",
    goalTags: ["maintenance"],
    mealType: ["dinner"],
    prepTime: 15,
    cookTime: 35,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 410, proteinG: 15, carbsG: 50, fatG: 14 },
    ingredients: [
      { id: "himachal_pradesh_dinner_sepu_vadi_urad_dal_vadi_lentil_dumplings", name: "Urad dal vadi (lentil dumplings)", quantity: 150, unit: "g", category: "protein", searchTerms: { zepto: "urad dal vadi", instamart: "vadi" } },
      { id: "himachal_pradesh_dinner_sepu_vadi_yogurt", name: "Yogurt", quantity: 200, unit: "g", category: "dairy", searchTerms: { zepto: "curd fresh", instamart: "dahi" } },
      { id: "himachal_pradesh_dinner_sepu_vadi_tomato", name: "Tomato", quantity: 2, unit: "medium", category: "vegetable", searchTerms: { zepto: "tomato", instamart: "tamatar" } },
      { id: "himachal_pradesh_dinner_sepu_vadi_onion", name: "Onion", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "pyaz" } },
      { id: "himachal_pradesh_dinner_sepu_vadi_turmeric_powder", name: "Turmeric powder", quantity: 0.5, unit: "tsp", category: "spice", searchTerms: { zepto: "turmeric powder haldi", instamart: "haldi" } },
      { id: "himachal_pradesh_dinner_sepu_vadi_ghee", name: "Ghee", quantity: 2, unit: "tbsp", category: "oil", searchTerms: { zepto: "ghee", instamart: "desi ghee" } },
      { id: "himachal_pradesh_dinner_sepu_vadi_rice", name: "Rice", quantity: 200, unit: "g", category: "grain", searchTerms: { zepto: "basmati rice", instamart: "chawal" } },
      { id: "himachal_pradesh_dinner_sepu_vadi_red_chili_powder", name: "Red chili powder", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "red chilli powder", instamart: "lal mirch powder" } }
    ],
    steps: [
      "Lightly roast or fry the vadi pieces until golden, then set aside.",
      "Heat ghee, sauté onion until golden, then add tomato and cook until soft.",
      "Add turmeric and chili powder, then whisked yogurt, stirring continuously to avoid curdling.",
      "Add the roasted vadi and a little water, simmer for 15 minutes until the gravy thickens.",
      "Serve hot with steamed rice."
    ],
    tags: ["curry", "lentil", "home-style"],
  },
  {
    id: "uttarakhand_breakfast_aloo_ke_gutke_with_poori",
    name: "Aloo ke Gutke with Poori",
    description: "Pan-roasted spiced potatoes tempered with cumin and Himalayan herbs, served with deep-fried whole wheat poori.",
    cuisineRegion: ["Uttarakhand"],
    dietType: "veg",
    goalTags: ["maintenance"],
    mealType: ["breakfast"],
    prepTime: 15,
    cookTime: 25,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 480, proteinG: 9, carbsG: 65, fatG: 20 },
    ingredients: [
      { id: "uttarakhand_breakfast_aloo_ke_gutke_with_poori_potato", name: "Potato", quantity: 4, unit: "medium", category: "vegetable", searchTerms: { zepto: "potato", instamart: "aloo" } },
      { id: "uttarakhand_breakfast_aloo_ke_gutke_with_poori_whole_wheat_flour", name: "Whole wheat flour", quantity: 200, unit: "g", category: "grain", searchTerms: { zepto: "wheat flour atta", instamart: "atta" } },
      { id: "uttarakhand_breakfast_aloo_ke_gutke_with_poori_cumin_seeds", name: "Cumin seeds", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "cumin seeds jeera", instamart: "jeera" }, optional: true },
      { id: "uttarakhand_breakfast_aloo_ke_gutke_with_poori_red_chili_powder", name: "Red chili powder", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "red chilli powder", instamart: "lal mirch powder" } },
      { id: "uttarakhand_breakfast_aloo_ke_gutke_with_poori_turmeric_powder", name: "Turmeric powder", quantity: 0.5, unit: "tsp", category: "spice", searchTerms: { zepto: "turmeric powder haldi", instamart: "haldi" } },
      { id: "uttarakhand_breakfast_aloo_ke_gutke_with_poori_mustard_oil", name: "Mustard oil", quantity: 3, unit: "tbsp", category: "oil", searchTerms: { zepto: "mustard oil", instamart: "sarson ka tel" } },
      { id: "uttarakhand_breakfast_aloo_ke_gutke_with_poori_oil_for_frying_poori", name: "Oil for frying poori", quantity: 200, unit: "ml", category: "oil", searchTerms: { zepto: "refined sunflower oil", instamart: "khana pakane ka tel" } },
      { id: "uttarakhand_breakfast_aloo_ke_gutke_with_poori_coriander_leaves", name: "Coriander leaves", quantity: 10, unit: "g", category: "vegetable", searchTerms: { zepto: "coriander leaves", instamart: "dhania patta" }, optional: true }
    ],
    steps: [
      "Boil potatoes until just tender, peel and cut into cubes.",
      "Heat mustard oil, splutter cumin seeds, add turmeric and chili powder, then toss in the potatoes.",
      "Roast on medium-low heat until the potatoes develop a light crust; garnish with coriander.",
      "Knead wheat flour into a stiff dough, roll into small discs, and deep-fry until puffed and golden.",
      "Serve the gutke hot with the poori."
    ],
    tags: ["mountain food", "spiced potatoes", "fried bread"],
  },
  {
    id: "uttarakhand_lunch_bhatt_ki_churkani",
    name: "Bhatt ki Churkani",
    description: "Black soybeans simmered in a roasted-gram-flour thickened curry, a wholesome Kumaoni lunch classic served with rice.",
    cuisineRegion: ["Uttarakhand"],
    dietType: "veg",
    goalTags: ["maintenance", "muscle", "recovery"],
    mealType: ["lunch"],
    prepTime: 15,
    cookTime: 40,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 400, proteinG: 20, carbsG: 45, fatG: 12 },
    ingredients: [
      { id: "uttarakhand_lunch_bhatt_ki_churkani_bhatt_black_soybean", name: "Bhatt (black soybean)", quantity: 200, unit: "g", category: "protein", searchTerms: { zepto: "black soybean bhatt", instamart: "bhatt dal" } },
      { id: "uttarakhand_lunch_bhatt_ki_churkani_gram_flour", name: "Gram flour", quantity: 2, unit: "tbsp", category: "grain", searchTerms: { zepto: "gram flour besan", instamart: "besan" }, optional: true },
      { id: "uttarakhand_lunch_bhatt_ki_churkani_garlic", name: "Garlic", quantity: 6, unit: "piece", category: "spice", searchTerms: { zepto: "garlic", instamart: "lehsun" } },
      { id: "uttarakhand_lunch_bhatt_ki_churkani_ginger", name: "Ginger", quantity: 1, unit: "inch", category: "spice", searchTerms: { zepto: "ginger", instamart: "adrak" }, optional: true },
      { id: "uttarakhand_lunch_bhatt_ki_churkani_mustard_oil", name: "Mustard oil", quantity: 2, unit: "tbsp", category: "oil", searchTerms: { zepto: "mustard oil", instamart: "sarson ka tel" } },
      { id: "uttarakhand_lunch_bhatt_ki_churkani_turmeric_powder", name: "Turmeric powder", quantity: 0.5, unit: "tsp", category: "spice", searchTerms: { zepto: "turmeric powder haldi", instamart: "haldi" } },
      { id: "uttarakhand_lunch_bhatt_ki_churkani_rice", name: "Rice", quantity: 200, unit: "g", category: "grain", searchTerms: { zepto: "basmati rice", instamart: "chawal" } }
    ],
    steps: [
      "Soak bhatt overnight, then pressure cook with turmeric and salt until soft.",
      "Dry roast gram flour lightly and mix with a little water to make a smooth slurry.",
      "Heat mustard oil, sauté crushed garlic and ginger until fragrant.",
      "Add the boiled bhatt along with the besan slurry, simmer for 15 minutes until the curry thickens.",
      "Serve hot with steamed rice."
    ],
    tags: ["protein-rich", "Kumaoni", "hearty"],
  },
  {
    id: "uttarakhand_snack_bal_mithai",
    name: "Bal Mithai",
    description: "Roasted khoya fudge coated in white sugar balls, the iconic sweet treat of Almora, Uttarakhand.",
    cuisineRegion: ["Uttarakhand"],
    dietType: "veg",
    goalTags: ["maintenance", "weight_loss"],
    mealType: ["snack"],
    prepTime: 15,
    cookTime: 20,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 280, proteinG: 6, carbsG: 35, fatG: 12 },
    ingredients: [
      { id: "uttarakhand_snack_bal_mithai_khoya_mawa", name: "Khoya (mawa)", quantity: 250, unit: "g", category: "dairy", searchTerms: { zepto: "khoya mawa", instamart: "mawa" } },
      { id: "uttarakhand_snack_bal_mithai_sugar", name: "Sugar", quantity: 100, unit: "g", category: "other", searchTerms: { zepto: "sugar", instamart: "cheeni" } },
      { id: "uttarakhand_snack_bal_mithai_sugar_balls_dragees", name: "Sugar balls (dragees)", quantity: 30, unit: "g", category: "other", searchTerms: { zepto: "sugar balls dragees", instamart: "sugar balls" }, optional: true },
      { id: "uttarakhand_snack_bal_mithai_cardamom_powder", name: "Cardamom powder", quantity: 0.5, unit: "tsp", category: "spice", searchTerms: { zepto: "cardamom powder elaichi", instamart: "elaichi powder" }, optional: true },
      { id: "uttarakhand_snack_bal_mithai_ghee", name: "Ghee", quantity: 1, unit: "tbsp", category: "oil", searchTerms: { zepto: "ghee", instamart: "desi ghee" }, optional: true }
    ],
    steps: [
      "Roast khoya in a heavy pan on low heat until it turns light brown and fragrant, stirring continuously.",
      "Add sugar and cardamom, continue cooking until the mixture thickens and leaves the sides of the pan.",
      "Spread the mixture on a greased plate and let it cool slightly.",
      "Cut into small squares and coat each piece generously with sugar balls before serving."
    ],
    tags: ["sweet", "festive", "milk-based"],
  },
  {
    id: "uttarakhand_dinner_kafuli",
    name: "Kafuli",
    description: "Garhwali-style pureed spinach and fenugreek leaves cooked with rice flour, served with steamed rice or roti.",
    cuisineRegion: ["Uttarakhand"],
    dietType: "veg",
    goalTags: ["maintenance"],
    mealType: ["dinner"],
    prepTime: 15,
    cookTime: 25,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 320, proteinG: 10, carbsG: 40, fatG: 10 },
    ingredients: [
      { id: "uttarakhand_dinner_kafuli_spinach", name: "Spinach", quantity: 300, unit: "g", category: "vegetable", searchTerms: { zepto: "spinach palak", instamart: "palak" } },
      { id: "uttarakhand_dinner_kafuli_fenugreek_leaves_methi", name: "Fenugreek leaves (methi)", quantity: 100, unit: "g", category: "vegetable", searchTerms: { zepto: "fenugreek leaves methi", instamart: "methi" }, optional: true },
      { id: "uttarakhand_dinner_kafuli_rice_flour", name: "Rice flour", quantity: 2, unit: "tbsp", category: "grain", searchTerms: { zepto: "rice flour", instamart: "chawal ka atta" } },
      { id: "uttarakhand_dinner_kafuli_garlic", name: "Garlic", quantity: 4, unit: "piece", category: "spice", searchTerms: { zepto: "garlic", instamart: "lehsun" } },
      { id: "uttarakhand_dinner_kafuli_ghee", name: "Ghee", quantity: 2, unit: "tbsp", category: "oil", searchTerms: { zepto: "ghee", instamart: "desi ghee" } },
      { id: "uttarakhand_dinner_kafuli_cumin_seeds", name: "Cumin seeds", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "cumin seeds jeera", instamart: "jeera" }, optional: true },
      { id: "uttarakhand_dinner_kafuli_rice", name: "Rice", quantity: 200, unit: "g", category: "grain", searchTerms: { zepto: "basmati rice", instamart: "chawal" } }
    ],
    steps: [
      "Boil spinach and fenugreek leaves together until wilted, then blend to a coarse puree.",
      "Mix rice flour with a little water to make a smooth slurry.",
      "Heat ghee, splutter cumin and crushed garlic, then add the pureed greens.",
      "Stir in the rice flour slurry and simmer for 10 minutes until the curry thickens.",
      "Serve hot with steamed rice or roti."
    ],
    tags: ["greens", "light dinner", "Garhwali"],
  },
  {
    id: "delhi_breakfast_chole_bhature",
    name: "Chole Bhature",
    description: "Spicy chickpea curry paired with fluffy deep-fried leavened bread, Delhi's ultimate weekend breakfast indulgence.",
    cuisineRegion: ["Delhi"],
    dietType: "veg",
    goalTags: ["maintenance", "weight_gain"],
    mealType: ["breakfast"],
    prepTime: 15,
    cookTime: 30,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 550, proteinG: 16, carbsG: 75, fatG: 22 },
    ingredients: [
      { id: "delhi_breakfast_chole_bhature_chickpeas", name: "Chickpeas", quantity: 200, unit: "g", category: "protein", searchTerms: { zepto: "kabuli chana chickpeas", instamart: "kabuli chana" } },
      { id: "delhi_breakfast_chole_bhature_refined_flour_maida", name: "Refined flour (maida)", quantity: 250, unit: "g", category: "grain", searchTerms: { zepto: "refined flour maida", instamart: "maida" } },
      { id: "delhi_breakfast_chole_bhature_yogurt", name: "Yogurt", quantity: 2, unit: "tbsp", category: "dairy", searchTerms: { zepto: "curd fresh", instamart: "dahi" } },
      { id: "delhi_breakfast_chole_bhature_onion", name: "Onion", quantity: 2, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "pyaz" } },
      { id: "delhi_breakfast_chole_bhature_tomato", name: "Tomato", quantity: 2, unit: "medium", category: "vegetable", searchTerms: { zepto: "tomato", instamart: "tamatar" } },
      { id: "delhi_breakfast_chole_bhature_chole_masala", name: "Chole masala", quantity: 1.5, unit: "tbsp", category: "spice", searchTerms: { zepto: "chole masala", instamart: "chole masala" } },
      { id: "delhi_breakfast_chole_bhature_baking_soda", name: "Baking soda", quantity: 0.5, unit: "tsp", category: "other", searchTerms: { zepto: "baking soda", instamart: "baking soda" }, optional: true },
      { id: "delhi_breakfast_chole_bhature_oil_for_frying", name: "Oil for frying", quantity: 300, unit: "ml", category: "oil", searchTerms: { zepto: "refined sunflower oil", instamart: "khana pakane ka tel" } }
    ],
    steps: [
      "Soak chickpeas overnight, then pressure cook with a pinch of baking soda until soft.",
      "Knead maida with yogurt, a pinch of baking soda and water into a soft dough; rest for 2 hours.",
      "Sauté onion and tomato with chole masala, add the boiled chickpeas and simmer until thick.",
      "Roll dough into ovals and deep-fry until puffed and golden to make bhature.",
      "Serve the chole hot with freshly fried bhature."
    ],
    tags: ["street food", "indulgent", "popular"],
  },
  {
    id: "delhi_lunch_kadai_paneer",
    name: "Kadai Paneer",
    description: "Cottage cheese and bell peppers tossed in a coarsely ground spice-tomato masala, a Delhi restaurant-style lunch favorite with tandoori roti.",
    cuisineRegion: ["Delhi"],
    dietType: "veg",
    goalTags: ["maintenance"],
    mealType: ["lunch"],
    prepTime: 15,
    cookTime: 20,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 420, proteinG: 18, carbsG: 30, fatG: 24 },
    ingredients: [
      { id: "delhi_lunch_kadai_paneer_paneer", name: "Paneer", quantity: 250, unit: "g", category: "dairy", searchTerms: { zepto: "paneer fresh", instamart: "paneer" } },
      { id: "delhi_lunch_kadai_paneer_capsicum_bell_pepper", name: "Capsicum (bell pepper)", quantity: 2, unit: "medium", category: "vegetable", searchTerms: { zepto: "capsicum green", instamart: "shimla mirch" } },
      { id: "delhi_lunch_kadai_paneer_onion", name: "Onion", quantity: 2, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "pyaz" } },
      { id: "delhi_lunch_kadai_paneer_tomato", name: "Tomato", quantity: 3, unit: "medium", category: "vegetable", searchTerms: { zepto: "tomato", instamart: "tamatar" } },
      { id: "delhi_lunch_kadai_paneer_kadai_masala", name: "Kadai masala", quantity: 1.5, unit: "tbsp", category: "spice", searchTerms: { zepto: "kadai masala", instamart: "kadai masala" } },
      { id: "delhi_lunch_kadai_paneer_ginger_garlic_paste", name: "Ginger-garlic paste", quantity: 1, unit: "tbsp", category: "spice", searchTerms: { zepto: "ginger garlic paste", instamart: "adrak lehsun paste" } },
      { id: "delhi_lunch_kadai_paneer_whole_wheat_flour", name: "Whole wheat flour", quantity: 150, unit: "g", category: "grain", searchTerms: { zepto: "wheat flour atta", instamart: "atta" } },
      { id: "delhi_lunch_kadai_paneer_oil", name: "Oil", quantity: 2, unit: "tbsp", category: "oil", searchTerms: { zepto: "refined sunflower oil", instamart: "khana pakane ka tel" } }
    ],
    steps: [
      "Coarsely grind kadai masala with dry red chilies for a rustic texture.",
      "Heat oil, sauté onion and ginger-garlic paste, then add tomato and cook until soft.",
      "Add the ground kadai masala, capsicum and paneer cubes, tossing well for 5-7 minutes.",
      "Knead wheat flour into a dough and roll into rotis; cook on a hot tawa or tandoor until charred.",
      "Serve the kadai paneer hot with tandoori roti."
    ],
    tags: ["restaurant-style", "spicy", "quick"],
  },
  {
    id: "delhi_snack_aloo_tikki_chaat",
    name: "Aloo Tikki Chaat",
    description: "Crisp shallow-fried potato patties topped with tangy tamarind and mint chutneys, yogurt, and crunchy sev.",
    cuisineRegion: ["Delhi"],
    dietType: "veg",
    goalTags: ["maintenance"],
    mealType: ["snack"],
    prepTime: 20,
    cookTime: 20,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 350, proteinG: 7, carbsG: 48, fatG: 14 },
    ingredients: [
      { id: "delhi_snack_aloo_tikki_chaat_potato", name: "Potato", quantity: 4, unit: "medium", category: "vegetable", searchTerms: { zepto: "potato", instamart: "aloo" } },
      { id: "delhi_snack_aloo_tikki_chaat_cornflour", name: "Cornflour", quantity: 2, unit: "tbsp", category: "grain", searchTerms: { zepto: "cornflour", instamart: "cornflour" }, optional: true },
      { id: "delhi_snack_aloo_tikki_chaat_green_chili", name: "Green chili", quantity: 1, unit: "piece", category: "spice", searchTerms: { zepto: "green chilli", instamart: "hari mirch" }, optional: true },
      { id: "delhi_snack_aloo_tikki_chaat_tamarind_chutney", name: "Tamarind chutney", quantity: 2, unit: "tbsp", category: "other", searchTerms: { zepto: "tamarind chutney", instamart: "imli chutney" } },
      { id: "delhi_snack_aloo_tikki_chaat_mint_coriander_chutney", name: "Mint-coriander chutney", quantity: 2, unit: "tbsp", category: "vegetable", searchTerms: { zepto: "mint coriander chutney", instamart: "hari chutney" } },
      { id: "delhi_snack_aloo_tikki_chaat_yogurt", name: "Yogurt", quantity: 100, unit: "g", category: "dairy", searchTerms: { zepto: "curd fresh", instamart: "dahi" }, optional: true },
      { id: "delhi_snack_aloo_tikki_chaat_sev", name: "Sev", quantity: 30, unit: "g", category: "other", searchTerms: { zepto: "sev namkeen", instamart: "sev" }, optional: true },
      { id: "delhi_snack_aloo_tikki_chaat_oil_for_shallow_fry", name: "Oil for shallow fry", quantity: 4, unit: "tbsp", category: "oil", searchTerms: { zepto: "refined sunflower oil", instamart: "khana pakane ka tel" } }
    ],
    steps: [
      "Boil potatoes, mash and mix with cornflour, chopped green chili and salt; shape into flat patties.",
      "Shallow fry the patties on a griddle until golden and crisp on both sides.",
      "Arrange the tikkis on a plate and top with whisked yogurt, tamarind chutney and mint chutney.",
      "Sprinkle with sev and serve immediately."
    ],
    tags: ["street food", "chaat", "tangy"],
  },
  {
    id: "delhi_dinner_butter_chicken",
    name: "Butter Chicken",
    description: "Tandoori-roasted chicken simmered in a velvety tomato-cashew gravy finished with butter and cream, served with naan.",
    cuisineRegion: ["Delhi"],
    dietType: "nonveg",
    goalTags: ["maintenance", "muscle", "recovery", "weight_gain"],
    mealType: ["dinner"],
    prepTime: 30,
    cookTime: 30,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 520, proteinG: 32, carbsG: 20, fatG: 32 },
    ingredients: [
      { id: "delhi_dinner_butter_chicken_chicken_boneless", name: "Chicken (boneless)", quantity: 400, unit: "g", category: "protein", searchTerms: { zepto: "boneless chicken", instamart: "chicken boneless" } },
      { id: "delhi_dinner_butter_chicken_yogurt", name: "Yogurt", quantity: 100, unit: "g", category: "dairy", searchTerms: { zepto: "curd fresh", instamart: "dahi" } },
      { id: "delhi_dinner_butter_chicken_butter", name: "Butter", quantity: 3, unit: "tbsp", category: "dairy", searchTerms: { zepto: "butter", instamart: "makhan" } },
      { id: "delhi_dinner_butter_chicken_tomato_puree", name: "Tomato puree", quantity: 300, unit: "g", category: "vegetable", searchTerms: { zepto: "tomato puree", instamart: "tamatar puree" } },
      { id: "delhi_dinner_butter_chicken_cashew_nuts", name: "Cashew nuts", quantity: 20, unit: "g", category: "protein", searchTerms: { zepto: "cashew nuts kaju", instamart: "kaju" }, optional: true },
      { id: "delhi_dinner_butter_chicken_fresh_cream", name: "Fresh cream", quantity: 3, unit: "tbsp", category: "dairy", searchTerms: { zepto: "fresh cream", instamart: "malai cream" } },
      { id: "delhi_dinner_butter_chicken_ginger_garlic_paste", name: "Ginger-garlic paste", quantity: 1, unit: "tbsp", category: "spice", searchTerms: { zepto: "ginger garlic paste", instamart: "adrak lehsun paste" } },
      { id: "delhi_dinner_butter_chicken_kasuri_methi", name: "Kasuri methi", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "kasuri methi dried fenugreek", instamart: "kasuri methi" }, optional: true },
      { id: "delhi_dinner_butter_chicken_naan", name: "Naan", quantity: 4, unit: "piece", category: "grain", searchTerms: { zepto: "naan bread", instamart: "naan" } }
    ],
    steps: [
      "Marinate chicken with yogurt, ginger-garlic paste and spices for at least 1 hour; grill or pan-roast until charred at the edges.",
      "Simmer tomato puree with cashews until soft, then blend into a smooth paste.",
      "Heat butter, add the tomato-cashew paste and simmer for 10 minutes.",
      "Add the roasted chicken, cream and crushed kasuri methi, simmering for another 10 minutes.",
      "Serve hot with butter-brushed naan."
    ],
    tags: ["rich", "iconic", "restaurant-style"],
  },
  {
    id: "jammu_kashmir_breakfast_noon_chai_with_kulcha",
    name: "Noon Chai with Kulcha",
    description: "Traditional Kashmiri pink salted tea simmered with baking soda and milk, sipped with crisp sesame-topped kulcha bread.",
    cuisineRegion: ["Jammu & Kashmir"],
    dietType: "veg",
    goalTags: ["maintenance"],
    mealType: ["breakfast"],
    prepTime: 5,
    cookTime: 20,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 300, proteinG: 7, carbsG: 42, fatG: 11 },
    ingredients: [
      { id: "jammu_kashmir_breakfast_noon_chai_with_kulcha_kashmiri_green_tea_leaves", name: "Kashmiri green tea leaves", quantity: 2, unit: "tbsp", category: "other", searchTerms: { zepto: "kashmiri green tea leaves", instamart: "kashmiri chai patti" } },
      { id: "jammu_kashmir_breakfast_noon_chai_with_kulcha_baking_soda", name: "Baking soda", quantity: 1, unit: "piece", category: "other", searchTerms: { zepto: "baking soda", instamart: "baking soda" }, optional: true },
      { id: "jammu_kashmir_breakfast_noon_chai_with_kulcha_milk", name: "Milk", quantity: 300, unit: "ml", category: "dairy", searchTerms: { zepto: "full cream milk", instamart: "doodh" } },
      { id: "jammu_kashmir_breakfast_noon_chai_with_kulcha_salt", name: "Salt", quantity: 1, unit: "piece", category: "other", searchTerms: { zepto: "iodised salt", instamart: "namak" }, optional: true },
      { id: "jammu_kashmir_breakfast_noon_chai_with_kulcha_kulcha_bread", name: "Kulcha bread", quantity: 4, unit: "piece", category: "grain", searchTerms: { zepto: "kulcha bread", instamart: "kulcha" } },
      { id: "jammu_kashmir_breakfast_noon_chai_with_kulcha_sesame_seeds", name: "Sesame seeds", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "sesame seeds til", instamart: "til" }, optional: true },
      { id: "jammu_kashmir_breakfast_noon_chai_with_kulcha_chopped_almonds", name: "Chopped almonds", quantity: 10, unit: "g", category: "protein", searchTerms: { zepto: "almonds badam", instamart: "badam" }, optional: true }
    ],
    steps: [
      "Boil the tea leaves with water and a pinch of baking soda, whisking vigorously until the liquid turns deep pink.",
      "Add milk and a pinch of salt, simmering gently for 10 minutes.",
      "Strain into cups and garnish with crushed almonds.",
      "Warm the sesame-topped kulcha and serve alongside the hot noon chai."
    ],
    tags: ["traditional", "beverage", "Kashmiri"],
  },
  {
    id: "jammu_kashmir_lunch_kashmiri_dum_aloo",
    name: "Kashmiri Dum Aloo",
    description: "Baby potatoes slow-cooked in a fragrant yogurt-fennel gravy tinged red with Kashmiri chili, served with steamed rice.",
    cuisineRegion: ["Jammu & Kashmir"],
    dietType: "veg",
    goalTags: ["maintenance"],
    mealType: ["lunch"],
    prepTime: 15,
    cookTime: 30,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 400, proteinG: 8, carbsG: 55, fatG: 16 },
    ingredients: [
      { id: "jammu_kashmir_lunch_kashmiri_dum_aloo_baby_potatoes", name: "Baby potatoes", quantity: 400, unit: "g", category: "vegetable", searchTerms: { zepto: "baby potatoes", instamart: "chote aloo" } },
      { id: "jammu_kashmir_lunch_kashmiri_dum_aloo_yogurt", name: "Yogurt", quantity: 200, unit: "g", category: "dairy", searchTerms: { zepto: "curd fresh", instamart: "dahi" } },
      { id: "jammu_kashmir_lunch_kashmiri_dum_aloo_kashmiri_red_chili_powder", name: "Kashmiri red chili powder", quantity: 1.5, unit: "tbsp", category: "spice", searchTerms: { zepto: "kashmiri red chilli powder", instamart: "kashmiri lal mirch" } },
      { id: "jammu_kashmir_lunch_kashmiri_dum_aloo_fennel_powder_saunf", name: "Fennel powder (saunf)", quantity: 1, unit: "tbsp", category: "spice", searchTerms: { zepto: "fennel powder saunf", instamart: "saunf powder" } },
      { id: "jammu_kashmir_lunch_kashmiri_dum_aloo_dry_ginger_powder_saunth", name: "Dry ginger powder (saunth)", quantity: 0.5, unit: "tsp", category: "spice", searchTerms: { zepto: "dry ginger powder saunth", instamart: "saunth" }, optional: true },
      { id: "jammu_kashmir_lunch_kashmiri_dum_aloo_mustard_oil", name: "Mustard oil", quantity: 3, unit: "tbsp", category: "oil", searchTerms: { zepto: "mustard oil", instamart: "sarson ka tel" } },
      { id: "jammu_kashmir_lunch_kashmiri_dum_aloo_rice", name: "Rice", quantity: 200, unit: "g", category: "grain", searchTerms: { zepto: "basmati rice", instamart: "chawal" } },
      { id: "jammu_kashmir_lunch_kashmiri_dum_aloo_asafoetida_hing", name: "Asafoetida (hing)", quantity: 1, unit: "piece", category: "spice", searchTerms: { zepto: "asafoetida hing", instamart: "hing" }, optional: true }
    ],
    steps: [
      "Boil baby potatoes until just tender, peel and prick them lightly with a fork; shallow-fry until golden.",
      "Whisk yogurt with Kashmiri chili powder, fennel powder and dry ginger powder.",
      "Heat mustard oil, add a pinch of hing, then pour in the yogurt-spice mixture, stirring continuously.",
      "Add the fried potatoes and a little water, cover and simmer on low heat for 15 minutes.",
      "Serve hot with steamed rice."
    ],
    tags: ["Kashmiri", "vegetarian", "curry"],
  },
  {
    id: "jammu_kashmir_snack_nadru_monje",
    name: "Nadru Monje",
    description: "Crunchy lotus stem slices coated in spiced gram flour batter and fried golden, a favorite Kashmiri teatime snack.",
    cuisineRegion: ["Jammu & Kashmir"],
    dietType: "veg",
    goalTags: ["maintenance", "weight_loss"],
    mealType: ["snack"],
    prepTime: 15,
    cookTime: 20,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 280, proteinG: 6, carbsG: 32, fatG: 14 },
    ingredients: [
      { id: "jammu_kashmir_snack_nadru_monje_lotus_stem_nadru", name: "Lotus stem (nadru)", quantity: 250, unit: "g", category: "vegetable", searchTerms: { zepto: "lotus stem", instamart: "nadru" } },
      { id: "jammu_kashmir_snack_nadru_monje_gram_flour_besan", name: "Gram flour (besan)", quantity: 100, unit: "g", category: "grain", searchTerms: { zepto: "gram flour besan", instamart: "besan" } },
      { id: "jammu_kashmir_snack_nadru_monje_red_chili_powder", name: "Red chili powder", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "red chilli powder", instamart: "lal mirch powder" } },
      { id: "jammu_kashmir_snack_nadru_monje_fennel_powder", name: "Fennel powder", quantity: 0.5, unit: "tsp", category: "spice", searchTerms: { zepto: "fennel powder saunf", instamart: "saunf powder" }, optional: true },
      { id: "jammu_kashmir_snack_nadru_monje_carom_seeds_ajwain", name: "Carom seeds (ajwain)", quantity: 0.5, unit: "tsp", category: "spice", searchTerms: { zepto: "carom seeds ajwain", instamart: "ajwain" }, optional: true },
      { id: "jammu_kashmir_snack_nadru_monje_oil_for_frying", name: "Oil for frying", quantity: 200, unit: "ml", category: "oil", searchTerms: { zepto: "refined sunflower oil", instamart: "khana pakane ka tel" } }
    ],
    steps: [
      "Peel and slice the lotus stem into thin rounds; parboil briefly and pat dry.",
      "Make a thick batter with besan, chili powder, fennel powder, ajwain, salt and water.",
      "Dip the lotus stem slices into the batter and deep-fry until golden and crisp.",
      "Drain on paper towels and serve hot with chutney or ketchup."
    ],
    tags: ["fried", "crunchy", "tea-time"],
  },
  {
    id: "jammu_kashmir_dinner_rogan_josh",
    name: "Rogan Josh",
    description: "Tender mutton braised in a deep red Kashmiri chili and yogurt gravy fragrant with fennel and dry ginger, served with steamed rice.",
    cuisineRegion: ["Jammu & Kashmir"],
    dietType: "nonveg",
    goalTags: ["maintenance", "muscle", "recovery", "weight_gain"],
    mealType: ["dinner"],
    prepTime: 20,
    cookTime: 60,
    servings: 2,
    difficulty: "hard",
    nutrition: { calories: 500, proteinG: 34, carbsG: 15, fatG: 30 },
    ingredients: [
      { id: "jammu_kashmir_dinner_rogan_josh_mutton_bone_in", name: "Mutton (bone-in)", quantity: 500, unit: "g", category: "protein", searchTerms: { zepto: "mutton bone-in", instamart: "mutton" } },
      { id: "jammu_kashmir_dinner_rogan_josh_yogurt", name: "Yogurt", quantity: 200, unit: "g", category: "dairy", searchTerms: { zepto: "curd fresh", instamart: "dahi" } },
      { id: "jammu_kashmir_dinner_rogan_josh_kashmiri_red_chili_powder", name: "Kashmiri red chili powder", quantity: 2, unit: "tbsp", category: "spice", searchTerms: { zepto: "kashmiri red chilli powder", instamart: "kashmiri lal mirch" } },
      { id: "jammu_kashmir_dinner_rogan_josh_fennel_powder", name: "Fennel powder", quantity: 1, unit: "tbsp", category: "spice", searchTerms: { zepto: "fennel powder saunf", instamart: "saunf powder" } },
      { id: "jammu_kashmir_dinner_rogan_josh_dry_ginger_powder_saunth", name: "Dry ginger powder (saunth)", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "dry ginger powder saunth", instamart: "saunth" }, optional: true },
      { id: "jammu_kashmir_dinner_rogan_josh_mustard_oil", name: "Mustard oil", quantity: 4, unit: "tbsp", category: "oil", searchTerms: { zepto: "mustard oil", instamart: "sarson ka tel" } },
      { id: "jammu_kashmir_dinner_rogan_josh_bay_leaf", name: "Bay leaf", quantity: 2, unit: "piece", category: "spice", searchTerms: { zepto: "bay leaf tej patta", instamart: "tej patta" }, optional: true },
      { id: "jammu_kashmir_dinner_rogan_josh_rice", name: "Rice", quantity: 200, unit: "g", category: "grain", searchTerms: { zepto: "basmati rice", instamart: "chawal" } }
    ],
    steps: [
      "Heat mustard oil until smoking, then let it cool slightly; sear the mutton pieces with bay leaf until browned.",
      "Whisk yogurt with Kashmiri chili powder, fennel powder and dry ginger powder.",
      "Lower the heat, add the yogurt-spice mixture to the mutton, stirring continuously to prevent curdling.",
      "Add water, cover and simmer on low heat for 45-50 minutes until the mutton is fork-tender and the gravy turns deep red.",
      "Serve hot with steamed rice."
    ],
    tags: ["iconic", "slow-cooked", "festive"],
  },
  {
    id: "ladakh_breakfast_gur_gur_cha_with_khambir",
    name: "Gur Gur Cha with Khambir",
    description: "Churned butter tea seasoned with salt, sipped with fresh Ladakhi fermented barley bread, a warming Himalayan breakfast.",
    cuisineRegion: ["Ladakh"],
    dietType: "veg",
    goalTags: ["maintenance"],
    mealType: ["breakfast"],
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 320, proteinG: 7, carbsG: 45, fatG: 12 },
    ingredients: [
      { id: "ladakh_breakfast_gur_gur_cha_with_khambir_brick_butter_tea_leaves", name: "Brick/butter tea leaves", quantity: 2, unit: "tbsp", category: "other", searchTerms: { zepto: "loose tea leaves", instamart: "chai patti" } },
      { id: "ladakh_breakfast_gur_gur_cha_with_khambir_butter", name: "Butter", quantity: 2, unit: "tbsp", category: "dairy", searchTerms: { zepto: "butter", instamart: "makhan" } },
      { id: "ladakh_breakfast_gur_gur_cha_with_khambir_salt", name: "Salt", quantity: 1, unit: "piece", category: "other", searchTerms: { zepto: "iodised salt", instamart: "namak" }, optional: true },
      { id: "ladakh_breakfast_gur_gur_cha_with_khambir_milk", name: "Milk", quantity: 100, unit: "ml", category: "dairy", searchTerms: { zepto: "full cream milk", instamart: "doodh" }, optional: true },
      { id: "ladakh_breakfast_gur_gur_cha_with_khambir_barley_flour", name: "Barley flour", quantity: 200, unit: "g", category: "grain", searchTerms: { zepto: "barley flour", instamart: "jau atta" } },
      { id: "ladakh_breakfast_gur_gur_cha_with_khambir_yeast_sourdough_starter", name: "Yeast/sourdough starter", quantity: 1, unit: "tsp", category: "other", searchTerms: { zepto: "instant yeast", instamart: "yeast" }, optional: true }
    ],
    steps: [
      "Boil the tea leaves in water for 10 minutes until strong and dark.",
      "Churn the tea with butter, milk and a pinch of salt until frothy and well blended.",
      "Knead barley flour with yeast and warm water into a soft dough, let it ferment for a few hours.",
      "Shape into small rounds and bake or pan-cook until lightly browned on both sides.",
      "Serve the khambir warm alongside a cup of gur gur cha."
    ],
    tags: ["Himalayan", "traditional", "warming"],
  },
  {
    id: "ladakh_lunch_chicken_thukpa",
    name: "Chicken Thukpa",
    description: "Hearty hand-pulled noodle soup loaded with vegetables, shredded chicken and warming spices, a staple Ladakhi lunch bowl.",
    cuisineRegion: ["Ladakh"],
    dietType: "nonveg",
    goalTags: ["maintenance", "muscle", "recovery"],
    mealType: ["lunch"],
    prepTime: 15,
    cookTime: 25,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 380, proteinG: 22, carbsG: 45, fatG: 10 },
    ingredients: [
      { id: "ladakh_lunch_chicken_thukpa_wheat_noodles", name: "Wheat noodles", quantity: 150, unit: "g", category: "grain", searchTerms: { zepto: "hakka noodles wheat", instamart: "noodles" } },
      { id: "ladakh_lunch_chicken_thukpa_chicken_boneless", name: "Chicken (boneless)", quantity: 200, unit: "g", category: "protein", searchTerms: { zepto: "boneless chicken", instamart: "chicken boneless" } },
      { id: "ladakh_lunch_chicken_thukpa_carrot", name: "Carrot", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "carrot", instamart: "gajar" } },
      { id: "ladakh_lunch_chicken_thukpa_cabbage", name: "Cabbage", quantity: 100, unit: "g", category: "vegetable", searchTerms: { zepto: "cabbage", instamart: "patta gobi" } },
      { id: "ladakh_lunch_chicken_thukpa_spring_onion", name: "Spring onion", quantity: 2, unit: "piece", category: "vegetable", searchTerms: { zepto: "spring onion", instamart: "hara pyaz" }, optional: true },
      { id: "ladakh_lunch_chicken_thukpa_garlic", name: "Garlic", quantity: 4, unit: "piece", category: "spice", searchTerms: { zepto: "garlic", instamart: "lehsun" } },
      { id: "ladakh_lunch_chicken_thukpa_ginger", name: "Ginger", quantity: 1, unit: "inch", category: "spice", searchTerms: { zepto: "ginger", instamart: "adrak" }, optional: true },
      { id: "ladakh_lunch_chicken_thukpa_soy_sauce", name: "Soy sauce", quantity: 1, unit: "tbsp", category: "other", searchTerms: { zepto: "soy sauce", instamart: "soy sauce" }, optional: true },
      { id: "ladakh_lunch_chicken_thukpa_oil", name: "Oil", quantity: 1, unit: "tbsp", category: "oil", searchTerms: { zepto: "refined sunflower oil", instamart: "khana pakane ka tel" } }
    ],
    steps: [
      "Boil the noodles until just cooked, drain and set aside.",
      "Heat oil, sauté garlic and ginger, then add sliced chicken and cook until browned.",
      "Add carrot and cabbage, stir-fry briefly, then pour in water or stock and bring to a boil.",
      "Season with soy sauce and salt, simmer for 10 minutes until the chicken is cooked through.",
      "Add the boiled noodles to the broth, garnish with spring onion, and serve hot."
    ],
    tags: ["soup", "noodles", "Himalayan"],
  },
  {
    id: "ladakh_snack_vegetable_momos",
    name: "Vegetable Momos",
    description: "Steamed dumplings filled with finely chopped vegetables, served with a fiery tomato-chili dip, Ladakh's favorite snack.",
    cuisineRegion: ["Ladakh"],
    dietType: "veg",
    goalTags: ["maintenance"],
    mealType: ["snack"],
    prepTime: 30,
    cookTime: 20,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 300, proteinG: 9, carbsG: 45, fatG: 8 },
    ingredients: [
      { id: "ladakh_snack_vegetable_momos_refined_flour_maida", name: "Refined flour (maida)", quantity: 200, unit: "g", category: "grain", searchTerms: { zepto: "refined flour maida", instamart: "maida" } },
      { id: "ladakh_snack_vegetable_momos_cabbage", name: "Cabbage", quantity: 150, unit: "g", category: "vegetable", searchTerms: { zepto: "cabbage", instamart: "patta gobi" } },
      { id: "ladakh_snack_vegetable_momos_carrot", name: "Carrot", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "carrot", instamart: "gajar" } },
      { id: "ladakh_snack_vegetable_momos_onion", name: "Onion", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "pyaz" } },
      { id: "ladakh_snack_vegetable_momos_garlic", name: "Garlic", quantity: 3, unit: "piece", category: "spice", searchTerms: { zepto: "garlic", instamart: "lehsun" } },
      { id: "ladakh_snack_vegetable_momos_soy_sauce", name: "Soy sauce", quantity: 1, unit: "tsp", category: "other", searchTerms: { zepto: "soy sauce", instamart: "soy sauce" }, optional: true },
      { id: "ladakh_snack_vegetable_momos_oil", name: "Oil", quantity: 1, unit: "tbsp", category: "oil", searchTerms: { zepto: "refined sunflower oil", instamart: "khana pakane ka tel" } },
      { id: "ladakh_snack_vegetable_momos_tomato", name: "Tomato", quantity: 3, unit: "medium", category: "vegetable", searchTerms: { zepto: "tomato", instamart: "tamatar" } }
    ],
    steps: [
      "Knead maida with water and a little oil into a smooth, firm dough; rest for 20 minutes.",
      "Finely chop cabbage, carrot and onion, sauté briefly with garlic, soy sauce and salt to make the filling.",
      "Roll small dough discs, place a spoonful of filling in the center and pleat to seal into momo shapes.",
      "Steam the momos for 10-12 minutes until the wrappers turn translucent.",
      "Blend tomatoes with dried red chilies and salt to make a spicy dip, and serve alongside."
    ],
    tags: ["steamed", "dumplings", "popular"],
  },
  {
    id: "ladakh_dinner_skyu",
    name: "Skyu",
    description: "Thumb-shaped pasta simmered with root vegetables in a light broth, a traditional one-pot Ladakhi dinner stew.",
    cuisineRegion: ["Ladakh"],
    dietType: "veg",
    goalTags: ["maintenance"],
    mealType: ["dinner"],
    prepTime: 20,
    cookTime: 30,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 350, proteinG: 10, carbsG: 55, fatG: 8 },
    ingredients: [
      { id: "ladakh_dinner_skyu_whole_wheat_flour", name: "Whole wheat flour", quantity: 250, unit: "g", category: "grain", searchTerms: { zepto: "wheat flour atta", instamart: "atta" } },
      { id: "ladakh_dinner_skyu_potato", name: "Potato", quantity: 2, unit: "medium", category: "vegetable", searchTerms: { zepto: "potato", instamart: "aloo" } },
      { id: "ladakh_dinner_skyu_carrot", name: "Carrot", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "carrot", instamart: "gajar" } },
      { id: "ladakh_dinner_skyu_turnip", name: "Turnip", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "turnip", instamart: "shalgam" }, optional: true },
      { id: "ladakh_dinner_skyu_onion", name: "Onion", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "pyaz" } },
      { id: "ladakh_dinner_skyu_garlic", name: "Garlic", quantity: 3, unit: "piece", category: "spice", searchTerms: { zepto: "garlic", instamart: "lehsun" } },
      { id: "ladakh_dinner_skyu_oil", name: "Oil", quantity: 1, unit: "tbsp", category: "oil", searchTerms: { zepto: "refined sunflower oil", instamart: "khana pakane ka tel" } },
      { id: "ladakh_dinner_skyu_salt", name: "Salt", quantity: 1, unit: "tsp", category: "other", searchTerms: { zepto: "iodised salt", instamart: "namak" } }
    ],
    steps: [
      "Knead wheat flour with water into a firm dough; pinch off small pieces and shape into thumb-sized flattened discs.",
      "Heat oil, sauté onion and garlic until fragrant, then add chopped potato, carrot and turnip.",
      "Add water to make a broth, bring to a boil and season with salt.",
      "Drop in the pasta pieces and simmer for 15-20 minutes until the vegetables and dough are cooked through and the stew thickens slightly.",
      "Serve hot in bowls as a complete one-pot meal."
    ],
    tags: ["one-pot", "Himalayan", "wholesome"],
  },
];
