import type { Recipe } from "../types";

// Auto-generated from regional recipe research (South zone).
export const SOUTH_RECIPES: Recipe[] = [
  {
    id: "karnataka_breakfast_rava_idli",
    name: "Rava Idli",
    description: "Soft steamed semolina cakes tempered with mustard seeds, cashews and curry leaves, served with coconut chutney.",
    cuisineRegion: ["Karnataka"],
    dietType: "veg",
    goalTags: ["maintenance", "weight_loss"],
    mealType: ["breakfast"],
    prepTime: 15,
    cookTime: 20,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 260, proteinG: 6, carbsG: 40, fatG: 8 },
    ingredients: [
      { id: "karnataka_breakfast_rava_idli_semolina_rava_sooji", name: "Semolina (rava/sooji)", quantity: 150, unit: "g", category: "grain", searchTerms: { zepto: "semolina rava sooji", instamart: "suji rava" } },
      { id: "karnataka_breakfast_rava_idli_curd_yogurt", name: "Curd (yogurt)", quantity: 150, unit: "g", category: "dairy", searchTerms: { zepto: "curd", instamart: "dahi" } },
      { id: "karnataka_breakfast_rava_idli_carrot", name: "Carrot", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "carrot", instamart: "gajar" }, optional: true },
      { id: "karnataka_breakfast_rava_idli_green_chilli", name: "Green chilli", quantity: 2, unit: "piece", category: "vegetable", searchTerms: { zepto: "green chilli", instamart: "hari mirch" }, optional: true },
      { id: "karnataka_breakfast_rava_idli_mustard_seeds", name: "Mustard seeds", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "mustard seeds", instamart: "rai sarson" }, optional: true },
      { id: "karnataka_breakfast_rava_idli_curry_leaves", name: "Curry leaves", quantity: 8, unit: "piece", category: "spice", searchTerms: { zepto: "curry leaves", instamart: "kadi patta" }, optional: true },
      { id: "karnataka_breakfast_rava_idli_cashew_nuts", name: "Cashew nuts", quantity: 10, unit: "piece", category: "other", searchTerms: { zepto: "cashew nuts", instamart: "kaju" }, optional: true },
      { id: "karnataka_breakfast_rava_idli_eno_fruit_salt_baking_soda", name: "Eno fruit salt / baking soda", quantity: 1, unit: "tsp", category: "other", searchTerms: { zepto: "eno fruit salt", instamart: "eno" } },
      { id: "karnataka_breakfast_rava_idli_ghee", name: "Ghee", quantity: 1, unit: "tbsp", category: "dairy", searchTerms: { zepto: "ghee", instamart: "ghee" } }
    ],
    steps: [
      "Dry roast rava lightly for 3-4 minutes and cool; mix with curd, grated carrot, chopped green chilli and salt to a thick batter, rest 15 minutes.",
      "Heat ghee, splutter mustard seeds, curry leaves and cashews, and fold this tempering into the batter.",
      "Just before steaming, add eno/baking soda and a splash of water, mix gently.",
      "Pour into greased idli moulds and steam for 12-15 minutes until a knife comes out clean.",
      "Serve hot with coconut chutney and sambar."
    ],
    tags: ["steamed", "light", "tiffin", "quick"],
  },
  {
    id: "karnataka_lunch_bisi_bele_bath",
    name: "Bisi Bele Bath",
    description: "A hearty one-pot Mysore-style rice and lentil dish simmered with mixed vegetables and a spicy roasted powder, finished with ghee.",
    cuisineRegion: ["Karnataka"],
    dietType: "veg",
    goalTags: ["maintenance"],
    mealType: ["lunch"],
    prepTime: 15,
    cookTime: 30,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 400, proteinG: 11, carbsG: 62, fatG: 11 },
    ingredients: [
      { id: "karnataka_lunch_bisi_bele_bath_rice", name: "Rice", quantity: 150, unit: "g", category: "grain", searchTerms: { zepto: "rice", instamart: "chawal" } },
      { id: "karnataka_lunch_bisi_bele_bath_toor_dal", name: "Toor dal", quantity: 100, unit: "g", category: "protein", searchTerms: { zepto: "toor dal", instamart: "arhar dal" } },
      { id: "karnataka_lunch_bisi_bele_bath_mixed_vegetables_carrot_beans_peas_potato", name: "Mixed vegetables (carrot, beans, peas, potato)", quantity: 200, unit: "g", category: "vegetable", searchTerms: { zepto: "mixed vegetables", instamart: "mix sabzi" } },
      { id: "karnataka_lunch_bisi_bele_bath_tamarind", name: "Tamarind", quantity: 1, unit: "tbsp", category: "other", searchTerms: { zepto: "tamarind", instamart: "imli" } },
      { id: "karnataka_lunch_bisi_bele_bath_bisi_bele_bath_powder", name: "Bisi bele bath powder", quantity: 2, unit: "tbsp", category: "spice", searchTerms: { zepto: "bisi bele bath masala", instamart: "bisi bele bath masala" } },
      { id: "karnataka_lunch_bisi_bele_bath_peanuts", name: "Peanuts", quantity: 2, unit: "tbsp", category: "other", searchTerms: { zepto: "raw peanuts", instamart: "moongfali" }, optional: true },
      { id: "karnataka_lunch_bisi_bele_bath_ghee", name: "Ghee", quantity: 2, unit: "tbsp", category: "dairy", searchTerms: { zepto: "ghee", instamart: "ghee" } },
      { id: "karnataka_lunch_bisi_bele_bath_curry_leaves", name: "Curry leaves", quantity: 8, unit: "piece", category: "spice", searchTerms: { zepto: "curry leaves", instamart: "kadi patta" }, optional: true },
      { id: "karnataka_lunch_bisi_bele_bath_mustard_seeds", name: "Mustard seeds", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "mustard seeds", instamart: "rai sarson" }, optional: true }
    ],
    steps: [
      "Pressure cook rice and toor dal together with the chopped vegetables until soft and mushy.",
      "Soak tamarind in warm water and extract the pulp; add to the cooked rice-dal mixture along with bisi bele bath powder and salt.",
      "Simmer for 10-12 minutes, adding water to reach a thick, porridge-like consistency.",
      "In a small pan, heat ghee and fry peanuts, mustard seeds and curry leaves; pour this tempering over the bath.",
      "Serve hot with boondi or crisp fried papad on the side."
    ],
    tags: ["one-pot", "comfort", "spicy", "festive"],
  },
  {
    id: "karnataka_snack_mysore_bonda_goli_baje",
    name: "Mysore Bonda (Goli Baje)",
    description: "Deep-fried fluffy dumplings made from a curd-thickened maida batter, a popular Karnataka tea-time snack.",
    cuisineRegion: ["Karnataka"],
    dietType: "veg",
    goalTags: ["maintenance", "weight_loss"],
    mealType: ["snack"],
    prepTime: 15,
    cookTime: 15,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 240, proteinG: 5, carbsG: 24, fatG: 13 },
    ingredients: [
      { id: "karnataka_snack_mysore_bonda_goli_baje_all_purpose_flour_maida", name: "All-purpose flour (maida)", quantity: 150, unit: "g", category: "grain", searchTerms: { zepto: "maida all purpose flour", instamart: "maida" } },
      { id: "karnataka_snack_mysore_bonda_goli_baje_curd_yogurt", name: "Curd (yogurt)", quantity: 100, unit: "g", category: "dairy", searchTerms: { zepto: "curd", instamart: "dahi" } },
      { id: "karnataka_snack_mysore_bonda_goli_baje_green_chilli", name: "Green chilli", quantity: 2, unit: "piece", category: "vegetable", searchTerms: { zepto: "green chilli", instamart: "hari mirch" }, optional: true },
      { id: "karnataka_snack_mysore_bonda_goli_baje_ginger", name: "Ginger", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "ginger", instamart: "adrak" }, optional: true },
      { id: "karnataka_snack_mysore_bonda_goli_baje_curry_leaves", name: "Curry leaves", quantity: 6, unit: "piece", category: "spice", searchTerms: { zepto: "curry leaves", instamart: "kadi patta" }, optional: true },
      { id: "karnataka_snack_mysore_bonda_goli_baje_coriander_leaves", name: "Coriander leaves", quantity: 2, unit: "tbsp", category: "vegetable", searchTerms: { zepto: "coriander leaves", instamart: "dhaniya patta" }, optional: true },
      { id: "karnataka_snack_mysore_bonda_goli_baje_baking_soda", name: "Baking soda", quantity: 0.5, unit: "tsp", category: "other", searchTerms: { zepto: "baking soda", instamart: "baking soda" } },
      { id: "karnataka_snack_mysore_bonda_goli_baje_oil_for_deep_frying", name: "Oil (for deep frying)", quantity: 300, unit: "ml", category: "oil", searchTerms: { zepto: "cooking oil", instamart: "khana pakane ka tel" } }
    ],
    steps: [
      "Whisk maida, curd, chopped green chilli, ginger, curry leaves, coriander and baking soda into a thick, drop-able batter; rest 20 minutes.",
      "Heat oil to medium-hot in a kadai.",
      "Drop small portions of the batter into the oil and fry on medium flame, turning occasionally, until golden brown and cooked through.",
      "Drain on paper towels and serve hot with coconut chutney and filter coffee."
    ],
    tags: ["fried", "tea-time", "street-food"],
  },
  {
    id: "karnataka_dinner_ragi_mudde_with_saaru",
    name: "Ragi Mudde with Saaru",
    description: "Steamed finger-millet balls served with a tangy, spiced lentil-vegetable sambar, a staple rustic Karnataka dinner.",
    cuisineRegion: ["Karnataka"],
    dietType: "veg",
    goalTags: ["maintenance"],
    mealType: ["dinner"],
    prepTime: 10,
    cookTime: 30,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 320, proteinG: 9, carbsG: 56, fatG: 6 },
    ingredients: [
      { id: "karnataka_dinner_ragi_mudde_with_saaru_ragi_finger_millet_flour", name: "Ragi (finger millet) flour", quantity: 150, unit: "g", category: "grain", searchTerms: { zepto: "ragi flour", instamart: "ragi atta" } },
      { id: "karnataka_dinner_ragi_mudde_with_saaru_toor_dal", name: "Toor dal", quantity: 80, unit: "g", category: "protein", searchTerms: { zepto: "toor dal", instamart: "arhar dal" } },
      { id: "karnataka_dinner_ragi_mudde_with_saaru_drumstick", name: "Drumstick", quantity: 1, unit: "piece", category: "vegetable", searchTerms: { zepto: "drumstick", instamart: "saijan phali" }, optional: true },
      { id: "karnataka_dinner_ragi_mudde_with_saaru_onion", name: "Onion", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "pyaz" } },
      { id: "karnataka_dinner_ragi_mudde_with_saaru_tomato", name: "Tomato", quantity: 2, unit: "medium", category: "vegetable", searchTerms: { zepto: "tomato", instamart: "tamatar" } },
      { id: "karnataka_dinner_ragi_mudde_with_saaru_tamarind", name: "Tamarind", quantity: 1, unit: "tbsp", category: "other", searchTerms: { zepto: "tamarind", instamart: "imli" } },
      { id: "karnataka_dinner_ragi_mudde_with_saaru_sambar_powder", name: "Sambar powder", quantity: 2, unit: "tbsp", category: "spice", searchTerms: { zepto: "sambar powder", instamart: "sambar masala" } },
      { id: "karnataka_dinner_ragi_mudde_with_saaru_mustard_seeds", name: "Mustard seeds", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "mustard seeds", instamart: "rai sarson" }, optional: true }
    ],
    steps: [
      "Boil water, gradually stir in ragi flour, cooking and mashing continuously until it forms a smooth, thick, lump-free dough (mudde).",
      "Shape the hot dough into smooth balls using wet hands or a small bowl of water; set aside.",
      "Cook toor dal with drumstick, onion and tomato until soft; add tamarind pulp, sambar powder and salt, simmer 10 minutes.",
      "Temper with mustard seeds in hot oil and pour over the saaru (sambar).",
      "Serve the ragi mudde balls hot alongside the saaru, eating by breaking off small pieces and dunking them in."
    ],
    tags: ["millet", "rustic", "wholesome", "gluten-free"],
  },
  {
    id: "tamil_nadu_breakfast_idli_with_sambar",
    name: "Idli with Sambar",
    description: "Steamed fermented rice-lentil cakes served with a vegetable lentil sambar and coconut chutney, Tamil Nadu's everyday breakfast.",
    cuisineRegion: ["Tamil Nadu"],
    dietType: "veg",
    goalTags: ["maintenance", "weight_loss"],
    mealType: ["breakfast"],
    prepTime: 20,
    cookTime: 25,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 290, proteinG: 9, carbsG: 50, fatG: 6 },
    ingredients: [
      { id: "tamil_nadu_breakfast_idli_with_sambar_idli_rice", name: "Idli rice", quantity: 200, unit: "g", category: "grain", searchTerms: { zepto: "idli rice", instamart: "idli chawal" } },
      { id: "tamil_nadu_breakfast_idli_with_sambar_urad_dal", name: "Urad dal", quantity: 60, unit: "g", category: "protein", searchTerms: { zepto: "urad dal", instamart: "urad dal" } },
      { id: "tamil_nadu_breakfast_idli_with_sambar_fenugreek_seeds", name: "Fenugreek seeds", quantity: 0.5, unit: "tsp", category: "spice", searchTerms: { zepto: "fenugreek seeds", instamart: "methi dana" }, optional: true },
      { id: "tamil_nadu_breakfast_idli_with_sambar_toor_dal", name: "Toor dal", quantity: 80, unit: "g", category: "protein", searchTerms: { zepto: "toor dal", instamart: "arhar dal" } },
      { id: "tamil_nadu_breakfast_idli_with_sambar_mixed_vegetables_drumstick_carrot", name: "Mixed vegetables (drumstick, carrot)", quantity: 150, unit: "g", category: "vegetable", searchTerms: { zepto: "mixed vegetables", instamart: "mix sabzi" }, optional: true },
      { id: "tamil_nadu_breakfast_idli_with_sambar_sambar_powder", name: "Sambar powder", quantity: 2, unit: "tbsp", category: "spice", searchTerms: { zepto: "sambar powder", instamart: "sambar masala" } },
      { id: "tamil_nadu_breakfast_idli_with_sambar_tamarind", name: "Tamarind", quantity: 1, unit: "tbsp", category: "other", searchTerms: { zepto: "tamarind", instamart: "imli" } },
      { id: "tamil_nadu_breakfast_idli_with_sambar_coconut_fresh", name: "Coconut (fresh)", quantity: 0.5, unit: "piece", category: "other", searchTerms: { zepto: "fresh coconut", instamart: "nariyal" } }
    ],
    steps: [
      "Soak rice and urad dal (with fenugreek) separately for 4-6 hours, grind to a smooth batter, mix and ferment overnight.",
      "Pour batter into greased idli moulds and steam for 10-12 minutes until springy.",
      "For sambar, cook toor dal with vegetables until soft, add tamarind pulp, sambar powder and salt, and simmer 15 minutes; temper with mustard seeds and curry leaves.",
      "Grind fresh coconut with green chilli and a little roasted gram into a smooth chutney.",
      "Serve hot idlis with sambar and coconut chutney."
    ],
    tags: ["steamed", "fermented", "tiffin", "light"],
  },
  {
    id: "tamil_nadu_lunch_chettinad_chicken_curry",
    name: "Chettinad Chicken Curry",
    description: "A fiery, aromatic Chettinad-style chicken curry made with freshly ground pepper, star anise and coconut, served with steamed rice.",
    cuisineRegion: ["Tamil Nadu"],
    dietType: "nonveg",
    goalTags: ["maintenance", "muscle", "recovery", "weight_gain"],
    mealType: ["lunch"],
    prepTime: 20,
    cookTime: 35,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 520, proteinG: 32, carbsG: 42, fatG: 22 },
    ingredients: [
      { id: "tamil_nadu_lunch_chettinad_chicken_curry_chicken_curry_cut_bone_in", name: "Chicken (curry cut, bone-in)", quantity: 400, unit: "g", category: "protein", searchTerms: { zepto: "chicken curry cut", instamart: "chicken" } },
      { id: "tamil_nadu_lunch_chettinad_chicken_curry_onion", name: "Onion", quantity: 2, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "pyaz" } },
      { id: "tamil_nadu_lunch_chettinad_chicken_curry_tomato", name: "Tomato", quantity: 2, unit: "medium", category: "vegetable", searchTerms: { zepto: "tomato", instamart: "tamatar" } },
      { id: "tamil_nadu_lunch_chettinad_chicken_curry_coconut_fresh_grated", name: "Coconut (fresh, grated)", quantity: 0.5, unit: "piece", category: "other", searchTerms: { zepto: "fresh coconut", instamart: "nariyal" } },
      { id: "tamil_nadu_lunch_chettinad_chicken_curry_chettinad_masala_fennel_star_anise_pepper_cinnamo", name: "Chettinad masala (fennel, star anise, pepper, cinnamon)", quantity: 2, unit: "tbsp", category: "spice", searchTerms: { zepto: "chettinad masala", instamart: "chettinad masala" } },
      { id: "tamil_nadu_lunch_chettinad_chicken_curry_ginger_garlic_paste", name: "Ginger garlic paste", quantity: 1, unit: "tbsp", category: "spice", searchTerms: { zepto: "ginger garlic paste", instamart: "adrak lahsun paste" } },
      { id: "tamil_nadu_lunch_chettinad_chicken_curry_curry_leaves", name: "Curry leaves", quantity: 10, unit: "piece", category: "spice", searchTerms: { zepto: "curry leaves", instamart: "kadi patta" }, optional: true },
      { id: "tamil_nadu_lunch_chettinad_chicken_curry_rice", name: "Rice", quantity: 150, unit: "g", category: "grain", searchTerms: { zepto: "rice", instamart: "chawal" } },
      { id: "tamil_nadu_lunch_chettinad_chicken_curry_cooking_oil", name: "Cooking oil", quantity: 2, unit: "tbsp", category: "oil", searchTerms: { zepto: "cooking oil", instamart: "khana pakane ka tel" } }
    ],
    steps: [
      "Dry roast fennel, star anise, pepper, cinnamon and dried red chillies, cool, and grind with grated coconut to a coarse paste.",
      "Heat oil, fry curry leaves and sliced onions until golden, add ginger garlic paste and cook off the raw smell.",
      "Add tomatoes and cook until mushy, then add the ground masala paste and cook until oil separates.",
      "Add chicken pieces, salt and a little water; cover and simmer 20-25 minutes until the chicken is tender and the gravy thickens.",
      "Serve hot with steamed rice."
    ],
    tags: ["spicy", "curry", "festive"],
  },
  {
    id: "tamil_nadu_snack_murukku",
    name: "Murukku",
    description: "Crisp, spiral-shaped deep-fried snack made from rice flour and urad dal flour, a classic Tamil Nadu tea-time favourite.",
    cuisineRegion: ["Tamil Nadu"],
    dietType: "veg",
    goalTags: ["maintenance", "weight_loss"],
    mealType: ["snack"],
    prepTime: 20,
    cookTime: 20,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 210, proteinG: 4, carbsG: 22, fatG: 12 },
    ingredients: [
      { id: "tamil_nadu_snack_murukku_rice_flour", name: "Rice flour", quantity: 200, unit: "g", category: "grain", searchTerms: { zepto: "rice flour", instamart: "chawal ka atta" } },
      { id: "tamil_nadu_snack_murukku_urad_dal_flour", name: "Urad dal flour", quantity: 50, unit: "g", category: "protein", searchTerms: { zepto: "urad dal flour", instamart: "urad dal atta" } },
      { id: "tamil_nadu_snack_murukku_butter", name: "Butter", quantity: 2, unit: "tbsp", category: "dairy", searchTerms: { zepto: "butter", instamart: "makhan" } },
      { id: "tamil_nadu_snack_murukku_cumin_seeds", name: "Cumin seeds", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "cumin seeds", instamart: "jeera" }, optional: true },
      { id: "tamil_nadu_snack_murukku_sesame_seeds", name: "Sesame seeds", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "sesame seeds", instamart: "til" }, optional: true },
      { id: "tamil_nadu_snack_murukku_asafoetida", name: "Asafoetida", quantity: 1, unit: "pinch", category: "spice", searchTerms: { zepto: "asafoetida hing", instamart: "hing" }, optional: true },
      { id: "tamil_nadu_snack_murukku_oil_for_deep_frying", name: "Oil (for deep frying)", quantity: 300, unit: "ml", category: "oil", searchTerms: { zepto: "cooking oil", instamart: "khana pakane ka tel" } }
    ],
    steps: [
      "Mix rice flour, urad dal flour, softened butter, cumin, sesame seeds, hing and salt with water into a smooth, pliable dough.",
      "Fill the dough into a murukku press fitted with a star-shaped disc.",
      "Press directly into hot oil in spiral shapes and deep fry on medium heat, turning once, until golden and crisp.",
      "Drain on paper towels and cool completely before storing in an airtight container."
    ],
    tags: ["fried", "crunchy", "festive", "tea-time"],
  },
  {
    id: "tamil_nadu_dinner_kothu_parotta",
    name: "Kothu Parotta",
    description: "Shredded flaky parottas tossed on a hot griddle with scrambled egg, spiced chicken and vegetables, a beloved Tamil Nadu roadside dinner.",
    cuisineRegion: ["Tamil Nadu"],
    dietType: "nonveg",
    goalTags: ["maintenance", "muscle", "recovery", "weight_gain"],
    mealType: ["dinner"],
    prepTime: 15,
    cookTime: 25,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 560, proteinG: 28, carbsG: 58, fatG: 24 },
    ingredients: [
      { id: "tamil_nadu_dinner_kothu_parotta_parotta_frozen_or_fresh", name: "Parotta (frozen or fresh)", quantity: 4, unit: "piece", category: "grain", searchTerms: { zepto: "malabar parotta", instamart: "parotta" } },
      { id: "tamil_nadu_dinner_kothu_parotta_chicken_boneless_chopped", name: "Chicken (boneless, chopped)", quantity: 250, unit: "g", category: "protein", searchTerms: { zepto: "boneless chicken", instamart: "chicken boneless" } },
      { id: "tamil_nadu_dinner_kothu_parotta_egg", name: "Egg", quantity: 2, unit: "piece", category: "protein", searchTerms: { zepto: "eggs", instamart: "anda" }, optional: true },
      { id: "tamil_nadu_dinner_kothu_parotta_onion", name: "Onion", quantity: 2, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "pyaz" } },
      { id: "tamil_nadu_dinner_kothu_parotta_tomato", name: "Tomato", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "tomato", instamart: "tamatar" } },
      { id: "tamil_nadu_dinner_kothu_parotta_ginger_garlic_paste", name: "Ginger garlic paste", quantity: 1, unit: "tbsp", category: "spice", searchTerms: { zepto: "ginger garlic paste", instamart: "adrak lahsun paste" } },
      { id: "tamil_nadu_dinner_kothu_parotta_chilli_powder", name: "Chilli powder", quantity: 1, unit: "tbsp", category: "spice", searchTerms: { zepto: "red chilli powder", instamart: "lal mirch powder" } },
      { id: "tamil_nadu_dinner_kothu_parotta_garam_masala", name: "Garam masala", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "garam masala", instamart: "garam masala" }, optional: true },
      { id: "tamil_nadu_dinner_kothu_parotta_cooking_oil", name: "Cooking oil", quantity: 2, unit: "tbsp", category: "oil", searchTerms: { zepto: "cooking oil", instamart: "khana pakane ka tel" } }
    ],
    steps: [
      "Cook parottas as per package instructions, then shred them into small pieces using two knives or a chopper.",
      "In a pan, heat oil, sauté onions until golden, add ginger garlic paste, tomato, chilli powder and garam masala and cook to a thick masala.",
      "Add chicken and cook through; push to one side, scramble the eggs in the same pan and mix everything together.",
      "Add the shredded parotta and toss vigorously with the masala, chopping and mixing on the hot griddle until well combined and slightly crisp.",
      "Serve hot, optionally with onion raita or a side of salna."
    ],
    tags: ["street-food", "spicy", "hearty"],
  },
  {
    id: "kerala_breakfast_puttu_with_kadala_curry",
    name: "Puttu with Kadala Curry",
    description: "Steamed cylinders of rice flour and coconut layers served with a spiced black chickpea curry, Kerala's iconic breakfast pairing.",
    cuisineRegion: ["Kerala"],
    dietType: "veg",
    goalTags: ["maintenance"],
    mealType: ["breakfast"],
    prepTime: 15,
    cookTime: 25,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 360, proteinG: 12, carbsG: 58, fatG: 8 },
    ingredients: [
      { id: "kerala_breakfast_puttu_with_kadala_curry_puttu_podi_roasted_rice_flour", name: "Puttu podi (roasted rice flour)", quantity: 200, unit: "g", category: "grain", searchTerms: { zepto: "puttu podi rice flour", instamart: "puttu podi" } },
      { id: "kerala_breakfast_puttu_with_kadala_curry_coconut_fresh_grated", name: "Coconut (fresh, grated)", quantity: 100, unit: "g", category: "other", searchTerms: { zepto: "fresh coconut", instamart: "nariyal" } },
      { id: "kerala_breakfast_puttu_with_kadala_curry_black_chickpeas_kala_chana", name: "Black chickpeas (kala chana)", quantity: 150, unit: "g", category: "protein", searchTerms: { zepto: "kala chana black chickpeas", instamart: "kala chana" } },
      { id: "kerala_breakfast_puttu_with_kadala_curry_onion", name: "Onion", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "pyaz" } },
      { id: "kerala_breakfast_puttu_with_kadala_curry_tomato", name: "Tomato", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "tomato", instamart: "tamatar" } },
      { id: "kerala_breakfast_puttu_with_kadala_curry_coconut_oil", name: "Coconut oil", quantity: 1, unit: "tbsp", category: "oil", searchTerms: { zepto: "coconut oil", instamart: "nariyal tel" } },
      { id: "kerala_breakfast_puttu_with_kadala_curry_curry_leaves", name: "Curry leaves", quantity: 8, unit: "piece", category: "spice", searchTerms: { zepto: "curry leaves", instamart: "kadi patta" }, optional: true },
      { id: "kerala_breakfast_puttu_with_kadala_curry_mustard_seeds", name: "Mustard seeds", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "mustard seeds", instamart: "rai sarson" }, optional: true }
    ],
    steps: [
      "Soak black chickpeas overnight and pressure cook until soft.",
      "Mix puttu podi with a little salt and water until it reaches a crumbly, moist texture; layer alternately with grated coconut in a puttu maker/steamer and steam for 10-12 minutes.",
      "For the kadala curry, heat coconut oil, splutter mustard seeds and curry leaves, sauté onions and tomatoes until soft.",
      "Add cooked chickpeas along with turmeric, chilli powder and coriander powder, simmer 10-15 minutes with a little of the cooking water until thickened.",
      "Unmould the puttu cylinders and serve hot with the kadala curry, and a ripe banana on the side if desired."
    ],
    tags: ["steamed", "wholesome", "traditional"],
  },
  {
    id: "kerala_lunch_kerala_fish_curry_meen_curry",
    name: "Kerala Fish Curry (Meen Curry)",
    description: "Tangy, fiery fish curry cooked in a clay-pot style gravy of kokum, coconut and red chillies, served with steamed rice.",
    cuisineRegion: ["Kerala"],
    dietType: "nonveg",
    goalTags: ["maintenance", "muscle", "recovery"],
    mealType: ["lunch"],
    prepTime: 15,
    cookTime: 25,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 470, proteinG: 29, carbsG: 46, fatG: 17 },
    ingredients: [
      { id: "kerala_lunch_kerala_fish_curry_meen_curry_fish_kingfish_or_pomfret_cleaned", name: "Fish (kingfish or pomfret, cleaned)", quantity: 400, unit: "g", category: "protein", searchTerms: { zepto: "fish kingfish", instamart: "machli" } },
      { id: "kerala_lunch_kerala_fish_curry_meen_curry_kokum_kudampuli", name: "Kokum (kudampuli)", quantity: 3, unit: "piece", category: "other", searchTerms: { zepto: "kudampuli kokum", instamart: "kokum" } },
      { id: "kerala_lunch_kerala_fish_curry_meen_curry_shallots", name: "Shallots", quantity: 8, unit: "piece", category: "vegetable", searchTerms: { zepto: "small onion shallots", instamart: "sambar onion" } },
      { id: "kerala_lunch_kerala_fish_curry_meen_curry_coconut_oil", name: "Coconut oil", quantity: 2, unit: "tbsp", category: "oil", searchTerms: { zepto: "coconut oil", instamart: "nariyal tel" } },
      { id: "kerala_lunch_kerala_fish_curry_meen_curry_kashmiri_chilli_powder", name: "Kashmiri chilli powder", quantity: 2, unit: "tbsp", category: "spice", searchTerms: { zepto: "kashmiri red chilli powder", instamart: "kashmiri lal mirch" } },
      { id: "kerala_lunch_kerala_fish_curry_meen_curry_turmeric_powder", name: "Turmeric powder", quantity: 0.5, unit: "tsp", category: "spice", searchTerms: { zepto: "turmeric powder", instamart: "haldi powder" } },
      { id: "kerala_lunch_kerala_fish_curry_meen_curry_curry_leaves", name: "Curry leaves", quantity: 10, unit: "piece", category: "spice", searchTerms: { zepto: "curry leaves", instamart: "kadi patta" }, optional: true },
      { id: "kerala_lunch_kerala_fish_curry_meen_curry_ginger_garlic_paste", name: "Ginger garlic paste", quantity: 1, unit: "tbsp", category: "spice", searchTerms: { zepto: "ginger garlic paste", instamart: "adrak lahsun paste" } },
      { id: "kerala_lunch_kerala_fish_curry_meen_curry_rice", name: "Rice", quantity: 150, unit: "g", category: "grain", searchTerms: { zepto: "rice", instamart: "chawal" } }
    ],
    steps: [
      "Soak kokum pieces in a little warm water and set aside.",
      "Heat coconut oil in a clay pot or heavy pan, sauté shallots and curry leaves until soft, then add ginger garlic paste.",
      "Add chilli powder and turmeric, mix well with a splash of water to avoid burning, then add the soaked kokum with its water.",
      "Bring to a boil, slide in the fish pieces, season with salt and simmer gently for 12-15 minutes without stirring vigorously.",
      "Rest the curry for a few minutes for flavours to deepen, and serve hot with steamed rice."
    ],
    tags: ["tangy", "spicy", "coastal"],
  },
  {
    id: "kerala_snack_kerala_banana_chips_ethakka_upperi",
    name: "Kerala Banana Chips (Ethakka Upperi)",
    description: "Thin slices of raw plantain deep-fried in coconut oil until crisp and golden, a beloved Kerala snack.",
    cuisineRegion: ["Kerala"],
    dietType: "veg",
    goalTags: ["maintenance", "weight_loss"],
    mealType: ["snack"],
    prepTime: 15,
    cookTime: 20,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 260, proteinG: 2, carbsG: 32, fatG: 14 },
    ingredients: [
      { id: "kerala_snack_kerala_banana_chips_ethakka_upperi_raw_plantain_nendran_banana", name: "Raw plantain (nendran banana)", quantity: 3, unit: "piece", category: "fruit", searchTerms: { zepto: "raw banana nendran plantain", instamart: "kachha kela" } },
      { id: "kerala_snack_kerala_banana_chips_ethakka_upperi_coconut_oil", name: "Coconut oil", quantity: 400, unit: "ml", category: "oil", searchTerms: { zepto: "coconut oil", instamart: "nariyal tel" } },
      { id: "kerala_snack_kerala_banana_chips_ethakka_upperi_turmeric_powder", name: "Turmeric powder", quantity: 0.5, unit: "tsp", category: "spice", searchTerms: { zepto: "turmeric powder", instamart: "haldi powder" }, optional: true },
      { id: "kerala_snack_kerala_banana_chips_ethakka_upperi_salt", name: "Salt", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "salt", instamart: "namak" } }
    ],
    steps: [
      "Peel the raw plantains and slice them very thinly using a mandoline slicer directly into a bowl of turmeric-salted water.",
      "Heat coconut oil in a deep kadai until hot.",
      "Pat the slices dry and fry in batches, stirring occasionally, until golden and crisp.",
      "Drain on paper towels, sprinkle with a little extra salt while hot, and cool completely before storing."
    ],
    tags: ["fried", "crunchy", "snack"],
  },
  {
    id: "kerala_dinner_appam_with_chicken_stew",
    name: "Appam with Chicken Stew",
    description: "Lacy, soft-centred fermented rice pancakes paired with a mild coconut-milk chicken stew, a signature Kerala dinner.",
    cuisineRegion: ["Kerala"],
    dietType: "nonveg",
    goalTags: ["maintenance", "muscle", "recovery"],
    mealType: ["dinner"],
    prepTime: 20,
    cookTime: 30,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 440, proteinG: 26, carbsG: 44, fatG: 18 },
    ingredients: [
      { id: "kerala_dinner_appam_with_chicken_stew_raw_rice", name: "Raw rice", quantity: 200, unit: "g", category: "grain", searchTerms: { zepto: "raw rice", instamart: "chawal" } },
      { id: "kerala_dinner_appam_with_chicken_stew_cooked_rice", name: "Cooked rice", quantity: 50, unit: "g", category: "grain", searchTerms: { zepto: "cooked rice", instamart: "pakaya hua chawal" }, optional: true },
      { id: "kerala_dinner_appam_with_chicken_stew_coconut_fresh_grated", name: "Coconut (fresh, grated)", quantity: 100, unit: "g", category: "other", searchTerms: { zepto: "fresh coconut", instamart: "nariyal" } },
      { id: "kerala_dinner_appam_with_chicken_stew_chicken_curry_cut_bone_in", name: "Chicken (curry cut, bone-in)", quantity: 350, unit: "g", category: "protein", searchTerms: { zepto: "chicken curry cut", instamart: "chicken" } },
      { id: "kerala_dinner_appam_with_chicken_stew_coconut_milk", name: "Coconut milk", quantity: 200, unit: "ml", category: "dairy", searchTerms: { zepto: "coconut milk", instamart: "nariyal doodh" } },
      { id: "kerala_dinner_appam_with_chicken_stew_onion", name: "Onion", quantity: 2, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "pyaz" } },
      { id: "kerala_dinner_appam_with_chicken_stew_green_chilli", name: "Green chilli", quantity: 3, unit: "piece", category: "vegetable", searchTerms: { zepto: "green chilli", instamart: "hari mirch" }, optional: true },
      { id: "kerala_dinner_appam_with_chicken_stew_whole_spices_cinnamon_cloves_cardamom", name: "Whole spices (cinnamon, cloves, cardamom)", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "whole garam masala", instamart: "sabut garam masala" }, optional: true },
      { id: "kerala_dinner_appam_with_chicken_stew_curry_leaves", name: "Curry leaves", quantity: 8, unit: "piece", category: "spice", searchTerms: { zepto: "curry leaves", instamart: "kadi patta" }, optional: true }
    ],
    steps: [
      "Soak raw rice for 5-6 hours, grind with cooked rice and grated coconut into a smooth batter, and ferment overnight with a little salt.",
      "Heat a small amount of oil in a pan, add whole spices, sliced onions, green chillies and curry leaves and sauté until soft.",
      "Add chicken pieces and cook for a few minutes, then pour in thin coconut milk and simmer until chicken is nearly cooked; add thick coconut milk at the end and simmer gently without boiling hard.",
      "Heat an appam pan (kadai), pour a ladle of batter and swirl to coat the sides, cover and cook until the edges are lacy and crisp and the centre is soft.",
      "Serve hot appams with the chicken stew."
    ],
    tags: ["coconut", "mild", "comfort", "festive"],
  },
  {
    id: "andhra_pradesh_breakfast_pesarattu_with_allam_chutney",
    name: "Pesarattu with Allam Chutney",
    description: "A protein-rich crepe made from whole green gram batter, crisp at the edges, served with a tangy ginger chutney.",
    cuisineRegion: ["Andhra Pradesh"],
    dietType: "veg",
    goalTags: ["maintenance", "weight_loss"],
    mealType: ["breakfast"],
    prepTime: 20,
    cookTime: 20,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 270, proteinG: 13, carbsG: 38, fatG: 6 },
    ingredients: [
      { id: "andhra_pradesh_breakfast_pesarattu_with_allam_chutney_whole_green_gram_moong_dal_unpeeled", name: "Whole green gram (moong dal, unpeeled)", quantity: 200, unit: "g", category: "protein", searchTerms: { zepto: "whole green moong dal", instamart: "sabut moong dal" } },
      { id: "andhra_pradesh_breakfast_pesarattu_with_allam_chutney_rice", name: "Rice", quantity: 30, unit: "g", category: "grain", searchTerms: { zepto: "rice", instamart: "chawal" }, optional: true },
      { id: "andhra_pradesh_breakfast_pesarattu_with_allam_chutney_ginger", name: "Ginger", quantity: 1, unit: "tbsp", category: "spice", searchTerms: { zepto: "ginger", instamart: "adrak" } },
      { id: "andhra_pradesh_breakfast_pesarattu_with_allam_chutney_green_chilli", name: "Green chilli", quantity: 3, unit: "piece", category: "vegetable", searchTerms: { zepto: "green chilli", instamart: "hari mirch" }, optional: true },
      { id: "andhra_pradesh_breakfast_pesarattu_with_allam_chutney_cumin_seeds", name: "Cumin seeds", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "cumin seeds", instamart: "jeera" }, optional: true },
      { id: "andhra_pradesh_breakfast_pesarattu_with_allam_chutney_onion_finely_chopped_for_topping", name: "Onion (finely chopped, for topping)", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "pyaz" }, optional: true },
      { id: "andhra_pradesh_breakfast_pesarattu_with_allam_chutney_tamarind", name: "Tamarind", quantity: 1, unit: "tsp", category: "other", searchTerms: { zepto: "tamarind", instamart: "imli" } },
      { id: "andhra_pradesh_breakfast_pesarattu_with_allam_chutney_cooking_oil", name: "Cooking oil", quantity: 2, unit: "tbsp", category: "oil", searchTerms: { zepto: "cooking oil", instamart: "khana pakane ka tel" } }
    ],
    steps: [
      "Soak whole green gram and rice together for 5-6 hours, then grind with ginger, green chilli and cumin into a smooth, pourable batter; no fermentation needed.",
      "Heat a griddle, pour a ladle of batter and spread thin into a crepe; sprinkle chopped onions on top and drizzle oil around the edges.",
      "Cook until the base is golden and crisp, then fold in half and remove.",
      "For the chutney, blend ginger, tamarind, dried red chillies, jaggery and salt into a smooth-to-slightly-coarse paste.",
      "Serve hot pesarattu with the allam (ginger) chutney."
    ],
    tags: ["protein-rich", "quick", "tangy"],
  },
  {
    id: "andhra_pradesh_lunch_gongura_mutton",
    name: "Gongura Mutton",
    description: "Tender mutton simmered with tangy sorrel (gongura) leaves and fiery Andhra spices, a signature Andhra lunch dish served with rice.",
    cuisineRegion: ["Andhra Pradesh"],
    dietType: "nonveg",
    goalTags: ["maintenance", "muscle", "recovery", "weight_gain"],
    mealType: ["lunch"],
    prepTime: 20,
    cookTime: 45,
    servings: 2,
    difficulty: "hard",
    nutrition: { calories: 560, proteinG: 34, carbsG: 44, fatG: 26 },
    ingredients: [
      { id: "andhra_pradesh_lunch_gongura_mutton_mutton_bone_in_curry_cut", name: "Mutton (bone-in, curry cut)", quantity: 400, unit: "g", category: "protein", searchTerms: { zepto: "mutton curry cut", instamart: "mutton" } },
      { id: "andhra_pradesh_lunch_gongura_mutton_gongura_leaves_sorrel_leaves", name: "Gongura leaves (sorrel leaves)", quantity: 150, unit: "g", category: "vegetable", searchTerms: { zepto: "gongura leaves", instamart: "gongura" } },
      { id: "andhra_pradesh_lunch_gongura_mutton_onion", name: "Onion", quantity: 2, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "pyaz" } },
      { id: "andhra_pradesh_lunch_gongura_mutton_ginger_garlic_paste", name: "Ginger garlic paste", quantity: 1.5, unit: "tbsp", category: "spice", searchTerms: { zepto: "ginger garlic paste", instamart: "adrak lahsun paste" } },
      { id: "andhra_pradesh_lunch_gongura_mutton_red_chilli_powder", name: "Red chilli powder", quantity: 2, unit: "tbsp", category: "spice", searchTerms: { zepto: "red chilli powder", instamart: "lal mirch powder" } },
      { id: "andhra_pradesh_lunch_gongura_mutton_coriander_powder", name: "Coriander powder", quantity: 1, unit: "tbsp", category: "spice", searchTerms: { zepto: "coriander powder", instamart: "dhaniya powder" } },
      { id: "andhra_pradesh_lunch_gongura_mutton_green_chilli", name: "Green chilli", quantity: 3, unit: "piece", category: "vegetable", searchTerms: { zepto: "green chilli", instamart: "hari mirch" }, optional: true },
      { id: "andhra_pradesh_lunch_gongura_mutton_cooking_oil", name: "Cooking oil", quantity: 3, unit: "tbsp", category: "oil", searchTerms: { zepto: "cooking oil", instamart: "khana pakane ka tel" } },
      { id: "andhra_pradesh_lunch_gongura_mutton_rice", name: "Rice", quantity: 150, unit: "g", category: "grain", searchTerms: { zepto: "rice", instamart: "chawal" } }
    ],
    steps: [
      "Wash gongura leaves and cook them down with a splash of water until wilted and pulpy; set aside.",
      "Pressure cook mutton with turmeric and salt until about 70% tender.",
      "Heat oil, sauté onions until golden, add ginger garlic paste, green chillies, chilli powder and coriander powder, and cook until oil separates.",
      "Add the cooked mutton along with its stock and simmer until fully tender.",
      "Stir in the cooked gongura pulp and simmer for 10 more minutes until the flavours meld and the gravy thickens.",
      "Serve hot with steamed rice."
    ],
    tags: ["spicy", "tangy", "festive"],
  },
  {
    id: "andhra_pradesh_snack_mirchi_bajji",
    name: "Mirchi Bajji",
    description: "Large mild green chillies stuffed with a tangy spiced filling, dipped in gram flour batter and deep-fried, a favourite Andhra street snack.",
    cuisineRegion: ["Andhra Pradesh"],
    dietType: "veg",
    goalTags: ["maintenance", "weight_loss"],
    mealType: ["snack"],
    prepTime: 15,
    cookTime: 20,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 230, proteinG: 5, carbsG: 24, fatG: 13 },
    ingredients: [
      { id: "andhra_pradesh_snack_mirchi_bajji_bajji_chillies_large_mild_green_chillies", name: "Bajji chillies (large mild green chillies)", quantity: 6, unit: "piece", category: "vegetable", searchTerms: { zepto: "bajji mirchi green chilli", instamart: "bajji mirch" } },
      { id: "andhra_pradesh_snack_mirchi_bajji_gram_flour_besan", name: "Gram flour (besan)", quantity: 150, unit: "g", category: "grain", searchTerms: { zepto: "besan gram flour", instamart: "besan" } },
      { id: "andhra_pradesh_snack_mirchi_bajji_rice_flour", name: "Rice flour", quantity: 2, unit: "tbsp", category: "grain", searchTerms: { zepto: "rice flour", instamart: "chawal ka atta" }, optional: true },
      { id: "andhra_pradesh_snack_mirchi_bajji_tamarind", name: "Tamarind", quantity: 1, unit: "tbsp", category: "other", searchTerms: { zepto: "tamarind", instamart: "imli" }, optional: true },
      { id: "andhra_pradesh_snack_mirchi_bajji_roasted_peanuts_for_stuffing_crushed", name: "Roasted peanuts (for stuffing, crushed)", quantity: 3, unit: "tbsp", category: "other", searchTerms: { zepto: "roasted peanuts", instamart: "bhuni moongfali" }, optional: true },
      { id: "andhra_pradesh_snack_mirchi_bajji_cumin_seeds", name: "Cumin seeds", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "cumin seeds", instamart: "jeera" }, optional: true },
      { id: "andhra_pradesh_snack_mirchi_bajji_oil_for_deep_frying", name: "Oil (for deep frying)", quantity: 300, unit: "ml", category: "oil", searchTerms: { zepto: "cooking oil", instamart: "khana pakane ka tel" } }
    ],
    steps: [
      "Slit the chillies lengthwise and remove seeds; stuff with a mix of crushed roasted peanuts, tamarind, cumin and salt.",
      "Make a thick batter with gram flour, rice flour, a pinch of turmeric, salt and water.",
      "Dip each stuffed chilli into the batter, coating well.",
      "Deep fry in hot oil until golden and crisp on the outside.",
      "Drain and serve hot with tamarind or coconut chutney."
    ],
    tags: ["fried", "spicy", "street-food"],
  },
  {
    id: "andhra_pradesh_dinner_gutti_vankaya_kura",
    name: "Gutti Vankaya Kura",
    description: "Baby brinjals stuffed with a roasted peanut-sesame-coconut masala, simmered in a spicy tamarind gravy, a beloved Andhra dinner curry.",
    cuisineRegion: ["Andhra Pradesh"],
    dietType: "veg",
    goalTags: ["maintenance"],
    mealType: ["dinner"],
    prepTime: 20,
    cookTime: 30,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 340, proteinG: 8, carbsG: 40, fatG: 16 },
    ingredients: [
      { id: "andhra_pradesh_dinner_gutti_vankaya_kura_baby_brinjal_eggplant", name: "Baby brinjal (eggplant)", quantity: 300, unit: "g", category: "vegetable", searchTerms: { zepto: "baby brinjal", instamart: "choti baingan" } },
      { id: "andhra_pradesh_dinner_gutti_vankaya_kura_peanuts", name: "Peanuts", quantity: 3, unit: "tbsp", category: "other", searchTerms: { zepto: "raw peanuts", instamart: "moongfali" } },
      { id: "andhra_pradesh_dinner_gutti_vankaya_kura_sesame_seeds", name: "Sesame seeds", quantity: 2, unit: "tbsp", category: "spice", searchTerms: { zepto: "sesame seeds", instamart: "til" } },
      { id: "andhra_pradesh_dinner_gutti_vankaya_kura_coconut_fresh_or_desiccated", name: "Coconut (fresh or desiccated)", quantity: 3, unit: "tbsp", category: "other", searchTerms: { zepto: "fresh coconut", instamart: "nariyal" }, optional: true },
      { id: "andhra_pradesh_dinner_gutti_vankaya_kura_tamarind", name: "Tamarind", quantity: 1, unit: "tbsp", category: "other", searchTerms: { zepto: "tamarind", instamart: "imli" } },
      { id: "andhra_pradesh_dinner_gutti_vankaya_kura_onion", name: "Onion", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "pyaz" } },
      { id: "andhra_pradesh_dinner_gutti_vankaya_kura_red_chilli_powder", name: "Red chilli powder", quantity: 1, unit: "tbsp", category: "spice", searchTerms: { zepto: "red chilli powder", instamart: "lal mirch powder" } },
      { id: "andhra_pradesh_dinner_gutti_vankaya_kura_cooking_oil", name: "Cooking oil", quantity: 3, unit: "tbsp", category: "oil", searchTerms: { zepto: "cooking oil", instamart: "khana pakane ka tel" } },
      { id: "andhra_pradesh_dinner_gutti_vankaya_kura_rice", name: "Rice", quantity: 150, unit: "g", category: "grain", searchTerms: { zepto: "rice", instamart: "chawal" }, optional: true }
    ],
    steps: [
      "Dry roast peanuts, sesame seeds and coconut, then grind with chilli powder, tamarind and salt into a thick paste.",
      "Slit brinjals into quarters keeping the stem intact, and stuff generously with the ground masala paste.",
      "Heat oil, sauté chopped onions until golden, then place the stuffed brinjals in gently and sauté for a few minutes.",
      "Add any leftover masala paste with a little water, cover and cook on low heat until the brinjals are tender.",
      "Simmer uncovered briefly to thicken the gravy, and serve hot with steamed rice or roti."
    ],
    tags: ["stuffed", "spicy", "festive"],
  },
  {
    id: "telangana_breakfast_jonna_rotte_with_vankaya_pachadi",
    name: "Jonna Rotte with Vankaya Pachadi",
    description: "Rustic sorghum flatbreads paired with a smoky roasted brinjal chutney, a traditional dryland Telangana breakfast.",
    cuisineRegion: ["Telangana"],
    dietType: "veg",
    goalTags: ["maintenance", "weight_loss"],
    mealType: ["breakfast"],
    prepTime: 15,
    cookTime: 20,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 290, proteinG: 7, carbsG: 50, fatG: 7 },
    ingredients: [
      { id: "telangana_breakfast_jonna_rotte_with_vankaya_pachadi_jowar_flour_sorghum_flour", name: "Jowar flour (sorghum flour)", quantity: 200, unit: "g", category: "grain", searchTerms: { zepto: "jowar flour sorghum atta", instamart: "jowar atta" } },
      { id: "telangana_breakfast_jonna_rotte_with_vankaya_pachadi_brinjal_large", name: "Brinjal (large)", quantity: 1, unit: "large", category: "vegetable", searchTerms: { zepto: "brinjal eggplant", instamart: "baingan" } },
      { id: "telangana_breakfast_jonna_rotte_with_vankaya_pachadi_green_chilli", name: "Green chilli", quantity: 3, unit: "piece", category: "vegetable", searchTerms: { zepto: "green chilli", instamart: "hari mirch" }, optional: true },
      { id: "telangana_breakfast_jonna_rotte_with_vankaya_pachadi_garlic", name: "Garlic", quantity: 4, unit: "piece", category: "spice", searchTerms: { zepto: "garlic", instamart: "lahsun" }, optional: true },
      { id: "telangana_breakfast_jonna_rotte_with_vankaya_pachadi_tamarind", name: "Tamarind", quantity: 1, unit: "tsp", category: "other", searchTerms: { zepto: "tamarind", instamart: "imli" }, optional: true },
      { id: "telangana_breakfast_jonna_rotte_with_vankaya_pachadi_onion_for_chutney", name: "Onion (for chutney)", quantity: 1, unit: "small", category: "vegetable", searchTerms: { zepto: "onion", instamart: "pyaz" }, optional: true },
      { id: "telangana_breakfast_jonna_rotte_with_vankaya_pachadi_cooking_oil", name: "Cooking oil", quantity: 1, unit: "tbsp", category: "oil", searchTerms: { zepto: "cooking oil", instamart: "khana pakane ka tel" } }
    ],
    steps: [
      "Knead jowar flour with hot water and a pinch of salt into a soft dough; pat into thin rounds directly on a damp cloth or banana leaf.",
      "Cook the flattened rotte on a hot tawa on both sides until light brown spots appear and it is fully cooked.",
      "Roast the whole brinjal directly over a flame or in the oven until the skin chars and the flesh softens; peel and mash.",
      "Mix the mashed brinjal with chopped green chilli, garlic, onion, tamarind and salt into a coarse chutney (pachadi).",
      "Serve the hot jonna rotte with a dollop of vankaya pachadi and a drizzle of oil."
    ],
    tags: ["millet", "rustic", "gluten-free", "wholesome"],
  },
  {
    id: "telangana_lunch_hyderabadi_chicken_biryani",
    name: "Hyderabadi Chicken Biryani",
    description: "Fragrant basmati rice layered and dum-cooked with marinated chicken, fried onions and saffron, Telangana's most iconic lunch dish.",
    cuisineRegion: ["Telangana"],
    dietType: "nonveg",
    goalTags: ["maintenance", "muscle", "recovery", "weight_gain"],
    mealType: ["lunch"],
    prepTime: 30,
    cookTime: 45,
    servings: 2,
    difficulty: "hard",
    nutrition: { calories: 610, proteinG: 31, carbsG: 66, fatG: 24 },
    ingredients: [
      { id: "telangana_lunch_hyderabadi_chicken_biryani_basmati_rice", name: "Basmati rice", quantity: 200, unit: "g", category: "grain", searchTerms: { zepto: "basmati rice", instamart: "basmati chawal" } },
      { id: "telangana_lunch_hyderabadi_chicken_biryani_chicken_curry_cut_bone_in", name: "Chicken (curry cut, bone-in)", quantity: 400, unit: "g", category: "protein", searchTerms: { zepto: "chicken curry cut", instamart: "chicken" } },
      { id: "telangana_lunch_hyderabadi_chicken_biryani_curd_yogurt", name: "Curd (yogurt)", quantity: 150, unit: "g", category: "dairy", searchTerms: { zepto: "curd", instamart: "dahi" } },
      { id: "telangana_lunch_hyderabadi_chicken_biryani_fried_onions_birista", name: "Fried onions (birista)", quantity: 100, unit: "g", category: "vegetable", searchTerms: { zepto: "fried onions birista", instamart: "fried onion" } },
      { id: "telangana_lunch_hyderabadi_chicken_biryani_ginger_garlic_paste", name: "Ginger garlic paste", quantity: 1.5, unit: "tbsp", category: "spice", searchTerms: { zepto: "ginger garlic paste", instamart: "adrak lahsun paste" } },
      { id: "telangana_lunch_hyderabadi_chicken_biryani_biryani_masala", name: "Biryani masala", quantity: 2, unit: "tbsp", category: "spice", searchTerms: { zepto: "biryani masala", instamart: "biryani masala" } },
      { id: "telangana_lunch_hyderabadi_chicken_biryani_mint_leaves", name: "Mint leaves", quantity: 0.5, unit: "cup", category: "vegetable", searchTerms: { zepto: "mint leaves", instamart: "pudina" }, optional: true },
      { id: "telangana_lunch_hyderabadi_chicken_biryani_saffron", name: "Saffron", quantity: 1, unit: "pinch", category: "spice", searchTerms: { zepto: "saffron kesar", instamart: "kesar" }, optional: true },
      { id: "telangana_lunch_hyderabadi_chicken_biryani_ghee", name: "Ghee", quantity: 2, unit: "tbsp", category: "dairy", searchTerms: { zepto: "ghee", instamart: "ghee" } }
    ],
    steps: [
      "Marinate chicken with curd, ginger garlic paste, biryani masala, half the fried onions and mint for at least 1 hour.",
      "Parboil basmati rice with whole spices until 70% cooked, then drain.",
      "Layer the marinated chicken in a heavy pot, top with the parboiled rice, remaining fried onions, saffron-soaked milk and ghee.",
      "Cover tightly with a lid (seal with dough if needed) and cook on dum (low heat) for 25-30 minutes.",
      "Rest for 10 minutes, then gently fluff and mix the layers before serving hot with raita."
    ],
    tags: ["festive", "aromatic", "dum", "spicy"],
  },
  {
    id: "telangana_snack_osmania_biscuit",
    name: "Osmania Biscuit",
    description: "Buttery, slightly salty-sweet Hyderabadi tea biscuits, a beloved Telangana bakery snack traditionally paired with Irani chai.",
    cuisineRegion: ["Telangana"],
    dietType: "veg",
    goalTags: ["maintenance", "weight_loss"],
    mealType: ["snack"],
    prepTime: 20,
    cookTime: 20,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 190, proteinG: 3, carbsG: 24, fatG: 9 },
    ingredients: [
      { id: "telangana_snack_osmania_biscuit_all_purpose_flour_maida", name: "All-purpose flour (maida)", quantity: 200, unit: "g", category: "grain", searchTerms: { zepto: "maida all purpose flour", instamart: "maida" } },
      { id: "telangana_snack_osmania_biscuit_butter", name: "Butter", quantity: 100, unit: "g", category: "dairy", searchTerms: { zepto: "butter", instamart: "makhan" } },
      { id: "telangana_snack_osmania_biscuit_powdered_sugar", name: "Powdered sugar", quantity: 60, unit: "g", category: "other", searchTerms: { zepto: "powdered sugar icing sugar", instamart: "cheeni powder" } },
      { id: "telangana_snack_osmania_biscuit_milk_powder", name: "Milk powder", quantity: 2, unit: "tbsp", category: "dairy", searchTerms: { zepto: "milk powder", instamart: "milk powder" }, optional: true },
      { id: "telangana_snack_osmania_biscuit_baking_powder", name: "Baking powder", quantity: 0.5, unit: "tsp", category: "other", searchTerms: { zepto: "baking powder", instamart: "baking powder" } },
      { id: "telangana_snack_osmania_biscuit_salt", name: "Salt", quantity: 1, unit: "pinch", category: "spice", searchTerms: { zepto: "salt", instamart: "namak" } },
      { id: "telangana_snack_osmania_biscuit_milk_for_glazing", name: "Milk (for glazing)", quantity: 2, unit: "tbsp", category: "dairy", searchTerms: { zepto: "milk", instamart: "doodh" }, optional: true }
    ],
    steps: [
      "Cream butter and powdered sugar together until light and fluffy.",
      "Sift in maida, milk powder, baking powder and a pinch of salt, and bring together into a soft dough without overworking it.",
      "Roll out to about 1 cm thickness and cut into round biscuits; brush tops lightly with milk.",
      "Bake in a preheated oven at 170°C for 15-18 minutes until the edges turn light golden.",
      "Cool completely on a wire rack before serving with hot Irani chai."
    ],
    tags: ["baked", "tea-time", "sweet-salty"],
  },
  {
    id: "telangana_dinner_bagara_baingan",
    name: "Bagara Baingan",
    description: "Small brinjals simmered in a rich tamarind, peanut and sesame gravy, a signature Hyderabadi-Telangana dinner curry.",
    cuisineRegion: ["Telangana"],
    dietType: "veg",
    goalTags: ["maintenance"],
    mealType: ["dinner"],
    prepTime: 20,
    cookTime: 30,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 360, proteinG: 7, carbsG: 46, fatG: 16 },
    ingredients: [
      { id: "telangana_dinner_bagara_baingan_baby_brinjal_eggplant", name: "Baby brinjal (eggplant)", quantity: 300, unit: "g", category: "vegetable", searchTerms: { zepto: "baby brinjal", instamart: "choti baingan" } },
      { id: "telangana_dinner_bagara_baingan_peanuts", name: "Peanuts", quantity: 3, unit: "tbsp", category: "other", searchTerms: { zepto: "raw peanuts", instamart: "moongfali" } },
      { id: "telangana_dinner_bagara_baingan_sesame_seeds", name: "Sesame seeds", quantity: 2, unit: "tbsp", category: "spice", searchTerms: { zepto: "sesame seeds", instamart: "til" } },
      { id: "telangana_dinner_bagara_baingan_desiccated_coconut", name: "Desiccated coconut", quantity: 2, unit: "tbsp", category: "other", searchTerms: { zepto: "desiccated coconut", instamart: "nariyal burada" }, optional: true },
      { id: "telangana_dinner_bagara_baingan_tamarind", name: "Tamarind", quantity: 1.5, unit: "tbsp", category: "other", searchTerms: { zepto: "tamarind", instamart: "imli" } },
      { id: "telangana_dinner_bagara_baingan_onion", name: "Onion", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "pyaz" } },
      { id: "telangana_dinner_bagara_baingan_red_chilli_powder", name: "Red chilli powder", quantity: 1, unit: "tbsp", category: "spice", searchTerms: { zepto: "red chilli powder", instamart: "lal mirch powder" } },
      { id: "telangana_dinner_bagara_baingan_cooking_oil", name: "Cooking oil", quantity: 3, unit: "tbsp", category: "oil", searchTerms: { zepto: "cooking oil", instamart: "khana pakane ka tel" } },
      { id: "telangana_dinner_bagara_baingan_rice", name: "Rice", quantity: 150, unit: "g", category: "grain", searchTerms: { zepto: "rice", instamart: "chawal" }, optional: true }
    ],
    steps: [
      "Dry roast peanuts, sesame seeds and coconut, cool, and grind to a smooth paste with a little water.",
      "Slit the brinjals into quarters keeping the stem intact.",
      "Heat oil, fry the brinjals lightly until just softened and set aside; in the same oil sauté sliced onions until golden.",
      "Add the ground peanut-sesame paste, tamarind pulp, chilli powder and salt, and cook until oil separates.",
      "Return the brinjals to the pan, add water to loosen the gravy, cover and simmer until fully tender.",
      "Serve hot with steamed rice."
    ],
    tags: ["nutty", "tangy", "festive"],
  },
  {
    id: "puducherry_breakfast_pondicherry_bonda_soup",
    name: "Pondicherry Bonda Soup",
    description: "Crisp deep-fried lentil bonda dunked in a piping hot, spiced vegetable-tamarind soup, a much-loved Puducherry breakfast street food.",
    cuisineRegion: ["Puducherry"],
    dietType: "veg",
    goalTags: ["maintenance", "weight_loss"],
    mealType: ["breakfast"],
    prepTime: 20,
    cookTime: 25,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 260, proteinG: 7, carbsG: 34, fatG: 10 },
    ingredients: [
      { id: "puducherry_breakfast_pondicherry_bonda_soup_urad_dal", name: "Urad dal", quantity: 150, unit: "g", category: "protein", searchTerms: { zepto: "urad dal", instamart: "urad dal" } },
      { id: "puducherry_breakfast_pondicherry_bonda_soup_onion", name: "Onion", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "pyaz" } },
      { id: "puducherry_breakfast_pondicherry_bonda_soup_carrot", name: "Carrot", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "carrot", instamart: "gajar" }, optional: true },
      { id: "puducherry_breakfast_pondicherry_bonda_soup_tomato", name: "Tomato", quantity: 2, unit: "medium", category: "vegetable", searchTerms: { zepto: "tomato", instamart: "tamatar" } },
      { id: "puducherry_breakfast_pondicherry_bonda_soup_toor_dal", name: "Toor dal", quantity: 50, unit: "g", category: "protein", searchTerms: { zepto: "toor dal", instamart: "arhar dal" } },
      { id: "puducherry_breakfast_pondicherry_bonda_soup_tamarind", name: "Tamarind", quantity: 1, unit: "tbsp", category: "other", searchTerms: { zepto: "tamarind", instamart: "imli" } },
      { id: "puducherry_breakfast_pondicherry_bonda_soup_sambar_powder", name: "Sambar powder", quantity: 1, unit: "tbsp", category: "spice", searchTerms: { zepto: "sambar powder", instamart: "sambar masala" } },
      { id: "puducherry_breakfast_pondicherry_bonda_soup_oil_for_deep_frying", name: "Oil (for deep frying)", quantity: 300, unit: "ml", category: "oil", searchTerms: { zepto: "cooking oil", instamart: "khana pakane ka tel" } }
    ],
    steps: [
      "Soak and grind urad dal into a thick, fluffy batter with chopped onion, green chilli and salt; shape into small balls and deep fry until golden (ulundu bonda).",
      "Cook toor dal with diced carrot and tomato until soft, then mash lightly.",
      "Add tamarind pulp, sambar powder and salt, and simmer into a thin, well-spiced soup.",
      "Temper with mustard seeds and curry leaves and pour into the soup.",
      "Serve the hot bonda soup in a bowl with 2-3 bondas dunked in, to be broken and eaten with a spoon."
    ],
    tags: ["street-food", "comfort", "spiced"],
  },
  {
    id: "puducherry_lunch_pondicherry_meen_kuzhambu",
    name: "Pondicherry Meen Kuzhambu",
    description: "A Franco-Tamil coastal fish curry from Puducherry, simmered with tamarind, coconut and country spices, served with rice.",
    cuisineRegion: ["Puducherry"],
    dietType: "nonveg",
    goalTags: ["maintenance", "muscle", "recovery"],
    mealType: ["lunch"],
    prepTime: 15,
    cookTime: 25,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 470, proteinG: 28, carbsG: 46, fatG: 17 },
    ingredients: [
      { id: "puducherry_lunch_pondicherry_meen_kuzhambu_fish_seer_fish_or_sardines_cleaned", name: "Fish (seer fish or sardines, cleaned)", quantity: 400, unit: "g", category: "protein", searchTerms: { zepto: "fish seer fish", instamart: "machli" } },
      { id: "puducherry_lunch_pondicherry_meen_kuzhambu_tamarind", name: "Tamarind", quantity: 2, unit: "tbsp", category: "other", searchTerms: { zepto: "tamarind", instamart: "imli" } },
      { id: "puducherry_lunch_pondicherry_meen_kuzhambu_shallots", name: "Shallots", quantity: 8, unit: "piece", category: "vegetable", searchTerms: { zepto: "small onion shallots", instamart: "sambar onion" } },
      { id: "puducherry_lunch_pondicherry_meen_kuzhambu_tomato", name: "Tomato", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "tomato", instamart: "tamatar" } },
      { id: "puducherry_lunch_pondicherry_meen_kuzhambu_coconut_fresh_grated", name: "Coconut (fresh, grated)", quantity: 3, unit: "tbsp", category: "other", searchTerms: { zepto: "fresh coconut", instamart: "nariyal" }, optional: true },
      { id: "puducherry_lunch_pondicherry_meen_kuzhambu_red_chilli_powder", name: "Red chilli powder", quantity: 1.5, unit: "tbsp", category: "spice", searchTerms: { zepto: "red chilli powder", instamart: "lal mirch powder" } },
      { id: "puducherry_lunch_pondicherry_meen_kuzhambu_fenugreek_seeds", name: "Fenugreek seeds", quantity: 0.25, unit: "tsp", category: "spice", searchTerms: { zepto: "fenugreek seeds", instamart: "methi dana" }, optional: true },
      { id: "puducherry_lunch_pondicherry_meen_kuzhambu_curry_leaves", name: "Curry leaves", quantity: 10, unit: "piece", category: "spice", searchTerms: { zepto: "curry leaves", instamart: "kadi patta" }, optional: true },
      { id: "puducherry_lunch_pondicherry_meen_kuzhambu_rice", name: "Rice", quantity: 150, unit: "g", category: "grain", searchTerms: { zepto: "rice", instamart: "chawal" } }
    ],
    steps: [
      "Soak tamarind in warm water and extract a thick pulp.",
      "Heat oil, splutter fenugreek seeds and curry leaves, sauté shallots and tomato until soft.",
      "Add chilli powder and a paste of ground coconut, cook briefly, then pour in the tamarind water.",
      "Bring to a boil, season with salt, and simmer for 8-10 minutes to cook out the raw tamarind taste.",
      "Gently slide in the fish pieces and simmer without stirring for 10-12 minutes until cooked through and the gravy thickens.",
      "Serve hot with steamed rice."
    ],
    tags: ["coastal", "tangy", "spicy"],
  },
  {
    id: "puducherry_snack_pondicherry_french_toast",
    name: "Pondicherry French Toast",
    description: "Café-style egg-dipped pan-fried bread with a hint of vanilla and sugar, reflecting Puducherry's French colonial bakery legacy.",
    cuisineRegion: ["Puducherry"],
    dietType: "egg",
    goalTags: ["maintenance", "weight_loss"],
    mealType: ["snack"],
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 280, proteinG: 9, carbsG: 30, fatG: 13 },
    ingredients: [
      { id: "puducherry_snack_pondicherry_french_toast_bread_slices", name: "Bread slices", quantity: 4, unit: "piece", category: "grain", searchTerms: { zepto: "white bread sandwich bread", instamart: "bread" } },
      { id: "puducherry_snack_pondicherry_french_toast_egg", name: "Egg", quantity: 2, unit: "piece", category: "protein", searchTerms: { zepto: "eggs", instamart: "anda" } },
      { id: "puducherry_snack_pondicherry_french_toast_milk", name: "Milk", quantity: 60, unit: "ml", category: "dairy", searchTerms: { zepto: "milk", instamart: "doodh" } },
      { id: "puducherry_snack_pondicherry_french_toast_sugar", name: "Sugar", quantity: 2, unit: "tbsp", category: "other", searchTerms: { zepto: "sugar", instamart: "cheeni" } },
      { id: "puducherry_snack_pondicherry_french_toast_vanilla_essence", name: "Vanilla essence", quantity: 0.5, unit: "tsp", category: "other", searchTerms: { zepto: "vanilla essence", instamart: "vanilla essence" }, optional: true },
      { id: "puducherry_snack_pondicherry_french_toast_butter", name: "Butter", quantity: 2, unit: "tbsp", category: "dairy", searchTerms: { zepto: "butter", instamart: "makhan" } },
      { id: "puducherry_snack_pondicherry_french_toast_cinnamon_powder", name: "Cinnamon powder", quantity: 0.25, unit: "tsp", category: "spice", searchTerms: { zepto: "cinnamon powder", instamart: "dalchini powder" }, optional: true }
    ],
    steps: [
      "Whisk together eggs, milk, sugar, vanilla essence and cinnamon in a wide shallow bowl.",
      "Dip each bread slice into the mixture, coating both sides well without oversoaking.",
      "Heat butter on a griddle or pan over medium heat.",
      "Pan-fry the soaked bread slices for 2-3 minutes on each side until golden brown and set.",
      "Serve warm with a drizzle of honey or a dusting of powdered sugar, café-style."
    ],
    tags: ["cafe-style", "sweet", "quick", "fusion"],
  },
  {
    id: "puducherry_dinner_uppu_kari_pondicherry_mutton_pepper_fry",
    name: "Uppu Kari (Pondicherry Mutton Pepper Fry)",
    description: "A dry, richly spiced mutton pepper fry considered a specialty of Puducherry's Tamil kitchens, traditionally served with rice or parotta.",
    cuisineRegion: ["Puducherry"],
    dietType: "nonveg",
    goalTags: ["maintenance", "muscle", "recovery", "weight_gain"],
    mealType: ["dinner"],
    prepTime: 20,
    cookTime: 40,
    servings: 2,
    difficulty: "hard",
    nutrition: { calories: 430, proteinG: 32, carbsG: 10, fatG: 28 },
    ingredients: [
      { id: "puducherry_dinner_uppu_kari_pondicherry_mutton_pepper_fry_mutton_bone_in_small_pieces", name: "Mutton (bone-in, small pieces)", quantity: 400, unit: "g", category: "protein", searchTerms: { zepto: "mutton curry cut", instamart: "mutton" } },
      { id: "puducherry_dinner_uppu_kari_pondicherry_mutton_pepper_fry_onion", name: "Onion", quantity: 2, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "pyaz" } },
      { id: "puducherry_dinner_uppu_kari_pondicherry_mutton_pepper_fry_black_pepper_crushed", name: "Black pepper (crushed)", quantity: 1.5, unit: "tbsp", category: "spice", searchTerms: { zepto: "black pepper", instamart: "kali mirch" } },
      { id: "puducherry_dinner_uppu_kari_pondicherry_mutton_pepper_fry_ginger_garlic_paste", name: "Ginger garlic paste", quantity: 1.5, unit: "tbsp", category: "spice", searchTerms: { zepto: "ginger garlic paste", instamart: "adrak lahsun paste" } },
      { id: "puducherry_dinner_uppu_kari_pondicherry_mutton_pepper_fry_fennel_seeds", name: "Fennel seeds", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "fennel seeds saunf", instamart: "saunf" }, optional: true },
      { id: "puducherry_dinner_uppu_kari_pondicherry_mutton_pepper_fry_curry_leaves", name: "Curry leaves", quantity: 12, unit: "piece", category: "spice", searchTerms: { zepto: "curry leaves", instamart: "kadi patta" }, optional: true },
      { id: "puducherry_dinner_uppu_kari_pondicherry_mutton_pepper_fry_coconut_fresh_sliced_thin", name: "Coconut (fresh, sliced thin)", quantity: 3, unit: "tbsp", category: "other", searchTerms: { zepto: "fresh coconut", instamart: "nariyal" }, optional: true },
      { id: "puducherry_dinner_uppu_kari_pondicherry_mutton_pepper_fry_cooking_oil", name: "Cooking oil", quantity: 3, unit: "tbsp", category: "oil", searchTerms: { zepto: "cooking oil", instamart: "khana pakane ka tel" } }
    ],
    steps: [
      "Pressure cook mutton with turmeric, salt and a little water until tender but not falling apart; reserve any leftover stock.",
      "Heat oil, splutter fennel seeds and curry leaves, then sauté onions until deep golden.",
      "Add ginger garlic paste and cook off the raw smell, then add crushed black pepper and the cooked mutton.",
      "Sauté on high heat, adding a little reserved stock as needed, until the mutton is well coated and most of the liquid evaporates.",
      "Toss in thin coconut slices in the last few minutes and fry until the mutton is dry, glossy and richly browned.",
      "Serve hot with steamed rice or parotta."
    ],
    tags: ["spicy", "dry-roast", "festive"],
  },
];
