import type { Recipe } from "../types";

// Auto-generated from regional recipe research (West zone).
export const WEST_RECIPES: Recipe[] = [
  {
    id: "rajasthan_breakfast_bajre_ki_roti_with_lehsun_chutney",
    name: "Bajre ki Roti with Lehsun Chutney",
    description: "A rustic pearl-millet flatbread served with a fiery garlic chutney and chilled buttermilk, a staple rural Rajasthani breakfast.",
    cuisineRegion: ["Rajasthan"],
    dietType: "veg",
    goalTags: ["maintenance"],
    mealType: ["breakfast"],
    prepTime: 15,
    cookTime: 20,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 320, proteinG: 8, carbsG: 55, fatG: 8 },
    ingredients: [
      { id: "rajasthan_breakfast_bajre_ki_roti_with_lehsun_chutney_bajra_flour", name: "Bajra flour", quantity: 200, unit: "g", category: "grain", searchTerms: { zepto: "bajra flour", instamart: "bajra atta" } },
      { id: "rajasthan_breakfast_bajre_ki_roti_with_lehsun_chutney_garlic", name: "Garlic", quantity: 8, unit: "piece", category: "vegetable", searchTerms: { zepto: "garlic", instamart: "lehsun" } },
      { id: "rajasthan_breakfast_bajre_ki_roti_with_lehsun_chutney_green_chili", name: "Green chili", quantity: 2, unit: "piece", category: "vegetable", searchTerms: { zepto: "green chilli", instamart: "hari mirch" }, optional: true },
      { id: "rajasthan_breakfast_bajre_ki_roti_with_lehsun_chutney_cumin_seeds", name: "Cumin seeds", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "cumin seeds", instamart: "jeera" }, optional: true },
      { id: "rajasthan_breakfast_bajre_ki_roti_with_lehsun_chutney_salt", name: "Salt", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "salt", instamart: "namak" } },
      { id: "rajasthan_breakfast_bajre_ki_roti_with_lehsun_chutney_ghee", name: "Ghee", quantity: 2, unit: "tbsp", category: "oil", searchTerms: { zepto: "ghee", instamart: "desi ghee" } },
      { id: "rajasthan_breakfast_bajre_ki_roti_with_lehsun_chutney_buttermilk", name: "Buttermilk", quantity: 400, unit: "ml", category: "dairy", searchTerms: { zepto: "buttermilk", instamart: "chaas" }, optional: true }
    ],
    steps: [
      "Knead bajra flour with warm water and a pinch of salt into a firm dough; divide into 4 balls.",
      "Pat or roll each ball between plastic sheets into thick rotis, as bajra dough is fragile.",
      "Cook each roti on a hot tawa, flipping and pressing until golden brown spots appear; smear with ghee.",
      "Pound garlic, green chili, cumin and salt together into a coarse chutney using a mortar and pestle.",
      "Serve the hot bajra rotis with lehsun chutney and a glass of chilled buttermilk."
    ],
    tags: ["rustic", "gluten-free", "winter", "traditional"],
  },
  {
    id: "rajasthan_lunch_dal_baati_churma",
    name: "Dal Baati Churma",
    description: "Rajasthan's signature lunch of baked wheat dumplings dunked in ghee, served with spiced lentils and sweet crumbled churma.",
    cuisineRegion: ["Rajasthan"],
    dietType: "veg",
    goalTags: ["maintenance", "weight_gain"],
    mealType: ["lunch"],
    prepTime: 30,
    cookTime: 45,
    servings: 2,
    difficulty: "hard",
    nutrition: { calories: 650, proteinG: 16, carbsG: 80, fatG: 26 },
    ingredients: [
      { id: "rajasthan_lunch_dal_baati_churma_whole_wheat_flour", name: "Whole wheat flour", quantity: 300, unit: "g", category: "grain", searchTerms: { zepto: "wheat flour atta", instamart: "atta" } },
      { id: "rajasthan_lunch_dal_baati_churma_semolina", name: "Semolina", quantity: 2, unit: "tbsp", category: "grain", searchTerms: { zepto: "semolina sooji", instamart: "sooji" }, optional: true },
      { id: "rajasthan_lunch_dal_baati_churma_ghee", name: "Ghee", quantity: 100, unit: "g", category: "oil", searchTerms: { zepto: "ghee", instamart: "desi ghee" } },
      { id: "rajasthan_lunch_dal_baati_churma_mixed_lentils", name: "Mixed lentils", quantity: 150, unit: "g", category: "protein", searchTerms: { zepto: "mixed dal", instamart: "mix dal" } },
      { id: "rajasthan_lunch_dal_baati_churma_tomato", name: "Tomato", quantity: 2, unit: "medium", category: "vegetable", searchTerms: { zepto: "tomato", instamart: "tamatar" } },
      { id: "rajasthan_lunch_dal_baati_churma_onion", name: "Onion", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "pyaz" }, optional: true },
      { id: "rajasthan_lunch_dal_baati_churma_turmeric_powder", name: "Turmeric powder", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "turmeric powder", instamart: "haldi" } },
      { id: "rajasthan_lunch_dal_baati_churma_red_chili_powder", name: "Red chili powder", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "red chilli powder", instamart: "lal mirch powder" }, optional: true },
      { id: "rajasthan_lunch_dal_baati_churma_jaggery", name: "Jaggery", quantity: 100, unit: "g", category: "other", searchTerms: { zepto: "jaggery gur", instamart: "gud" } },
      { id: "rajasthan_lunch_dal_baati_churma_baking_soda", name: "Baking soda", quantity: 1, unit: "tsp", category: "other", searchTerms: { zepto: "baking soda", instamart: "cooking soda" }, optional: true }
    ],
    steps: [
      "Knead wheat flour with semolina, a pinch of baking soda and melted ghee into a stiff dough; shape into round baatis.",
      "Bake the baatis until hard and golden on the outside, then dunk each one in melted ghee.",
      "Pressure cook the mixed lentils with turmeric until soft, then temper with onion, tomato and spices to make the dal.",
      "Crumble a few baatis and mix with ghee and jaggery to prepare the sweet churma.",
      "Serve hot baatis dunked in ghee alongside the dal and a portion of churma."
    ],
    tags: ["festive", "traditional", "hearty", "ghee-rich"],
  },
  {
    id: "rajasthan_snack_pyaaz_kachori",
    name: "Pyaaz Kachori",
    description: "A Jodhpur specialty of crisp deep-fried pastry stuffed with a spiced onion filling, popular as a teatime snack.",
    cuisineRegion: ["Rajasthan"],
    dietType: "veg",
    goalTags: ["maintenance", "weight_loss"],
    mealType: ["snack"],
    prepTime: 30,
    cookTime: 30,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 280, proteinG: 6, carbsG: 32, fatG: 15 },
    ingredients: [
      { id: "rajasthan_snack_pyaaz_kachori_all_purpose_flour", name: "All-purpose flour", quantity: 200, unit: "g", category: "grain", searchTerms: { zepto: "maida flour", instamart: "maida" } },
      { id: "rajasthan_snack_pyaaz_kachori_onion", name: "Onion", quantity: 2, unit: "large", category: "vegetable", searchTerms: { zepto: "onion", instamart: "pyaz" } },
      { id: "rajasthan_snack_pyaaz_kachori_fennel_seeds", name: "Fennel seeds", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "fennel seeds", instamart: "saunf" }, optional: true },
      { id: "rajasthan_snack_pyaaz_kachori_coriander_powder", name: "Coriander powder", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "coriander powder", instamart: "dhaniya powder" }, optional: true },
      { id: "rajasthan_snack_pyaaz_kachori_red_chili_powder", name: "Red chili powder", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "red chilli powder", instamart: "lal mirch powder" }, optional: true },
      { id: "rajasthan_snack_pyaaz_kachori_asafoetida", name: "Asafoetida", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "asafoetida hing", instamart: "hing" }, optional: true },
      { id: "rajasthan_snack_pyaaz_kachori_ghee", name: "Ghee", quantity: 3, unit: "tbsp", category: "oil", searchTerms: { zepto: "ghee", instamart: "desi ghee" } },
      { id: "rajasthan_snack_pyaaz_kachori_oil_for_deep_frying", name: "Oil for deep frying", quantity: 300, unit: "ml", category: "oil", searchTerms: { zepto: "sunflower oil", instamart: "tel" } },
      { id: "rajasthan_snack_pyaaz_kachori_salt", name: "Salt", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "salt", instamart: "namak" } }
    ],
    steps: [
      "Make a stiff dough with maida, a little salt and melted ghee (moyan); rest for 20 minutes.",
      "Sauté finely chopped onion with fennel, coriander powder, chili powder, hing and salt until the mixture is dry.",
      "Roll small dough balls into discs, stuff with the onion filling, and seal into round kachoris.",
      "Deep fry on medium-low heat until crisp and golden brown on all sides.",
      "Serve hot with tamarind or mint chutney."
    ],
    tags: ["fried", "spicy", "street-food", "festive"],
  },
  {
    id: "rajasthan_dinner_laal_maas",
    name: "Laal Maas",
    description: "A fiery Rajasthani mutton curry simmered in a deep red gravy of dried chilies, garlic and yogurt.",
    cuisineRegion: ["Rajasthan"],
    dietType: "nonveg",
    goalTags: ["maintenance", "muscle", "recovery", "weight_gain"],
    mealType: ["dinner"],
    prepTime: 25,
    cookTime: 50,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 420, proteinG: 32, carbsG: 10, fatG: 26 },
    ingredients: [
      { id: "rajasthan_dinner_laal_maas_mutton", name: "Mutton", quantity: 500, unit: "g", category: "protein", searchTerms: { zepto: "mutton goat meat", instamart: "mutton" } },
      { id: "rajasthan_dinner_laal_maas_curd", name: "Curd", quantity: 150, unit: "g", category: "dairy", searchTerms: { zepto: "curd yogurt", instamart: "dahi" } },
      { id: "rajasthan_dinner_laal_maas_dried_red_chili", name: "Dried red chili", quantity: 10, unit: "piece", category: "spice", searchTerms: { zepto: "kashmiri red chilli", instamart: "sukhi lal mirch" } },
      { id: "rajasthan_dinner_laal_maas_garlic_paste", name: "Garlic paste", quantity: 2, unit: "tbsp", category: "vegetable", searchTerms: { zepto: "garlic paste", instamart: "lehsun paste" } },
      { id: "rajasthan_dinner_laal_maas_ginger_paste", name: "Ginger paste", quantity: 1, unit: "tbsp", category: "vegetable", searchTerms: { zepto: "ginger paste", instamart: "adrak paste" }, optional: true },
      { id: "rajasthan_dinner_laal_maas_onion", name: "Onion", quantity: 2, unit: "large", category: "vegetable", searchTerms: { zepto: "onion", instamart: "pyaz" } },
      { id: "rajasthan_dinner_laal_maas_mustard_oil", name: "Mustard oil", quantity: 4, unit: "tbsp", category: "oil", searchTerms: { zepto: "mustard oil", instamart: "sarson tel" } },
      { id: "rajasthan_dinner_laal_maas_whole_garam_masala", name: "Whole garam masala", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "whole garam masala", instamart: "sabut garam masala" }, optional: true },
      { id: "rajasthan_dinner_laal_maas_salt", name: "Salt", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "salt", instamart: "namak" } }
    ],
    steps: [
      "Marinate mutton pieces in curd and salt for at least an hour.",
      "Soak the dried red chilies and grind into a fine paste with garlic paste.",
      "Heat mustard oil, temper the whole garam masala, then sauté sliced onions until golden brown.",
      "Add the red chili paste and cook until oil separates, then add marinated mutton and sear well.",
      "Add water, cover and slow-cook until the mutton is tender and the gravy turns deep red and thick.",
      "Serve hot with bajra roti or steamed rice."
    ],
    tags: ["spicy", "mutton", "festive", "rich"],
  },
  {
    id: "gujarat_breakfast_methi_thepla",
    name: "Methi Thepla",
    description: "A soft spiced flatbread made with fenugreek leaves and whole wheat, a quick everyday Gujarati breakfast.",
    cuisineRegion: ["Gujarat"],
    dietType: "veg",
    goalTags: ["maintenance", "weight_loss"],
    mealType: ["breakfast"],
    prepTime: 15,
    cookTime: 20,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 260, proteinG: 6, carbsG: 40, fatG: 9 },
    ingredients: [
      { id: "gujarat_breakfast_methi_thepla_whole_wheat_flour", name: "Whole wheat flour", quantity: 200, unit: "g", category: "grain", searchTerms: { zepto: "wheat flour atta", instamart: "atta" } },
      { id: "gujarat_breakfast_methi_thepla_fresh_fenugreek_leaves", name: "Fresh fenugreek leaves", quantity: 1, unit: "piece", category: "vegetable", searchTerms: { zepto: "fenugreek leaves methi", instamart: "methi" } },
      { id: "gujarat_breakfast_methi_thepla_besan", name: "Besan", quantity: 2, unit: "tbsp", category: "grain", searchTerms: { zepto: "gram flour besan", instamart: "besan" }, optional: true },
      { id: "gujarat_breakfast_methi_thepla_curd", name: "Curd", quantity: 2, unit: "tbsp", category: "dairy", searchTerms: { zepto: "curd yogurt", instamart: "dahi" }, optional: true },
      { id: "gujarat_breakfast_methi_thepla_turmeric_powder", name: "Turmeric powder", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "turmeric powder", instamart: "haldi" } },
      { id: "gujarat_breakfast_methi_thepla_red_chili_powder", name: "Red chili powder", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "red chilli powder", instamart: "lal mirch powder" }, optional: true },
      { id: "gujarat_breakfast_methi_thepla_carom_seeds", name: "Carom seeds", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "carom seeds ajwain", instamart: "ajwain" }, optional: true },
      { id: "gujarat_breakfast_methi_thepla_oil", name: "Oil", quantity: 3, unit: "tbsp", category: "oil", searchTerms: { zepto: "sunflower oil", instamart: "tel" } },
      { id: "gujarat_breakfast_methi_thepla_salt", name: "Salt", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "salt", instamart: "namak" } }
    ],
    steps: [
      "Mix wheat flour, besan, chopped methi leaves, curd, turmeric, chili powder, ajwain, salt and a little oil into a soft dough.",
      "Rest the dough for 10 minutes, then divide into small balls.",
      "Roll each ball into a thin round and cook on a hot tawa with a little oil until golden brown spots form on both sides.",
      "Serve hot theplas with curd, pickle or chundo."
    ],
    tags: ["quick", "travel-friendly", "everyday", "fiber-rich"],
  },
  {
    id: "gujarat_lunch_undhiyu",
    name: "Undhiyu",
    description: "A slow-cooked winter medley of mixed vegetables and fenugreek dumplings in a coconut-spice masala, Gujarat's most celebrated lunch dish.",
    cuisineRegion: ["Gujarat"],
    dietType: "veg",
    goalTags: ["maintenance"],
    mealType: ["lunch"],
    prepTime: 30,
    cookTime: 45,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 380, proteinG: 10, carbsG: 42, fatG: 18 },
    ingredients: [
      { id: "gujarat_lunch_undhiyu_baby_potato", name: "Baby potato", quantity: 200, unit: "g", category: "vegetable", searchTerms: { zepto: "baby potato", instamart: "chota aloo" } },
      { id: "gujarat_lunch_undhiyu_sweet_potato", name: "Sweet potato", quantity: 150, unit: "g", category: "vegetable", searchTerms: { zepto: "sweet potato", instamart: "shakarkand" }, optional: true },
      { id: "gujarat_lunch_undhiyu_flat_beans_papdi", name: "Flat beans (papdi)", quantity: 150, unit: "g", category: "vegetable", searchTerms: { zepto: "flat beans papdi", instamart: "papdi" } },
      { id: "gujarat_lunch_undhiyu_small_brinjal", name: "Small brinjal", quantity: 4, unit: "piece", category: "vegetable", searchTerms: { zepto: "small brinjal", instamart: "baingan" } },
      { id: "gujarat_lunch_undhiyu_raw_banana", name: "Raw banana", quantity: 1, unit: "piece", category: "vegetable", searchTerms: { zepto: "raw banana", instamart: "kaccha kela" }, optional: true },
      { id: "gujarat_lunch_undhiyu_grated_coconut", name: "Grated coconut", quantity: 3, unit: "tbsp", category: "other", searchTerms: { zepto: "grated coconut", instamart: "nariyal" } },
      { id: "gujarat_lunch_undhiyu_besan", name: "Besan", quantity: 3, unit: "tbsp", category: "grain", searchTerms: { zepto: "gram flour besan", instamart: "besan" }, optional: true },
      { id: "gujarat_lunch_undhiyu_ginger_garlic_green_chili_paste", name: "Ginger-garlic-green chili paste", quantity: 2, unit: "tbsp", category: "vegetable", searchTerms: { zepto: "ginger garlic green chilli paste", instamart: "adrak lehsun hari mirch paste" }, optional: true },
      { id: "gujarat_lunch_undhiyu_oil", name: "Oil", quantity: 4, unit: "tbsp", category: "oil", searchTerms: { zepto: "sunflower oil", instamart: "tel" } },
      { id: "gujarat_lunch_undhiyu_undhiyu_masala", name: "Undhiyu masala", quantity: 2, unit: "tbsp", category: "spice", searchTerms: { zepto: "undhiyu masala", instamart: "undhiyu masala" }, optional: true }
    ],
    steps: [
      "Prepare small besan-fenugreek muthia dumplings and lightly fry or steam them.",
      "Make a stuffing paste of grated coconut, coriander, ginger-garlic-green chili paste and undhiyu masala; stuff into slit baby potatoes, brinjals and banana.",
      "Heat oil in a heavy pot, add the stuffed vegetables along with papdi and sweet potato, and toss well.",
      "Add the remaining masala, cover and slow-cook on low heat until all vegetables are tender.",
      "Fold in the fried muthias in the last few minutes and mix gently.",
      "Serve hot with puri or rotli."
    ],
    tags: ["winter", "festive", "mixed-vegetable", "traditional"],
  },
  {
    id: "gujarat_snack_dhokla",
    name: "Dhokla",
    description: "A light, tangy steamed gram-flour cake tempered with mustard seeds and curry leaves, Gujarat's best-known snack.",
    cuisineRegion: ["Gujarat"],
    dietType: "veg",
    goalTags: ["maintenance", "weight_loss"],
    mealType: ["snack"],
    prepTime: 15,
    cookTime: 20,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 180, proteinG: 7, carbsG: 28, fatG: 5 },
    ingredients: [
      { id: "gujarat_snack_dhokla_besan", name: "Besan", quantity: 200, unit: "g", category: "grain", searchTerms: { zepto: "gram flour besan", instamart: "besan" } },
      { id: "gujarat_snack_dhokla_curd", name: "Curd", quantity: 100, unit: "g", category: "dairy", searchTerms: { zepto: "curd yogurt", instamart: "dahi" } },
      { id: "gujarat_snack_dhokla_eno_fruit_salt", name: "Eno fruit salt", quantity: 1, unit: "tsp", category: "other", searchTerms: { zepto: "eno fruit salt", instamart: "eno" } },
      { id: "gujarat_snack_dhokla_turmeric_powder", name: "Turmeric powder", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "turmeric powder", instamart: "haldi" }, optional: true },
      { id: "gujarat_snack_dhokla_green_chili", name: "Green chili", quantity: 1, unit: "piece", category: "vegetable", searchTerms: { zepto: "green chilli", instamart: "hari mirch" }, optional: true },
      { id: "gujarat_snack_dhokla_mustard_seeds", name: "Mustard seeds", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "mustard seeds", instamart: "rai" }, optional: true },
      { id: "gujarat_snack_dhokla_curry_leaves", name: "Curry leaves", quantity: 10, unit: "piece", category: "spice", searchTerms: { zepto: "curry leaves", instamart: "kadi patta" }, optional: true },
      { id: "gujarat_snack_dhokla_sugar", name: "Sugar", quantity: 2, unit: "tbsp", category: "other", searchTerms: { zepto: "sugar", instamart: "chini" }, optional: true },
      { id: "gujarat_snack_dhokla_oil", name: "Oil", quantity: 2, unit: "tbsp", category: "oil", searchTerms: { zepto: "sunflower oil", instamart: "tel" } }
    ],
    steps: [
      "Whisk besan with curd, turmeric, green chili paste, salt and water into a smooth, lump-free batter.",
      "Just before steaming, add eno fruit salt and mix gently until the batter turns frothy.",
      "Pour into a greased plate and steam for 15-18 minutes until a toothpick comes out clean.",
      "Heat oil, crackle mustard seeds and curry leaves, then add a little water and sugar to make a thin tempering syrup.",
      "Cut the steamed dhokla into squares and pour the tempering evenly over it.",
      "Garnish with coriander and grated coconut, and serve with green chutney."
    ],
    tags: ["steamed", "tangy", "light", "festive"],
  },
  {
    id: "gujarat_dinner_gujarati_kadhi_khichdi",
    name: "Gujarati Kadhi Khichdi",
    description: "A comforting weeknight combo of soft moong dal khichdi with a tangy, lightly sweet yogurt-besan kadhi.",
    cuisineRegion: ["Gujarat"],
    dietType: "veg",
    goalTags: ["maintenance"],
    mealType: ["dinner"],
    prepTime: 15,
    cookTime: 30,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 340, proteinG: 11, carbsG: 50, fatG: 9 },
    ingredients: [
      { id: "gujarat_dinner_gujarati_kadhi_khichdi_rice", name: "Rice", quantity: 150, unit: "g", category: "grain", searchTerms: { zepto: "rice", instamart: "chawal" } },
      { id: "gujarat_dinner_gujarati_kadhi_khichdi_moong_dal", name: "Moong dal", quantity: 100, unit: "g", category: "protein", searchTerms: { zepto: "moong dal", instamart: "moong dal" } },
      { id: "gujarat_dinner_gujarati_kadhi_khichdi_curd", name: "Curd", quantity: 300, unit: "ml", category: "dairy", searchTerms: { zepto: "curd yogurt", instamart: "dahi" } },
      { id: "gujarat_dinner_gujarati_kadhi_khichdi_besan", name: "Besan", quantity: 2, unit: "tbsp", category: "grain", searchTerms: { zepto: "gram flour besan", instamart: "besan" } },
      { id: "gujarat_dinner_gujarati_kadhi_khichdi_ginger_green_chili_paste", name: "Ginger-green chili paste", quantity: 1, unit: "tsp", category: "vegetable", searchTerms: { zepto: "ginger green chilli paste", instamart: "adrak hari mirch paste" }, optional: true },
      { id: "gujarat_dinner_gujarati_kadhi_khichdi_mustard_seeds", name: "Mustard seeds", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "mustard seeds", instamart: "rai" }, optional: true },
      { id: "gujarat_dinner_gujarati_kadhi_khichdi_curry_leaves", name: "Curry leaves", quantity: 10, unit: "piece", category: "spice", searchTerms: { zepto: "curry leaves", instamart: "kadi patta" }, optional: true },
      { id: "gujarat_dinner_gujarati_kadhi_khichdi_jaggery", name: "Jaggery", quantity: 1, unit: "tbsp", category: "other", searchTerms: { zepto: "jaggery gur", instamart: "gud" }, optional: true },
      { id: "gujarat_dinner_gujarati_kadhi_khichdi_ghee", name: "Ghee", quantity: 2, unit: "tbsp", category: "oil", searchTerms: { zepto: "ghee", instamart: "desi ghee" } }
    ],
    steps: [
      "Wash and pressure cook rice and moong dal together with turmeric and salt until soft and mushy to make khichdi.",
      "Whisk curd with besan and water until smooth, then bring to a gentle boil, stirring continuously to make the kadhi base.",
      "Add ginger-green chili paste, jaggery and salt to the kadhi and simmer for 10 minutes.",
      "Temper with ghee, mustard seeds and curry leaves, then pour over the kadhi.",
      "Serve hot khichdi with a generous ladle of kadhi and a dollop of ghee on top."
    ],
    tags: ["comfort-food", "everyday", "mild", "digestive"],
  },
  {
    id: "maharashtra_breakfast_kanda_poha",
    name: "Kanda Poha",
    description: "Flattened rice tossed with onions, peanuts and a tempering of mustard seeds and curry leaves, the everyday Maharashtrian breakfast.",
    cuisineRegion: ["Maharashtra"],
    dietType: "veg",
    goalTags: ["maintenance", "weight_loss"],
    mealType: ["breakfast"],
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 250, proteinG: 5, carbsG: 40, fatG: 8 },
    ingredients: [
      { id: "maharashtra_breakfast_kanda_poha_flattened_rice_poha", name: "Flattened rice (poha)", quantity: 200, unit: "g", category: "grain", searchTerms: { zepto: "poha flattened rice", instamart: "poha" } },
      { id: "maharashtra_breakfast_kanda_poha_onion", name: "Onion", quantity: 1, unit: "large", category: "vegetable", searchTerms: { zepto: "onion", instamart: "pyaz" } },
      { id: "maharashtra_breakfast_kanda_poha_potato", name: "Potato", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "potato", instamart: "aloo" }, optional: true },
      { id: "maharashtra_breakfast_kanda_poha_mustard_seeds", name: "Mustard seeds", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "mustard seeds", instamart: "rai" }, optional: true },
      { id: "maharashtra_breakfast_kanda_poha_curry_leaves", name: "Curry leaves", quantity: 10, unit: "piece", category: "spice", searchTerms: { zepto: "curry leaves", instamart: "kadi patta" }, optional: true },
      { id: "maharashtra_breakfast_kanda_poha_turmeric_powder", name: "Turmeric powder", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "turmeric powder", instamart: "haldi" } },
      { id: "maharashtra_breakfast_kanda_poha_green_chili", name: "Green chili", quantity: 2, unit: "piece", category: "vegetable", searchTerms: { zepto: "green chilli", instamart: "hari mirch" }, optional: true },
      { id: "maharashtra_breakfast_kanda_poha_roasted_peanuts", name: "Roasted peanuts", quantity: 2, unit: "tbsp", category: "protein", searchTerms: { zepto: "roasted peanuts", instamart: "moongfali" }, optional: true },
      { id: "maharashtra_breakfast_kanda_poha_lemon", name: "Lemon", quantity: 1, unit: "piece", category: "fruit", searchTerms: { zepto: "lemon", instamart: "nimbu" } },
      { id: "maharashtra_breakfast_kanda_poha_oil", name: "Oil", quantity: 3, unit: "tbsp", category: "oil", searchTerms: { zepto: "sunflower oil", instamart: "tel" } }
    ],
    steps: [
      "Rinse poha briefly in water and drain; set aside to soften.",
      "Heat oil, crackle mustard seeds, curry leaves and chopped green chili, then add peanuts and diced potato and cook until tender.",
      "Add chopped onion and sauté until translucent, then stir in turmeric and salt.",
      "Add the softened poha, toss gently to coat evenly, and cook covered for 2-3 minutes.",
      "Finish with a squeeze of lemon juice and chopped coriander before serving."
    ],
    tags: ["quick", "everyday", "light", "tangy"],
  },
  {
    id: "maharashtra_lunch_pithla_bhakri",
    name: "Pithla Bhakri",
    description: "A rustic gram-flour curry served with roasted millet flatbread, a beloved everyday Maharashtrian lunch.",
    cuisineRegion: ["Maharashtra"],
    dietType: "veg",
    goalTags: ["maintenance"],
    mealType: ["lunch"],
    prepTime: 10,
    cookTime: 25,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 320, proteinG: 12, carbsG: 40, fatG: 12 },
    ingredients: [
      { id: "maharashtra_lunch_pithla_bhakri_besan", name: "Besan", quantity: 150, unit: "g", category: "grain", searchTerms: { zepto: "gram flour besan", instamart: "besan" } },
      { id: "maharashtra_lunch_pithla_bhakri_jowar_flour", name: "Jowar flour", quantity: 200, unit: "g", category: "grain", searchTerms: { zepto: "jowar flour", instamart: "jowar atta" } },
      { id: "maharashtra_lunch_pithla_bhakri_onion", name: "Onion", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "pyaz" }, optional: true },
      { id: "maharashtra_lunch_pithla_bhakri_garlic", name: "Garlic", quantity: 4, unit: "piece", category: "vegetable", searchTerms: { zepto: "garlic", instamart: "lehsun" }, optional: true },
      { id: "maharashtra_lunch_pithla_bhakri_green_chili", name: "Green chili", quantity: 2, unit: "piece", category: "vegetable", searchTerms: { zepto: "green chilli", instamart: "hari mirch" }, optional: true },
      { id: "maharashtra_lunch_pithla_bhakri_mustard_seeds", name: "Mustard seeds", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "mustard seeds", instamart: "rai" }, optional: true },
      { id: "maharashtra_lunch_pithla_bhakri_turmeric_powder", name: "Turmeric powder", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "turmeric powder", instamart: "haldi" } },
      { id: "maharashtra_lunch_pithla_bhakri_asafoetida", name: "Asafoetida", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "asafoetida hing", instamart: "hing" }, optional: true },
      { id: "maharashtra_lunch_pithla_bhakri_oil", name: "Oil", quantity: 3, unit: "tbsp", category: "oil", searchTerms: { zepto: "sunflower oil", instamart: "tel" } },
      { id: "maharashtra_lunch_pithla_bhakri_salt", name: "Salt", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "salt", instamart: "namak" } }
    ],
    steps: [
      "Knead jowar flour with warm water into a soft dough and pat into thick round bhakris.",
      "Roast the bhakris directly on a tawa and open flame until cooked through with charred spots.",
      "Heat oil, temper mustard seeds, hing, chopped garlic and green chili, then sauté onion until soft.",
      "Add water, turmeric and salt, bring to a boil, then whisk in besan gradually, stirring until it thickens into a smooth pithla.",
      "Serve the hot pithla with bhakri, a drizzle of raw oil and chopped onion on the side."
    ],
    tags: ["rustic", "everyday", "comfort-food", "gluten-free"],
  },
  {
    id: "maharashtra_snack_vada_pav",
    name: "Vada Pav",
    description: "Mumbai's iconic street snack of a spiced potato fritter sandwiched in a soft bun with garlic chutney.",
    cuisineRegion: ["Maharashtra"],
    dietType: "veg",
    goalTags: ["maintenance"],
    mealType: ["snack"],
    prepTime: 20,
    cookTime: 20,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 460, proteinG: 10, carbsG: 58, fatG: 18 },
    ingredients: [
      { id: "maharashtra_snack_vada_pav_potato", name: "Potato", quantity: 4, unit: "medium", category: "vegetable", searchTerms: { zepto: "potato", instamart: "aloo" } },
      { id: "maharashtra_snack_vada_pav_pav_bread_buns", name: "Pav (bread buns)", quantity: 4, unit: "piece", category: "grain", searchTerms: { zepto: "pav bread", instamart: "pav" } },
      { id: "maharashtra_snack_vada_pav_besan", name: "Besan", quantity: 150, unit: "g", category: "grain", searchTerms: { zepto: "gram flour besan", instamart: "besan" } },
      { id: "maharashtra_snack_vada_pav_mustard_seeds", name: "Mustard seeds", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "mustard seeds", instamart: "rai" }, optional: true },
      { id: "maharashtra_snack_vada_pav_curry_leaves", name: "Curry leaves", quantity: 10, unit: "piece", category: "spice", searchTerms: { zepto: "curry leaves", instamart: "kadi patta" }, optional: true },
      { id: "maharashtra_snack_vada_pav_ginger_garlic_green_chili_paste", name: "Ginger-garlic-green chili paste", quantity: 1, unit: "tbsp", category: "vegetable", searchTerms: { zepto: "ginger garlic green chilli paste", instamart: "adrak lehsun hari mirch paste" }, optional: true },
      { id: "maharashtra_snack_vada_pav_turmeric_powder", name: "Turmeric powder", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "turmeric powder", instamart: "haldi" } },
      { id: "maharashtra_snack_vada_pav_dry_garlic_chutney", name: "Dry garlic chutney", quantity: 2, unit: "tbsp", category: "other", searchTerms: { zepto: "garlic chutney", instamart: "lehsun chutney" }, optional: true },
      { id: "maharashtra_snack_vada_pav_oil_for_frying", name: "Oil for frying", quantity: 300, unit: "ml", category: "oil", searchTerms: { zepto: "sunflower oil", instamart: "tel" } }
    ],
    steps: [
      "Boil, peel and mash potatoes; temper with mustard seeds, curry leaves and ginger-garlic-green chili paste, then mix in turmeric and salt to make the vada filling.",
      "Shape the potato mixture into round balls.",
      "Dip each ball in a seasoned besan batter and deep fry until golden and crisp.",
      "Slit the pav buns and spread garlic chutney inside.",
      "Sandwich a hot vada inside each pav and serve with fried green chilies."
    ],
    tags: ["street-food", "fried", "spicy", "iconic"],
  },
  {
    id: "maharashtra_dinner_kolhapuri_chicken",
    name: "Kolhapuri Chicken",
    description: "A fiery Kolhapur-style chicken curry built on a roasted coconut and dried red chili masala.",
    cuisineRegion: ["Maharashtra"],
    dietType: "nonveg",
    goalTags: ["maintenance", "muscle", "recovery", "weight_gain"],
    mealType: ["dinner"],
    prepTime: 20,
    cookTime: 40,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 430, proteinG: 34, carbsG: 12, fatG: 26 },
    ingredients: [
      { id: "maharashtra_dinner_kolhapuri_chicken_chicken_curry_cut", name: "Chicken curry cut", quantity: 500, unit: "g", category: "protein", searchTerms: { zepto: "chicken curry cut", instamart: "chicken" } },
      { id: "maharashtra_dinner_kolhapuri_chicken_onion", name: "Onion", quantity: 2, unit: "large", category: "vegetable", searchTerms: { zepto: "onion", instamart: "pyaz" } },
      { id: "maharashtra_dinner_kolhapuri_chicken_tomato", name: "Tomato", quantity: 2, unit: "medium", category: "vegetable", searchTerms: { zepto: "tomato", instamart: "tamatar" } },
      { id: "maharashtra_dinner_kolhapuri_chicken_dried_red_chili", name: "Dried red chili", quantity: 8, unit: "piece", category: "spice", searchTerms: { zepto: "dried red chilli", instamart: "sukhi lal mirch" } },
      { id: "maharashtra_dinner_kolhapuri_chicken_desiccated_coconut", name: "Desiccated coconut", quantity: 3, unit: "tbsp", category: "other", searchTerms: { zepto: "desiccated coconut", instamart: "sukha nariyal" } },
      { id: "maharashtra_dinner_kolhapuri_chicken_ginger_garlic_paste", name: "Ginger-garlic paste", quantity: 1, unit: "tbsp", category: "vegetable", searchTerms: { zepto: "ginger garlic paste", instamart: "adrak lehsun paste" } },
      { id: "maharashtra_dinner_kolhapuri_chicken_kolhapuri_masala", name: "Kolhapuri masala", quantity: 2, unit: "tbsp", category: "spice", searchTerms: { zepto: "kolhapuri masala", instamart: "kolhapuri masala" }, optional: true },
      { id: "maharashtra_dinner_kolhapuri_chicken_oil", name: "Oil", quantity: 4, unit: "tbsp", category: "oil", searchTerms: { zepto: "sunflower oil", instamart: "tel" } },
      { id: "maharashtra_dinner_kolhapuri_chicken_coriander_leaves", name: "Coriander leaves", quantity: 1, unit: "piece", category: "vegetable", searchTerms: { zepto: "coriander leaves", instamart: "dhaniya patta" }, optional: true }
    ],
    steps: [
      "Dry roast dried red chilies and desiccated coconut until fragrant, then grind into a fine paste with a little water.",
      "Heat oil, sauté onions until deep golden, then add ginger-garlic paste and cook until the raw smell disappears.",
      "Add chopped tomatoes and cook until soft, then stir in the roasted chili-coconut paste and Kolhapuri masala.",
      "Add chicken pieces, mix well to coat, and cook covered on medium heat until tender and the oil separates.",
      "Adjust water for gravy consistency, simmer for a few minutes, and garnish with coriander before serving."
    ],
    tags: ["spicy", "fiery", "festive", "rich"],
  },
  {
    id: "goa_breakfast_goan_ros_omelette",
    name: "Goan Ros Omelette",
    description: "Sliced egg omelette simmered in a light coconut-tomato gravy, a popular spicy Goan breakfast served with pav.",
    cuisineRegion: ["Goa"],
    dietType: "egg",
    goalTags: ["maintenance", "weight_loss"],
    mealType: ["breakfast"],
    prepTime: 10,
    cookTime: 15,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 280, proteinG: 16, carbsG: 10, fatG: 20 },
    ingredients: [
      { id: "goa_breakfast_goan_ros_omelette_eggs", name: "Eggs", quantity: 4, unit: "piece", category: "protein", searchTerms: { zepto: "eggs", instamart: "anda" } },
      { id: "goa_breakfast_goan_ros_omelette_onion", name: "Onion", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "pyaz" } },
      { id: "goa_breakfast_goan_ros_omelette_tomato", name: "Tomato", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "tomato", instamart: "tamatar" }, optional: true },
      { id: "goa_breakfast_goan_ros_omelette_coconut_milk", name: "Coconut milk", quantity: 100, unit: "ml", category: "dairy", searchTerms: { zepto: "coconut milk", instamart: "nariyal doodh" } },
      { id: "goa_breakfast_goan_ros_omelette_kashmiri_red_chili_powder", name: "Kashmiri red chili powder", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "kashmiri red chilli powder", instamart: "lal mirch powder" }, optional: true },
      { id: "goa_breakfast_goan_ros_omelette_turmeric_powder", name: "Turmeric powder", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "turmeric powder", instamart: "haldi" }, optional: true },
      { id: "goa_breakfast_goan_ros_omelette_garlic", name: "Garlic", quantity: 3, unit: "piece", category: "vegetable", searchTerms: { zepto: "garlic", instamart: "lehsun" }, optional: true },
      { id: "goa_breakfast_goan_ros_omelette_vinegar", name: "Vinegar", quantity: 1, unit: "tsp", category: "other", searchTerms: { zepto: "vinegar", instamart: "sirka" }, optional: true },
      { id: "goa_breakfast_goan_ros_omelette_oil", name: "Oil", quantity: 2, unit: "tbsp", category: "oil", searchTerms: { zepto: "sunflower oil", instamart: "tel" } },
      { id: "goa_breakfast_goan_ros_omelette_pav_bread", name: "Pav bread", quantity: 2, unit: "piece", category: "grain", searchTerms: { zepto: "pav bread", instamart: "pav" }, optional: true }
    ],
    steps: [
      "Make thin plain omelettes with beaten eggs and a little salt, then set aside and slice into strips.",
      "Sauté chopped onion and garlic in oil until soft, then add tomato and cook until pulpy.",
      "Stir in turmeric, chili powder, coconut milk and a splash of vinegar, and simmer into a light gravy.",
      "Add the sliced omelette strips to the gravy and simmer for 2-3 minutes so they soak up the sauce.",
      "Serve the ros omelette hot with pav bread."
    ],
    tags: ["spicy", "coastal", "quick", "protein-rich"],
  },
  {
    id: "goa_lunch_goan_fish_curry_with_rice",
    name: "Goan Fish Curry with Rice",
    description: "The quintessential Goan meal of fresh fish simmered in a tangy coconut-chili curry, served over steamed rice.",
    cuisineRegion: ["Goa"],
    dietType: "nonveg",
    goalTags: ["maintenance", "muscle", "recovery"],
    mealType: ["lunch"],
    prepTime: 20,
    cookTime: 30,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 480, proteinG: 28, carbsG: 55, fatG: 14 },
    ingredients: [
      { id: "goa_lunch_goan_fish_curry_with_rice_fish_pomfret_or_kingfish", name: "Fish (pomfret or kingfish)", quantity: 500, unit: "g", category: "protein", searchTerms: { zepto: "fish pomfret", instamart: "machli" } },
      { id: "goa_lunch_goan_fish_curry_with_rice_grated_coconut", name: "Grated coconut", quantity: 1, unit: "piece", category: "other", searchTerms: { zepto: "grated coconut", instamart: "nariyal" } },
      { id: "goa_lunch_goan_fish_curry_with_rice_dried_red_chili", name: "Dried red chili", quantity: 6, unit: "piece", category: "spice", searchTerms: { zepto: "dried red chilli", instamart: "sukhi lal mirch" } },
      { id: "goa_lunch_goan_fish_curry_with_rice_tamarind", name: "Tamarind", quantity: 1, unit: "tbsp", category: "other", searchTerms: { zepto: "tamarind", instamart: "imli" } },
      { id: "goa_lunch_goan_fish_curry_with_rice_turmeric_powder", name: "Turmeric powder", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "turmeric powder", instamart: "haldi" } },
      { id: "goa_lunch_goan_fish_curry_with_rice_coriander_seeds", name: "Coriander seeds", quantity: 1, unit: "tbsp", category: "spice", searchTerms: { zepto: "coriander seeds", instamart: "sabut dhaniya" }, optional: true },
      { id: "goa_lunch_goan_fish_curry_with_rice_onion", name: "Onion", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "pyaz" } },
      { id: "goa_lunch_goan_fish_curry_with_rice_green_chili", name: "Green chili", quantity: 2, unit: "piece", category: "vegetable", searchTerms: { zepto: "green chilli", instamart: "hari mirch" }, optional: true },
      { id: "goa_lunch_goan_fish_curry_with_rice_rice", name: "Rice", quantity: 200, unit: "g", category: "grain", searchTerms: { zepto: "rice", instamart: "chawal" } },
      { id: "goa_lunch_goan_fish_curry_with_rice_coconut_oil", name: "Coconut oil", quantity: 2, unit: "tbsp", category: "oil", searchTerms: { zepto: "coconut oil", instamart: "nariyal tel" }, optional: true }
    ],
    steps: [
      "Grind grated coconut, dried red chilies, coriander seeds and turmeric with a little water into a smooth masala paste.",
      "Heat coconut oil in a pan, sauté sliced onion and slit green chilies until soft.",
      "Add the ground masala paste along with tamarind pulp and enough water to form a curry, and bring to a boil.",
      "Simmer for 8-10 minutes, then gently slide in the fish pieces and cook until just done, without over-stirring.",
      "Cook rice separately until fluffy, and serve alongside the hot fish curry."
    ],
    tags: ["coastal", "tangy", "spicy", "iconic"],
  },
  {
    id: "goa_snack_choris_pao_chorizo_pav",
    name: "Choris Pao (Chorizo Pav)",
    description: "Spiced, tangy Goan pork chorizo stuffed into a soft pav bun, a much-loved Goan street snack.",
    cuisineRegion: ["Goa"],
    dietType: "nonveg",
    goalTags: ["maintenance"],
    mealType: ["snack"],
    prepTime: 15,
    cookTime: 20,
    servings: 2,
    difficulty: "easy",
    nutrition: { calories: 350, proteinG: 18, carbsG: 28, fatG: 20 },
    ingredients: [
      { id: "goa_snack_choris_pao_chorizo_pav_goan_pork_chorizo_sausage", name: "Goan pork chorizo sausage", quantity: 250, unit: "g", category: "protein", searchTerms: { zepto: "pork chorizo sausage", instamart: "chorizo" } },
      { id: "goa_snack_choris_pao_chorizo_pav_pav_bread", name: "Pav bread", quantity: 4, unit: "piece", category: "grain", searchTerms: { zepto: "pav bread", instamart: "pav" } },
      { id: "goa_snack_choris_pao_chorizo_pav_onion", name: "Onion", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "pyaz" } },
      { id: "goa_snack_choris_pao_chorizo_pav_tomato", name: "Tomato", quantity: 1, unit: "medium", category: "vegetable", searchTerms: { zepto: "tomato", instamart: "tamatar" }, optional: true },
      { id: "goa_snack_choris_pao_chorizo_pav_garlic", name: "Garlic", quantity: 3, unit: "piece", category: "vegetable", searchTerms: { zepto: "garlic", instamart: "lehsun" }, optional: true },
      { id: "goa_snack_choris_pao_chorizo_pav_turmeric_powder", name: "Turmeric powder", quantity: 1, unit: "tsp", category: "spice", searchTerms: { zepto: "turmeric powder", instamart: "haldi" }, optional: true },
      { id: "goa_snack_choris_pao_chorizo_pav_vinegar", name: "Vinegar", quantity: 1, unit: "tsp", category: "other", searchTerms: { zepto: "vinegar", instamart: "sirka" }, optional: true },
      { id: "goa_snack_choris_pao_chorizo_pav_oil", name: "Oil", quantity: 1, unit: "tbsp", category: "oil", searchTerms: { zepto: "sunflower oil", instamart: "tel" } }
    ],
    steps: [
      "Remove the chorizo from its casing and crumble it into a hot pan.",
      "Sauté chopped onion and garlic in a little oil until soft, then add the chorizo and cook, breaking it up further.",
      "Add chopped tomato, turmeric and a splash of vinegar, and cook until the mixture is rich and slightly dry.",
      "Simmer for a few minutes until the fat renders and the masala clings to the meat.",
      "Slit the pav buns, stuff generously with the hot chorizo mixture, and serve immediately."
    ],
    tags: ["spicy", "street-food", "pork", "coastal"],
  },
  {
    id: "goa_dinner_goan_vegetable_xacuti",
    name: "Goan Vegetable Xacuti",
    description: "Mixed vegetables simmered in Goa's signature roasted coconut and dried chili xacuti masala, a fragrant vegetarian dinner curry.",
    cuisineRegion: ["Goa"],
    dietType: "veg",
    goalTags: ["maintenance"],
    mealType: ["dinner"],
    prepTime: 20,
    cookTime: 30,
    servings: 2,
    difficulty: "medium",
    nutrition: { calories: 300, proteinG: 8, carbsG: 30, fatG: 16 },
    ingredients: [
      { id: "goa_dinner_goan_vegetable_xacuti_mixed_vegetables", name: "Mixed vegetables", quantity: 400, unit: "g", category: "vegetable", searchTerms: { zepto: "mixed vegetables", instamart: "mix sabzi" } },
      { id: "goa_dinner_goan_vegetable_xacuti_grated_coconut", name: "Grated coconut", quantity: 1, unit: "piece", category: "other", searchTerms: { zepto: "grated coconut", instamart: "nariyal" } },
      { id: "goa_dinner_goan_vegetable_xacuti_dried_red_chili", name: "Dried red chili", quantity: 5, unit: "piece", category: "spice", searchTerms: { zepto: "dried red chilli", instamart: "sukhi lal mirch" } },
      { id: "goa_dinner_goan_vegetable_xacuti_poppy_seeds", name: "Poppy seeds", quantity: 1, unit: "tbsp", category: "spice", searchTerms: { zepto: "poppy seeds khus khus", instamart: "khus khus" }, optional: true },
      { id: "goa_dinner_goan_vegetable_xacuti_coriander_seeds", name: "Coriander seeds", quantity: 1, unit: "tbsp", category: "spice", searchTerms: { zepto: "coriander seeds", instamart: "sabut dhaniya" }, optional: true },
      { id: "goa_dinner_goan_vegetable_xacuti_star_anise", name: "Star anise", quantity: 1, unit: "piece", category: "spice", searchTerms: { zepto: "star anise", instamart: "chakra phool" }, optional: true },
      { id: "goa_dinner_goan_vegetable_xacuti_onion", name: "Onion", quantity: 2, unit: "medium", category: "vegetable", searchTerms: { zepto: "onion", instamart: "pyaz" } },
      { id: "goa_dinner_goan_vegetable_xacuti_tamarind", name: "Tamarind", quantity: 1, unit: "tsp", category: "other", searchTerms: { zepto: "tamarind", instamart: "imli" }, optional: true },
      { id: "goa_dinner_goan_vegetable_xacuti_oil", name: "Oil", quantity: 3, unit: "tbsp", category: "oil", searchTerms: { zepto: "sunflower oil", instamart: "tel" } }
    ],
    steps: [
      "Dry roast grated coconut, dried red chilies, poppy seeds, coriander seeds and star anise until aromatic, then cool and grind into a fine xacuti masala paste.",
      "Heat oil and sauté sliced onion until golden brown.",
      "Add the ground xacuti masala paste and cook until the oil separates from the mixture.",
      "Add the mixed vegetables along with tamarind pulp and enough water, then cover and simmer until the vegetables are tender.",
      "Adjust seasoning and consistency, and serve hot with steamed rice or poee bread."
    ],
    tags: ["coastal", "spicy", "roasted-spices", "veg"],
  },
];
